import type { SaveCandidate } from '@/data/pattern-examples-full'

/**
 * Story paragraph saveCandidates — auto-generated by scripts/generate-story-chunks.mjs
 * 444 / 500 paragraphs have chunk data.
 */
export const storyChunks: Record<string, SaveCandidate[]> = {
  'p1-1': [
    { text: "I want to", type: 'chunk', start: 50, end: 59 },
    { text: "want to", type: 'collocation', start: 52, end: 59 },
  ],
  'p1-2': [
    { text: "I'm thinking about", type: 'chunk', start: 0, end: 18 },
    { text: "thinking about", type: 'phrasalVerb', start: 4, end: 18 },
    { text: "every night", type: 'collocation', start: 43, end: 54 },
    { text: "doesn't have to", type: 'chunk', start: 90, end: 105 },
    { text: "have to", type: 'collocation', start: 98, end: 105 },
  ],
  'p1-3': [
    { text: "stay positive", type: 'collocation', start: 68, end: 81 },
  ],
  'p1-4': [
    { text: "That's because", type: 'chunk', start: 0, end: 14 },
    { text: "I want to", type: 'chunk', start: 83, end: 92 },
    { text: "want to", type: 'collocation', start: 85, end: 92 },
    { text: "hold on to", type: 'phrasalVerb', start: 93, end: 103 },
  ],
  'p1-5': [
    { text: "It turns out", type: 'chunk', start: 34, end: 46 },
    { text: "new start", type: 'collocation', start: 76, end: 85 },
  ],
  'p2-1': [
    { text: "old friend", type: 'collocation', start: 15, end: 25 },
    { text: "a long time", type: 'prepPhrase', start: 127, end: 138 },
    { text: "long time", type: 'collocation', start: 129, end: 138 },
  ],
  'p2-2': [
    { text: "I used to", type: 'chunk', start: 0, end: 9 },
    { text: "used to", type: 'phrasalVerb', start: 2, end: 9 },
    { text: "used to", type: 'collocation', start: 2, end: 9 },
    { text: "felt tired", type: 'collocation', start: 34, end: 44 },
    { text: "a lot of", type: 'prepPhrase', start: 55, end: 63 },
    { text: "I don't want to", type: 'chunk', start: 82, end: 97 },
    { text: "want to", type: 'collocation', start: 90, end: 97 },
  ],
  'p2-3': [
    { text: "sat down", type: 'phrasalVerb', start: 9, end: 17 },
    { text: "I'm sorry", type: 'chunk', start: 28, end: 37 },
  ],
  'p2-4': [
    { text: "It seems like", type: 'chunk', start: 0, end: 13 },
  ],
  'p2-5': [
    { text: "I'm looking forward to", type: 'chunk', start: 41, end: 63 },
    { text: "looking forward to", type: 'phrasalVerb', start: 45, end: 63 },
    { text: "from now on", type: 'prepPhrase', start: 87, end: 98 },
  ],
  'p3-1': [
    { text: "in the morning", type: 'prepPhrase', start: 11, end: 25 },
    { text: "have to", type: 'collocation', start: 54, end: 61 },
  ],
  'p3-2': [
    { text: "in the morning", type: 'prepPhrase', start: 21, end: 35 },
    { text: "instead", type: 'chunk', start: 55, end: 62 },
  ],
  'p3-3': [
    { text: "Let me help you", type: 'fixedExpression', start: 34, end: 49 },
    { text: "Let me help", type: 'chunk', start: 34, end: 45 },
  ],
  'p3-4': [
    { text: "small kindness", type: 'collocation', start: 49, end: 63 },
  ],
  'p3-5': [
    { text: "wanted to", type: 'collocation', start: 7, end: 16 },
  ],
  'p4-1': [
    { text: "have a big presentation", type: 'collocation', start: 2, end: 25 },
    { text: "I've practiced", type: 'chunk', start: 52, end: 66 },
    { text: "for a whole", type: 'prepPhrase', start: 67, end: 78 },
    { text: "a whole week", type: 'collocation', start: 71, end: 83 },
  ],
  'p4-2': [
    { text: "think about", type: 'phrasalVerb', start: 58, end: 69 },
    { text: "I guess", type: 'chunk', start: 89, end: 96 },
  ],
  'p4-3': [
    { text: "again and again", type: 'prepPhrase', start: 25, end: 40 },
    { text: "want to", type: 'collocation', start: 85, end: 92 },
  ],
  'p4-4': [
    { text: "turn off", type: 'phrasalVerb', start: 32, end: 40 },
    { text: "deep breath", type: 'collocation', start: 62, end: 73 },
    { text: "either way", type: 'fixedExpression', start: 94, end: 104 },
    { text: "either way", type: 'prepPhrase', start: 94, end: 104 },
    { text: "either way", type: 'chunk', start: 94, end: 104 },
  ],
  'p4-5': [
    { text: "supposed to", type: 'collocation', start: 4, end: 15 },
    { text: "supposed to", type: 'chunk', start: 4, end: 15 },
    { text: "just in case", type: 'prepPhrase', start: 59, end: 71 },
    { text: "just in", type: 'chunk', start: 59, end: 66 },
  ],
  'p5-1': [
    { text: "by the window", type: 'prepPhrase', start: 14, end: 27 },
    { text: "for a long time", type: 'prepPhrase', start: 28, end: 43 },
    { text: "long time", type: 'collocation', start: 34, end: 43 },
    { text: "I'm going to", type: 'chunk', start: 45, end: 57 },
  ],
  'p5-2': [
    { text: "I'm going to", type: 'chunk', start: 0, end: 12 },
    { text: "waking up", type: 'phrasalVerb', start: 17, end: 26 },
    { text: "feel like", type: 'phrasalVerb', start: 68, end: 77 },
  ],
  'p5-3': [
    { text: "I've been", type: 'chunk', start: 0, end: 9 },
    { text: "for a while", type: 'prepPhrase', start: 24, end: 35 },
    { text: "asking for", type: 'phrasalVerb', start: 91, end: 101 },
  ],
  'p5-4': [
    { text: "That's when", type: 'chunk', start: 95, end: 106 },
  ],
  'p5-5': [
    { text: "feel like", type: 'phrasalVerb', start: 2, end: 11 },
  ],
  'p6-1': [
    { text: "I'm not sure", type: 'chunk', start: 45, end: 57 },
  ],
  'p6-2': [
    { text: "tend to", type: 'collocation', start: 2, end: 9 },
  ],
  'p6-3': [
    { text: "right answer", type: 'collocation', start: 14, end: 26 },
    { text: "It depends on", type: 'chunk', start: 94, end: 107 },
  ],
  'p6-4': [
    { text: "I'm trying to", type: 'chunk', start: 0, end: 13 },
    { text: "listen to", type: 'phrasalVerb', start: 14, end: 23 },
    { text: "instead of", type: 'prepPhrase', start: 31, end: 41 },
    { text: "instead", type: 'chunk', start: 31, end: 38 },
    { text: "has to", type: 'collocation', start: 109, end: 115 },
  ],
  'p6-5': [
    { text: "Even though", type: 'prepPhrase', start: 0, end: 11 },
  ],
  'p7-1': [
    { text: "As long as", type: 'prepPhrase', start: 40, end: 50 },
  ],
  'p7-2': [
    { text: "No wonder", type: 'prepPhrase', start: 36, end: 45 },
    { text: "No wonder", type: 'chunk', start: 36, end: 45 },
  ],
  'p7-3': [
    { text: "I'd rather", type: 'chunk', start: 40, end: 50 },
    { text: "need to", type: 'collocation', start: 92, end: 99 },
  ],
  'p7-4': [
    { text: "ended up", type: 'phrasalVerb', start: 43, end: 51 },
    { text: "for a whole", type: 'prepPhrase', start: 66, end: 77 },
    { text: "It was the best", type: 'chunk', start: 84, end: 99 },
    { text: "the best part", type: 'prepPhrase', start: 91, end: 104 },
  ],
  'p7-5': [
    { text: "Can you", type: 'chunk', start: 36, end: 43 },
    { text: "for a long time", type: 'prepPhrase', start: 108, end: 123 },
    { text: "long time", type: 'collocation', start: 114, end: 123 },
  ],
  'p8-1': [
    { text: "Could you", type: 'chunk', start: 46, end: 55 },
    { text: "by the window", type: 'prepPhrase', start: 72, end: 85 },
  ],
  'p8-2': [
    { text: "I'd like to", type: 'chunk', start: 28, end: 39 },
  ],
  'p8-3': [
    { text: "Why don't we", type: 'chunk', start: 39, end: 51 },
  ],
  'p8-4': [
    { text: "Would you", type: 'chunk', start: 38, end: 47 },
    { text: "turning on", type: 'phrasalVerb', start: 53, end: 63 },
    { text: "right away", type: 'prepPhrase', start: 103, end: 113 },
  ],
  'p8-5': [
    { text: "It was getting", type: 'chunk', start: 0, end: 14 },
  ],
  'p9-1': [
    { text: "Make sure", type: 'phrasalVerb', start: 43, end: 52 },
    { text: "Make sure", type: 'collocation', start: 43, end: 52 },
  ],
  'p9-2': [
    { text: "do you want", type: 'chunk', start: 5, end: 16 },
    { text: "want to", type: 'collocation', start: 12, end: 19 },
    { text: "have time", type: 'collocation', start: 86, end: 95 },
  ],
  'p9-3': [
    { text: "Have you ever", type: 'chunk', start: 1, end: 14 },
    { text: "made a funny face", type: 'collocation', start: 50, end: 67 },
    { text: "I'm curious", type: 'chunk', start: 93, end: 104 },
  ],
  'p9-4': [
    { text: "Do you know", type: 'chunk', start: 1, end: 12 },
  ],
  'p9-5': [
    { text: "instead", type: 'chunk', start: 34, end: 41 },
  ],
  'p10-1': [
    { text: "What do you think", type: 'chunk', start: 32, end: 49 },
    { text: "think about", type: 'phrasalVerb', start: 44, end: 55 },
  ],
  'p10-2': [
    { text: "New streets", type: 'collocation', start: 40, end: 51 },
    { text: "new faces", type: 'collocation', start: 53, end: 62 },
    { text: "new mornings", type: 'collocation', start: 64, end: 76 },
  ],
  'p10-3': [
    { text: "I can't wait", type: 'chunk', start: 0, end: 12 },
    { text: "feel like", type: 'phrasalVerb', start: 102, end: 111 },
  ],
  'p10-4': [
    { text: "so much", type: 'prepPhrase', start: 31, end: 38 },
  ],
  'p10-5': [
    { text: "worried about", type: 'phrasalVerb', start: 11, end: 24 },
    { text: "worried about", type: 'chunk', start: 11, end: 24 },
    { text: "at first", type: 'prepPhrase', start: 61, end: 69 },
  ],
  'p11-1': [
    { text: "I'm afraid I", type: 'chunk', start: 53, end: 65 },
    { text: "put down", type: 'phrasalVerb', start: 110, end: 118 },
  ],
  'p11-2': [
    { text: "To be honest", type: 'fixedExpression', start: 1, end: 13 },
    { text: "To be honest", type: 'prepPhrase', start: 1, end: 13 },
    { text: "for a while", type: 'prepPhrase', start: 34, end: 45 },
    { text: "easy to", type: 'collocation', start: 70, end: 77 },
    { text: "out loud", type: 'collocation', start: 82, end: 90 },
    { text: "out loud", type: 'prepPhrase', start: 82, end: 90 },
    { text: "out loud", type: 'chunk', start: 82, end: 90 },
  ],
  'p11-3': [
    { text: "I don't think", type: 'chunk', start: 1, end: 14 },
    { text: "the same", type: 'chunk', start: 23, end: 31 },
    { text: "went on", type: 'phrasalVerb', start: 51, end: 58 },
  ],
  'p11-4': [
    { text: "I'd been", type: 'chunk', start: 63, end: 71 },
    { text: "felt like", type: 'phrasalVerb', start: 113, end: 122 },
  ],
  'p11-5': [
    { text: "in silence", type: 'prepPhrase', start: 7, end: 17 },
    { text: "for a moment", type: 'prepPhrase', start: 18, end: 30 },
    { text: "for a moment", type: 'chunk', start: 18, end: 30 },
  ],
  'p12-1': [
    { text: "I was wondering", type: 'chunk', start: 94, end: 109 },
  ],
  'p12-2': [
    { text: "showed up", type: 'phrasalVerb', start: 3, end: 12 },
  ],
  'p12-3': [
    { text: "on the phone", type: 'prepPhrase', start: 86, end: 98 },
  ],
  'p12-4': [
    { text: "On the way", type: 'prepPhrase', start: 0, end: 10 },
    { text: "had time", type: 'collocation', start: 37, end: 45 },
    { text: "Let me know", type: 'chunk', start: 56, end: 67 },
  ],
  'p12-5': [
    { text: "show up", type: 'phrasalVerb', start: 129, end: 136 },
  ],
  'p13-1': [
    { text: "I'll get", type: 'chunk', start: 58, end: 66 },
    { text: "get back", type: 'phrasalVerb', start: 63, end: 71 },
    { text: "want to", type: 'collocation', start: 124, end: 131 },
  ],
  'p13-2': [
    { text: "sat down", type: 'phrasalVerb', start: 11, end: 19 },
    { text: "Let's go", type: 'chunk', start: 43, end: 51 },
  ],
  'p13-3': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
    { text: "Just to", type: 'chunk', start: 41, end: 48 },
  ],
  'p13-4': [
    { text: "take care of", type: 'phrasalVerb', start: 66, end: 78 },
    { text: "take care", type: 'fixedExpression', start: 66, end: 75 },
    { text: "take care", type: 'collocation', start: 66, end: 75 },
  ],
  'p13-5': [
    { text: "Can you", type: 'chunk', start: 47, end: 54 },
    { text: "walk me through", type: 'collocation', start: 55, end: 70 },
    { text: "pulled up", type: 'phrasalVerb', start: 107, end: 116 },
    { text: "pulled up a chair", type: 'collocation', start: 107, end: 124 },
    { text: "happy to help", type: 'collocation', start: 126, end: 139 },
  ],
  'p14-1': [
    { text: "back-to-back", type: 'prepPhrase', start: 26, end: 38 },
    { text: "Can we", type: 'chunk', start: 50, end: 56 },
    { text: "said that worked", type: 'collocation', start: 127, end: 143 },
  ],
  'p14-2': [
    { text: "follow up", type: 'phrasalVerb', start: 64, end: 73 },
    { text: "can't wait", type: 'chunk', start: 136, end: 146 },
  ],
  'p14-3': [
    { text: "drifting toward", type: 'phrasalVerb', start: 20, end: 35 },
    { text: "Let's circle back", type: 'chunk', start: 63, end: 80 },
    { text: "circle back", type: 'phrasalVerb', start: 69, end: 80 },
  ],
  'p14-4': [
    { text: "I'll have the draft", type: 'chunk', start: 50, end: 69 },
    { text: "by end of day", type: 'prepPhrase', start: 75, end: 88 },
    { text: "by end of day", type: 'chunk', start: 75, end: 88 },
    { text: "Saying it out loud", type: 'chunk', start: 99, end: 117 },
    { text: "out loud", type: 'collocation', start: 109, end: 117 },
    { text: "out loud", type: 'prepPhrase', start: 109, end: 117 },
  ],
  'p14-5': [
    { text: "No problem", type: 'prepPhrase', start: 55, end: 65 },
    { text: "No problem", type: 'chunk', start: 55, end: 65 },
    { text: "right now", type: 'prepPhrase', start: 78, end: 87 },
  ],
  'p15-1': [
    { text: "started with", type: 'phrasalVerb', start: 9, end: 21 },
  ],
  'p15-2': [
    { text: "got lost", type: 'collocation', start: 36, end: 44 },
    { text: "as soon as", type: 'prepPhrase', start: 70, end: 80 },
  ],
  'p15-3': [
    { text: "looking for", type: 'phrasalVerb', start: 36, end: 47 },
    { text: "By the time", type: 'chunk', start: 64, end: 75 },
  ],
  'p15-4': [
    { text: "stayed calm", type: 'collocation', start: 10, end: 21 },
  ],
  'p15-5': [
    { text: "That's why", type: 'chunk', start: 61, end: 71 },
    { text: "a lot of", type: 'prepPhrase', start: 132, end: 140 },
  ],
  'p16-1': [
    { text: "Now that", type: 'chunk', start: 51, end: 59 },
    { text: "feel the energy", type: 'collocation', start: 116, end: 131 },
    { text: "the energy shift", type: 'chunk', start: 121, end: 137 },
  ],
  'p16-2': [
    { text: "whether", type: 'chunk', start: 14, end: 21 },
    { text: "go with", type: 'phrasalVerb', start: 27, end: 34 },
    { text: "Either way", type: 'fixedExpression', start: 54, end: 64 },
    { text: "Either way", type: 'prepPhrase', start: 54, end: 64 },
    { text: "Either way", type: 'chunk', start: 54, end: 64 },
    { text: "by Friday", type: 'prepPhrase', start: 85, end: 94 },
  ],
  'p16-3': [
    { text: "what could go wrong", type: 'chunk', start: 28, end: 47 },
    { text: "Let's say", type: 'chunk', start: 50, end: 59 },
    { text: "save us later", type: 'chunk', start: 129, end: 142 },
  ],
  'p16-4': [
    { text: "starting with", type: 'phrasalVerb', start: 49, end: 62 },
  ],
  'p16-5': [
    { text: "It might be better to", type: 'chunk', start: 42, end: 63 },
  ],
  'p17-1': [
    { text: "pouring out", type: 'phrasalVerb', start: 43, end: 54 },
    { text: "Sounds like", type: 'chunk', start: 57, end: 68 },
    { text: "caught me up", type: 'chunk', start: 109, end: 121 },
    { text: "that was an understatement", type: 'chunk', start: 144, end: 170 },
  ],
  'p17-2': [
    { text: "wrapped up", type: 'phrasalVerb', start: 11, end: 21 },
    { text: "It makes sense", type: 'fixedExpression', start: 47, end: 61 },
    { text: "take a break", type: 'collocation', start: 65, end: 77 },
    { text: "after all", type: 'prepPhrase', start: 78, end: 87 },
    { text: "needs to", type: 'collocation', start: 116, end: 124 },
  ],
  'p17-3': [
    { text: "It was getting", type: 'chunk', start: 0, end: 14 },
  ],
  'p17-4': [
    { text: "it's up to you", type: 'fixedExpression', start: 66, end: 80 },
    { text: "it's up to you", type: 'chunk', start: 66, end: 80 },
    { text: "I'm easy", type: 'chunk', start: 91, end: 99 },
  ],
  'p17-5': [
    { text: "want to", type: 'collocation', start: 119, end: 126 },
    { text: "stretch out", type: 'phrasalVerb', start: 127, end: 138 },
  ],
  'p18-1': [
    { text: "I guess", type: 'chunk', start: 47, end: 54 },
    { text: "stay in", type: 'phrasalVerb', start: 65, end: 72 },
    { text: "Some Sundays", type: 'chunk', start: 99, end: 111 },
  ],
  'p18-2': [
    { text: "going out", type: 'phrasalVerb', start: 22, end: 31 },
    { text: "right now", type: 'prepPhrase', start: 71, end: 80 },
  ],
  'p18-3': [
    { text: "wanted to", type: 'collocation', start: 4, end: 13 },
  ],
  'p18-4': [
    { text: "thought about", type: 'phrasalVerb', start: 3, end: 16 },
    { text: "instead", type: 'chunk', start: 51, end: 58 },
    { text: "As far as", type: 'prepPhrase', start: 61, end: 70 },
  ],
  'p18-5': [
    { text: "On second thought", type: 'fixedExpression', start: 50, end: 67 },
    { text: "instead", type: 'chunk', start: 125, end: 132 },
  ],
  'p19-1': [
    { text: "Long story short", type: 'fixedExpression', start: 45, end: 61 },
    { text: "Long story short", type: 'prepPhrase', start: 45, end: 61 },
    { text: "Long story short", type: 'chunk', start: 45, end: 61 },
    { text: "by total accident", type: 'prepPhrase', start: 70, end: 87 },
    { text: "total accident", type: 'collocation', start: 73, end: 87 },
    { text: "The full version", type: 'chunk', start: 103, end: 119 },
  ],
  'p19-2': [
    { text: "the same", type: 'chunk', start: 117, end: 125 },
  ],
  'p19-3': [
    { text: "ended up", type: 'phrasalVerb', start: 3, end: 11 },
  ],
  'p19-4': [
    { text: "the whole thing", type: 'chunk', start: 31, end: 46 },
    { text: "It's like we'd", type: 'chunk', start: 49, end: 63 },
    { text: "Some people just", type: 'chunk', start: 100, end: 116 },
  ],
  'p19-5': [
    { text: "at the corner", type: 'prepPhrase', start: 9, end: 22 },
    { text: "I guess", type: 'chunk', start: 101, end: 108 },
    { text: "I'll have", type: 'chunk', start: 109, end: 118 },
    { text: "have to", type: 'collocation', start: 114, end: 121 },
  ],
  'p20-1': [
    { text: "look forward to", type: 'phrasalVerb', start: 148, end: 163 },
  ],
  'p20-2': [
    { text: "new place", type: 'collocation', start: 26, end: 35 },
    { text: "I'll let you know", type: 'collocation', start: 42, end: 59 },
  ],
  'p20-3': [
    { text: "tried to", type: 'collocation', start: 3, end: 11 },
    { text: "pulled up", type: 'phrasalVerb', start: 101, end: 110 },
  ],
  'p20-4': [
    { text: "worry about", type: 'phrasalVerb', start: 59, end: 70 },
  ],
  'p20-5': [
    { text: "at the corner", type: 'prepPhrase', start: 10, end: 23 },
    { text: "I'll catch you later", type: 'fixedExpression', start: 50, end: 70 },
    { text: "I'll catch you later", type: 'chunk', start: 50, end: 70 },
  ],
  'p21-1': [
    { text: "Do you have", type: 'chunk', start: 47, end: 58 },
  ],
  'p21-2': [
    { text: "Can I", type: 'chunk', start: 40, end: 45 },
    { text: "fitting room", type: 'collocation', start: 98, end: 110 },
  ],
  'p21-3': [
    { text: "right away", type: 'prepPhrase', start: 126, end: 136 },
  ],
  'p21-4': [
    { text: "How much is", type: 'chunk', start: 39, end: 50 },
  ],
  'p21-5': [
    { text: "I'll take it", type: 'chunk', start: 46, end: 58 },
    { text: "fits perfectly", type: 'phrasalVerb', start: 64, end: 78 },
    { text: "fits perfectly", type: 'collocation', start: 64, end: 78 },
  ],
  'p22-1': [
    { text: "arrived in", type: 'phrasalVerb', start: 10, end: 20 },
    { text: "in the wrong size", type: 'prepPhrase', start: 18, end: 35 },
    { text: "Can I", type: 'chunk', start: 44, end: 49 },
    { text: "within a minute", type: 'prepPhrase', start: 112, end: 127 },
  ],
  'p22-2': [
    { text: "How long does", type: 'chunk', start: 38, end: 51 },
    { text: "two business days", type: 'prepPhrase', start: 98, end: 115 },
  ],
  'p22-3': [
    { text: "new tracking", type: 'collocation', start: 109, end: 121 },
  ],
  'p22-4': [
    { text: "free returns", type: 'collocation', start: 56, end: 68 },
    { text: "within thirty days", type: 'prepPhrase', start: 96, end: 114 },
  ],
  'p22-5': [
    { text: "by tonight", type: 'prepPhrase', start: 113, end: 123 },
    { text: "by tonight", type: 'chunk', start: 113, end: 123 },
  ],
  'p23-1': [
    { text: "I'll have", type: 'chunk', start: 43, end: 52 },
    { text: "the same", type: 'chunk', start: 108, end: 116 },
  ],
  'p23-2': [
    { text: "What do you recommend", type: 'chunk', start: 47, end: 68 },
    { text: "house special", type: 'collocation', start: 123, end: 136 },
  ],
  'p23-3': [
    { text: "Does this come with", type: 'chunk', start: 46, end: 65 },
    { text: "come with", type: 'phrasalVerb', start: 56, end: 65 },
  ],
  'p23-4': [
    { text: "Just so you know", type: 'fixedExpression', start: 43, end: 59 },
    { text: "Just so you know", type: 'chunk', start: 43, end: 59 },
    { text: "I'm allergic to", type: 'chunk', start: 61, end: 76 },
  ],
  'p23-5': [
    { text: "Can we", type: 'chunk', start: 48, end: 54 },
  ],
  'p24-1': [
    { text: "looked up", type: 'phrasalVerb', start: 11, end: 20 },
  ],
  'p24-2': [
    { text: "take a deep breath", type: 'collocation', start: 51, end: 69 },
  ],
  'p24-3': [
    { text: "going on", type: 'phrasalVerb', start: 31, end: 39 },
    { text: "I've had", type: 'chunk', start: 42, end: 50 },
    { text: "listened to", type: 'phrasalVerb', start: 94, end: 105 },
  ],
  'p24-4': [
    { text: "come back", type: 'phrasalVerb', start: 62, end: 71 },
  ],
  'p24-5': [
    { text: "wanted to", type: 'collocation', start: 7, end: 16 },
    { text: "feel better", type: 'collocation', start: 54, end: 65 },
  ],
  'p25-1': [
    { text: "at the counter", type: 'prepPhrase', start: 20, end: 34 },
    { text: "Do you have", type: 'chunk', start: 37, end: 48 },
  ],
  'p25-2': [
    { text: "looking for", type: 'phrasalVerb', start: 53, end: 64 },
  ],
  'p25-3': [
    { text: "coming down with", type: 'phrasalVerb', start: 56, end: 72 },
  ],
  'p25-4': [
    { text: "Is it safe to", type: 'chunk', start: 44, end: 57 },
  ],
  'p25-5': [
    { text: "want to", type: 'collocation', start: 51, end: 58 },
  ],
  'p26-1': [
    { text: "I'm here to", type: 'chunk', start: 37, end: 48 },
  ],
  'p26-2': [
    { text: "Could you", type: 'chunk', start: 38, end: 47 },
  ],
  'p26-3': [
    { text: "pointed to", type: 'phrasalVerb', start: 93, end: 103 },
  ],
  'p26-4': [
    { text: "How much do I owe", type: 'chunk', start: 48, end: 65 },
  ],
  'p26-5': [
    { text: "at the counter", type: 'prepPhrase', start: 24, end: 38 },
    { text: "Can I", type: 'chunk', start: 41, end: 46 },
    { text: "either", type: 'chunk', start: 129, end: 135 },
  ],
  'p27-1': [
    { text: "checking in", type: 'phrasalVerb', start: 42, end: 53 },
    { text: "asked for", type: 'phrasalVerb', start: 97, end: 106 },
  ],
  'p27-2': [
    { text: "at once", type: 'prepPhrase', start: 34, end: 41 },
  ],
  'p27-3': [
    { text: "have time", type: 'collocation', start: 49, end: 58 },
  ],
  'p27-4': [
    { text: "What time does", type: 'chunk', start: 41, end: 55 },
    { text: "in about twenty minutes", type: 'prepPhrase', start: 91, end: 114 },
  ],
  'p27-5': [
    { text: "I think I'm at the wrong", type: 'chunk', start: 46, end: 70 },
    { text: "one terminal over", type: 'prepPhrase', start: 110, end: 127 },
  ],
  'p28-1': [
    { text: "I have a reservation", type: 'chunk', start: 53, end: 73 },
  ],
  'p28-2': [
    { text: "Is breakfast included", type: 'chunk', start: 41, end: 62 },
  ],
  'p28-3': [
    { text: "check in", type: 'phrasalVerb', start: 54, end: 62 },
  ],
  'p28-4': [
    { text: "a few times", type: 'prepPhrase', start: 18, end: 29 },
    { text: "with no luck", type: 'prepPhrase', start: 30, end: 42 },
  ],
  'p28-5': [
    { text: "Is there a good place", type: 'fixedExpression', start: 46, end: 67 },
    { text: "Is there a good place", type: 'chunk', start: 46, end: 67 },
  ],
  'p29-1': [
    { text: "I need to", type: 'chunk', start: 47, end: 56 },
    { text: "need to", type: 'collocation', start: 49, end: 56 },
  ],
  'p29-2': [
    { text: "Is it far", type: 'chunk', start: 43, end: 52 },
  ],
  'p29-3': [
    { text: "the same", type: 'chunk', start: 41, end: 49 },
  ],
  'p29-4': [
    { text: "Do you take cards", type: 'chunk', start: 45, end: 62 },
  ],
  'p29-5': [
    { text: "keep the change", type: 'fixedExpression', start: 53, end: 68 },
    { text: "keep the change", type: 'collocation', start: 53, end: 68 },
  ],
  'p30-1': [
    { text: "running out of", type: 'phrasalVerb', start: 46, end: 60 },
    { text: "just in time", type: 'prepPhrase', start: 111, end: 123 },
    { text: "just in", type: 'chunk', start: 111, end: 118 },
  ],
  'p30-2': [
    { text: "turned up", type: 'phrasalVerb', start: 85, end: 94 },
  ],
  'p30-3': [
    { text: "Watch out for", type: 'phrasalVerb', start: 46, end: 59 },
    { text: "Watch out for", type: 'fixedExpression', start: 46, end: 59 },
  ],
  'p30-4': [
    { text: "pull over", type: 'phrasalVerb', start: 51, end: 60 },
    { text: "for a quick break", type: 'prepPhrase', start: 61, end: 78 },
    { text: "a quick break", type: 'fixedExpression', start: 65, end: 78 },
  ],
  'p30-5': [
    { text: "beat the rush", type: 'fixedExpression', start: 70, end: 83 },
  ],
  'p31-1': [
    { text: "It looks like", type: 'chunk', start: 47, end: 60 },
    { text: "just in case", type: 'prepPhrase', start: 115, end: 127 },
    { text: "just in", type: 'chunk', start: 115, end: 122 },
  ],
  'p31-2': [
    { text: "It's freezing", type: 'chunk', start: 45, end: 58 },
  ],
  'p31-3': [
    { text: "What's the weather like", type: 'chunk', start: 40, end: 63 },
  ],
  'p31-4': [
    { text: "by noon", type: 'prepPhrase', start: 28, end: 35 },
    { text: "I can't stand", type: 'chunk', start: 38, end: 51 },
  ],
  'p31-5': [
    { text: "make the most of", type: 'fixedExpression', start: 50, end: 66 },
  ],
  'p32-1': [
    { text: "work out", type: 'phrasalVerb', start: 47, end: 55 },
    { text: "asked for", type: 'phrasalVerb', start: 111, end: 120 },
  ],
  'p32-2': [
    { text: "I'm sore from", type: 'chunk', start: 40, end: 53 },
  ],
  'p32-3': [
    { text: "warm up", type: 'phrasalVerb', start: 49, end: 56 },
    { text: "a slow lap", type: 'fixedExpression', start: 102, end: 112 },
  ],
  'p32-4': [
    { text: "I've been", type: 'chunk', start: 44, end: 53 },
    { text: "go with", type: 'phrasalVerb', start: 105, end: 112 },
  ],
  'p32-5': [
    { text: "Getting up", type: 'phrasalVerb', start: 0, end: 10 },
    { text: "waking up", type: 'phrasalVerb', start: 46, end: 55 },
    { text: "the whole thing", type: 'chunk', start: 102, end: 117 },
  ],
  'p33-1': [
    { text: "wanted to", type: 'collocation', start: 100, end: 109 },
  ],
  'p33-2': [
    { text: "in the corner", type: 'prepPhrase', start: 21, end: 34 },
    { text: "wanted to", type: 'collocation', start: 61, end: 70 },
  ],
  'p33-3': [
    { text: "good at", type: 'chunk', start: 56, end: 63 },
  ],
  'p33-4': [
    { text: "helps me relax", type: 'chunk', start: 54, end: 68 },
  ],
  'p33-5': [
    { text: "picked up", type: 'phrasalVerb', start: 52, end: 61 },
  ],
  'p34-1': [
    { text: "It's your turn", type: 'chunk', start: 41, end: 55 },
    { text: "do the dishes", type: 'fixedExpression', start: 59, end: 72 },
    { text: "do the dishes", type: 'collocation', start: 59, end: 72 },
    { text: "rolled up", type: 'phrasalVerb', start: 106, end: 115 },
  ],
  'p34-2': [
    { text: "Can you", type: 'chunk', start: 38, end: 45 },
  ],
  'p34-3': [
    { text: "take out", type: 'phrasalVerb', start: 54, end: 62 },
  ],
  'p34-4': [
    { text: "a total mess", type: 'fixedExpression', start: 59, end: 71 },
    { text: "a total mess", type: 'chunk', start: 59, end: 71 },
  ],
  'p35-1': [
    { text: "get ready", type: 'collocation', start: 76, end: 85 },
    { text: "ready for", type: 'chunk', start: 80, end: 89 },
  ],
  'p35-2': [
    { text: "brush your teeth", type: 'collocation', start: 51, end: 67 },
  ],
  'p35-3': [
    { text: "slowed down", type: 'phrasalVerb', start: 97, end: 108 },
  ],
  'p35-4': [
    { text: "by the door", type: 'prepPhrase', start: 23, end: 34 },
    { text: "by herself", type: 'prepPhrase', start: 39, end: 49 },
    { text: "Good job", type: 'collocation', start: 52, end: 60 },
    { text: "lit up", type: 'phrasalVerb', start: 110, end: 116 },
  ],
  'p35-5': [
    { text: "the same", type: 'chunk', start: 31, end: 39 },
    { text: "need to", type: 'collocation', start: 50, end: 57 },
    { text: "thought about", type: 'phrasalVerb', start: 103, end: 116 },
  ],
  'p36-1': [
    { text: "I'm majoring in", type: 'chunk', start: 41, end: 56 },
    { text: "majoring in", type: 'collocation', start: 45, end: 56 },
    { text: "lit up", type: 'phrasalVerb', start: 88, end: 94 },
  ],
  'p36-2': [
    { text: "at all", type: 'prepPhrase', start: 73, end: 79 },
    { text: "walked me through", type: 'collocation', start: 98, end: 115 },
    { text: "step by step", type: 'prepPhrase', start: 119, end: 131 },
  ],
  'p36-3': [
    { text: "due on Friday", type: 'prepPhrase', start: 64, end: 77 },
  ],
  'p36-4': [
    { text: "Want to", type: 'collocation', start: 40, end: 47 },
    { text: "new place", type: 'collocation', start: 114, end: 123 },
  ],
  'p36-5': [
    { text: "I'm behind on", type: 'fixedExpression', start: 40, end: 53 },
    { text: "I'm behind on", type: 'chunk', start: 40, end: 53 },
    { text: "behind on my", type: 'prepPhrase', start: 44, end: 56 },
  ],
  'p37-1': [
    { text: "picked up", type: 'phrasalVerb', start: 9, end: 18 },
    { text: "can I", type: 'chunk', start: 41, end: 46 },
    { text: "right away", type: 'prepPhrase', start: 107, end: 117 },
  ],
  'p37-2': [
    { text: "for a second", type: 'prepPhrase', start: 19, end: 31 },
    { text: "Can you", type: 'chunk', start: 43, end: 50 },
  ],
  'p37-3': [
    { text: "no problem", type: 'prepPhrase', start: 111, end: 121 },
    { text: "no problem", type: 'chunk', start: 111, end: 121 },
    { text: "at all", type: 'prepPhrase', start: 122, end: 128 },
  ],
  'p37-4': [
    { text: "breaking up", type: 'phrasalVerb', start: 59, end: 70 },
  ],
  'p37-5': [
    { text: "at the door", type: 'prepPhrase', start: 73, end: 84 },
  ],
  'p38-1': [
    { text: "get started", type: 'collocation', start: 52, end: 63 },
  ],
  'p38-2': [
    { text: "Moving on", type: 'phrasalVerb', start: 41, end: 50 },
  ],
  'p38-3': [
    { text: "sum up", type: 'phrasalVerb', start: 42, end: 48 },
  ],
  'p38-4': [
    { text: "make sense", type: 'phrasalVerb', start: 50, end: 60 },
    { text: "so far", type: 'prepPhrase', start: 61, end: 67 },
  ],
  'p38-5': [
    { text: "wrap up", type: 'phrasalVerb', start: 53, end: 60 },
  ],
  'p39-1': [
    { text: "Would it be", type: 'chunk', start: 40, end: 51 },
  ],
  'p39-2': [
    { text: "looking for", type: 'phrasalVerb', start: 104, end: 115 },
  ],
  'p39-3': [
    { text: "wanted to", type: 'collocation', start: 14, end: 23 },
    { text: "give up", type: 'phrasalVerb', start: 24, end: 31 },
  ],
  'p39-4': [
    { text: "Can we", type: 'chunk', start: 41, end: 47 },
  ],
  'p39-5': [
    { text: "Let's find a way", type: 'chunk', start: 43, end: 59 },
  ],
  'p40-1': [
    { text: "I can't believe", type: 'chunk', start: 41, end: 56 },
  ],
  'p40-2': [
    { text: "happy to", type: 'collocation', start: 57, end: 65 },
  ],
  'p40-3': [
    { text: "proud of", type: 'chunk', start: 51, end: 59 },
  ],
  'p40-4': [
    { text: "It drives me", type: 'chunk', start: 45, end: 57 },
    { text: "drives me crazy", type: 'fixedExpression', start: 48, end: 63 },
    { text: "drives me crazy", type: 'collocation', start: 48, end: 63 },
    { text: "take a breath", type: 'collocation', start: 118, end: 131 },
  ],
  'p40-5': [
    { text: "came back", type: 'phrasalVerb', start: 25, end: 34 },
  ],
  'p41-1': [
    { text: "Is it too late to", type: 'chunk', start: 42, end: 59 },
  ],
  'p41-2': [
    { text: "without any fuss", type: 'chunk', start: 117, end: 133 },
  ],
  'p41-3': [
    { text: "Can I", type: 'chunk', start: 52, end: 57 },
  ],
  'p41-4': [
    { text: "asked for", type: 'phrasalVerb', start: 4, end: 13 },
    { text: "right away", type: 'prepPhrase', start: 32, end: 42 },
  ],
  'p41-5': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
  ],
  'p42-1': [
    { text: "Do you deliver", type: 'chunk', start: 42, end: 56 },
  ],
  'p42-2': [
    { text: "within fifteen minutes", type: 'prepPhrase', start: 101, end: 123 },
  ],
  'p42-3': [
    { text: "Can you", type: 'chunk', start: 46, end: 53 },
  ],
  'p42-4': [
    { text: "by the door", type: 'prepPhrase', start: 114, end: 125 },
  ],
  'p42-5': [
    { text: "that really hit", type: 'chunk', start: 48, end: 63 },
    { text: "hit the spot", type: 'fixedExpression', start: 60, end: 72 },
    { text: "hit the spot", type: 'collocation', start: 60, end: 72 },
  ],
  'p43-1': [
    { text: "is this seat taken", type: 'fixedExpression', start: 59, end: 77 },
    { text: "is this seat taken", type: 'chunk', start: 59, end: 77 },
  ],
  'p43-2': [
    { text: "no problem", type: 'prepPhrase', start: 112, end: 122 },
    { text: "no problem", type: 'chunk', start: 112, end: 122 },
  ],
  'p43-3': [
    { text: "When do we", type: 'chunk', start: 41, end: 51 },
    { text: "in about two hours", type: 'prepPhrase', start: 96, end: 114 },
  ],
  'p43-4': [
    { text: "for a while", type: 'prepPhrase', start: 35, end: 46 },
  ],
  'p43-5': [
    { text: "take off", type: 'phrasalVerb', start: 54, end: 62 },
  ],
  'p44-1': [
    { text: "with no luck", type: 'prepPhrase', start: 27, end: 39 },
    { text: "can I", type: 'chunk', start: 48, end: 53 },
    { text: "pointed to", type: 'phrasalVerb', start: 93, end: 103 },
  ],
  'p44-2': [
    { text: "Am I allowed to", type: 'chunk', start: 38, end: 53 },
  ],
  'p44-3': [
    { text: "backed out", type: 'phrasalVerb', start: 91, end: 101 },
  ],
  'p44-4': [
    { text: "came back", type: 'phrasalVerb', start: 2, end: 11 },
  ],
  'p44-5': [
    { text: "gave up", type: 'phrasalVerb', start: 89, end: 96 },
    { text: "instead", type: 'chunk', start: 116, end: 123 },
  ],
  'p45-1': [
    { text: "pointed to", type: 'phrasalVerb', start: 94, end: 104 },
  ],
  'p45-2': [
    { text: "I can't connect to", type: 'chunk', start: 45, end: 63 },
    { text: "connect to", type: 'phrasalVerb', start: 53, end: 63 },
  ],
  'p45-3': [
    { text: "Is the internet down", type: 'chunk', start: 52, end: 72 },
  ],
  'p45-4': [
    { text: "Have you tried", type: 'chunk', start: 46, end: 60 },
  ],
  'p45-5': [
    { text: "over and over", type: 'prepPhrase', start: 18, end: 31 },
    { text: "with no luck", type: 'prepPhrase', start: 32, end: 44 },
    { text: "no matter what", type: 'fixedExpression', start: 61, end: 75 },
    { text: "no matter what", type: 'prepPhrase', start: 61, end: 75 },
    { text: "take a look", type: 'collocation', start: 107, end: 118 },
  ],
  'p46-1': [
    { text: "by Friday", type: 'prepPhrase', start: 70, end: 79 },
  ],
  'p46-2': [
    { text: "needs to", type: 'collocation', start: 37, end: 45 },
  ],
  'p46-3': [
    { text: "I need to", type: 'chunk', start: 38, end: 47 },
    { text: "need to", type: 'collocation', start: 40, end: 47 },
  ],
  'p46-4': [
    { text: "at once", type: 'prepPhrase', start: 28, end: 35 },
  ],
  'p46-5': [
    { text: "It should arrive", type: 'chunk', start: 43, end: 59 },
    { text: "arrive in", type: 'phrasalVerb', start: 53, end: 62 },
    { text: "in three days", type: 'prepPhrase', start: 60, end: 73 },
  ],
  'p47-1': [
    { text: "Do you have", type: 'chunk', start: 39, end: 50 },
  ],
  'p47-3': [
    { text: "at least", type: 'prepPhrase', start: 95, end: 103 },
    { text: "at least", type: 'chunk', start: 95, end: 103 },
  ],
  'p47-4': [
    { text: "can I", type: 'chunk', start: 66, end: 71 },
  ],
  'p47-5': [
    { text: "opened up", type: 'phrasalVerb', start: 25, end: 34 },
  ],
  'p48-1': [
    { text: "I'm sorry", type: 'chunk', start: 34, end: 43 },
    { text: "no problem", type: 'prepPhrase', start: 105, end: 115 },
    { text: "no problem", type: 'chunk', start: 105, end: 115 },
    { text: "at all", type: 'prepPhrase', start: 116, end: 122 },
  ],
  'p48-2': [
    { text: "Can we", type: 'chunk', start: 37, end: 43 },
  ],
  'p48-3': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
  ],
  'p48-4': [
    { text: "I won't be able to make it", type: 'fixedExpression', start: 37, end: 63 },
    { text: "I won't be able to", type: 'chunk', start: 37, end: 55 },
    { text: "try again next week", type: 'fixedExpression', start: 95, end: 114 },
  ],
  'p48-5': [
    { text: "instead", type: 'chunk', start: 68, end: 75 },
    { text: "right away", type: 'prepPhrase', start: 110, end: 120 },
  ],
  'p49-1': [
    { text: "looked around", type: 'phrasalVerb', start: 25, end: 38 },
  ],
  'p49-2': [
    { text: "pointed to", type: 'phrasalVerb', start: 97, end: 107 },
    { text: "by the window", type: 'prepPhrase', start: 117, end: 130 },
  ],
  'p49-3': [
    { text: "slowed down", type: 'phrasalVerb', start: 93, end: 104 },
  ],
  'p49-4': [
    { text: "put on", type: 'phrasalVerb', start: 97, end: 103 },
  ],
  'p49-5': [
    { text: "look like", type: 'phrasalVerb', start: 34, end: 43 },
  ],
  'p50-1': [
    { text: "There's something wrong", type: 'chunk', start: 44, end: 67 },
    { text: "by noon", type: 'prepPhrase', start: 135, end: 142 },
  ],
  'p50-2': [
    { text: "Can you", type: 'chunk', start: 43, end: 50 },
    { text: "take a look", type: 'collocation', start: 51, end: 62 },
  ],
  'p50-4': [
    { text: "can you", type: 'chunk', start: 50, end: 57 },
    { text: "come out", type: 'phrasalVerb', start: 58, end: 66 },
  ],
  'p50-5': [
    { text: "Of course", type: 'fixedExpression', start: 52, end: 61 },
    { text: "just my luck", type: 'fixedExpression', start: 64, end: 76 },
    { text: "just my luck", type: 'chunk', start: 64, end: 76 },
    { text: "nothing else to do", type: 'fixedExpression', start: 120, end: 138 },
  ],
  'p51-1': [
    { text: "I'm writing to", type: 'chunk', start: 44, end: 58 },
    { text: "follow up on", type: 'phrasalVerb', start: 59, end: 71 },
  ],
  'p51-2': [
    { text: "Please find the", type: 'fixedExpression', start: 41, end: 56 },
    { text: "Please find", type: 'chunk', start: 41, end: 52 },
  ],
  'p51-3': [
    { text: "Sorry for the late reply", type: 'fixedExpression', start: 43, end: 67 },
    { text: "Sorry for the late reply", type: 'chunk', start: 43, end: 67 },
  ],
  'p51-4': [
    { text: "Just a quick note", type: 'fixedExpression', start: 47, end: 64 },
    { text: "Just a quick note", type: 'chunk', start: 47, end: 64 },
  ],
  'p51-5': [
    { text: "I'll keep you posted", type: 'fixedExpression', start: 39, end: 59 },
    { text: "I'll keep you posted", type: 'chunk', start: 39, end: 59 },
  ],
  'p52-1': [
    { text: "at the table", type: 'prepPhrase', start: 100, end: 112 },
    { text: "at once", type: 'prepPhrase', start: 120, end: 127 },
  ],
  'p52-2': [
    { text: "peeling potatoes", type: 'phrasalVerb', start: 103, end: 119 },
  ],
  'p52-3': [
    { text: "stayed quiet", type: 'collocation', start: 96, end: 108 },
  ],
  'p52-4': [
    { text: "on the wall", type: 'prepPhrase', start: 11, end: 22 },
    { text: "grew up", type: 'phrasalVerb', start: 48, end: 55 },
    { text: "wanted to", type: 'collocation', start: 95, end: 104 },
  ],
  'p52-5': [
    { text: "the same", type: 'chunk', start: 18, end: 26 },
  ],
  'p53-1': [
    { text: "asked for", type: 'phrasalVerb', start: 119, end: 128 },
  ],
  'p53-2': [
    { text: "said it out loud", type: 'chunk', start: 10, end: 26 },
    { text: "out loud", type: 'collocation', start: 18, end: 26 },
    { text: "out loud", type: 'prepPhrase', start: 18, end: 26 },
  ],
  'p53-3': [
    { text: "tried to", type: 'collocation', start: 2, end: 10 },
  ],
  'p53-4': [
    { text: "felt like", type: 'phrasalVerb', start: 102, end: 111 },
  ],
  'p53-5': [
    { text: "at all", type: 'prepPhrase', start: 31, end: 37 },
  ],
  'p54-1': [
    { text: "Long time", type: 'collocation', start: 47, end: 56 },
  ],
  'p54-2': [
    { text: "a whole year", type: 'collocation', start: 97, end: 109 },
  ],
  'p54-3': [
    { text: "Catching up", type: 'phrasalVerb', start: 0, end: 11 },
  ],
  'p54-4': [
    { text: "It's been ages", type: 'fixedExpression', start: 45, end: 59 },
    { text: "It's been ages", type: 'chunk', start: 45, end: 59 },
  ],
  'p54-5': [
    { text: "pick up", type: 'phrasalVerb', start: 111, end: 118 },
  ],
  'p55-1': [
    { text: "heard about", type: 'phrasalVerb', start: 55, end: 66 },
  ],
  'p55-2': [
    { text: "over each other", type: 'prepPhrase', start: 21, end: 36 },
    { text: "In my opinion", type: 'fixedExpression', start: 48, end: 61 },
    { text: "In my opinion", type: 'chunk', start: 48, end: 61 },
    { text: "blown out of proportion", type: 'phrasalVerb', start: 74, end: 97 },
    { text: "blown out of proportion", type: 'fixedExpression', start: 74, end: 97 },
    { text: "out of proportion", type: 'prepPhrase', start: 80, end: 97 },
  ],
  'p55-3': [
    { text: "I'd been", type: 'chunk', start: 17, end: 25 },
    { text: "good to", type: 'collocation', start: 97, end: 104 },
    { text: "on the same page", type: 'fixedExpression', start: 108, end: 124 },
    { text: "on the same page", type: 'prepPhrase', start: 108, end: 124 },
    { text: "the same", type: 'chunk', start: 111, end: 119 },
  ],
  'p55-4': [
    { text: "want to", type: 'collocation', start: 9, end: 16 },
  ],
  'p55-5': [
    { text: "real confidence", type: 'collocation', start: 26, end: 41 },
    { text: "I hear you", type: 'fixedExpression', start: 44, end: 54 },
    { text: "I hear you", type: 'chunk', start: 44, end: 54 },
    { text: "I see it differently", type: 'fixedExpression', start: 60, end: 80 },
    { text: "I see it differently", type: 'chunk', start: 60, end: 80 },
  ],
  'p56-1': [
    { text: "with no luck", type: 'prepPhrase', start: 33, end: 45 },
    { text: "I'm lost", type: 'fixedExpression', start: 67, end: 75 },
    { text: "I'm lost", type: 'chunk', start: 67, end: 75 },
  ],
  'p56-2': [
    { text: "Could you", type: 'chunk', start: 40, end: 49 },
  ],
  'p56-3': [
    { text: "is everything okay", type: 'fixedExpression', start: 55, end: 73 },
  ],
  'p56-4': [
    { text: "at once", type: 'prepPhrase', start: 115, end: 122 },
  ],
  'p56-5': [
    { text: "on the way", type: 'prepPhrase', start: 9, end: 19 },
    { text: "tried to", type: 'collocation', start: 114, end: 122 },
  ],
  'p57-1': [
    { text: "What goes into", type: 'chunk', start: 40, end: 54 },
  ],
  'p57-2': [
    { text: "Could you", type: 'chunk', start: 43, end: 52 },
  ],
  'p57-3': [
    { text: "it needs a bit more", type: 'chunk', start: 48, end: 67 },
  ],
  'p57-4': [
    { text: "stepped back", type: 'phrasalVerb', start: 23, end: 35 },
  ],
  'p57-5': [
    { text: "dig in", type: 'phrasalVerb', start: 62, end: 68 },
    { text: "at once", type: 'prepPhrase', start: 108, end: 115 },
  ],
  'p58-1': [
    { text: "I'm saving up", type: 'chunk', start: 51, end: 64 },
    { text: "saving up for", type: 'phrasalVerb', start: 55, end: 68 },
  ],
  'p58-2': [
    { text: "right now", type: 'prepPhrase', start: 62, end: 71 },
  ],
  'p58-3': [
    { text: "dinner's on me", type: 'fixedExpression', start: 66, end: 80 },
    { text: "on me tonight", type: 'prepPhrase', start: 75, end: 88 },
  ],
  'p58-4': [
    { text: "in the middle of", type: 'prepPhrase', start: 17, end: 33 },
  ],
  'p58-5': [
    { text: "instead", type: 'chunk', start: 123, end: 130 },
  ],
  'p59-1': [
    { text: "log in", type: 'phrasalVerb', start: 54, end: 60 },
    { text: "log in to", type: 'collocation', start: 54, end: 63 },
  ],
  'p59-2': [
    { text: "There's an update", type: 'chunk', start: 41, end: 58 },
  ],
  'p59-3': [
    { text: "on the way", type: 'prepPhrase', start: 74, end: 84 },
    { text: "let me", type: 'chunk', start: 102, end: 108 },
  ],
  'p59-4': [
    { text: "It's not letting", type: 'fixedExpression', start: 43, end: 59 },
    { text: "It's not letting me", type: 'chunk', start: 43, end: 62 },
    { text: "log in", type: 'phrasalVerb', start: 63, end: 69 },
  ],
  'p59-5': [
    { text: "acting up", type: 'phrasalVerb', start: 68, end: 77 },
    { text: "acting up again", type: 'fixedExpression', start: 68, end: 83 },
    { text: "classic restart", type: 'fixedExpression', start: 108, end: 123 },
  ],
  'p60-1': [
    { text: "Sounds good", type: 'chunk', start: 48, end: 59 },
    { text: "good to", type: 'collocation', start: 55, end: 62 },
    { text: "moved on", type: 'phrasalVerb', start: 107, end: 115 },
  ],
  'p60-2': [
    { text: "at all", type: 'prepPhrase', start: 73, end: 79 },
  ],
  'p60-3': [
    { text: "go out", type: 'phrasalVerb', start: 33, end: 39 },
    { text: "Fair enough", type: 'fixedExpression', start: 50, end: 61 },
  ],
  'p60-4': [
    { text: "my bad", type: 'fixedExpression', start: 53, end: 59 },
    { text: "my bad", type: 'chunk', start: 53, end: 59 },
  ],
  'p60-5': [
    { text: "suit yourself", type: 'fixedExpression', start: 53, end: 66 },
    { text: "suit yourself", type: 'chunk', start: 53, end: 66 },
  ],
  'p61-1': [
    { text: "I'm swamped with", type: 'fixedExpression', start: 35, end: 51 },
    { text: "I'm swamped with", type: 'chunk', start: 35, end: 51 },
    { text: "swamped with", type: 'phrasalVerb', start: 39, end: 51 },
  ],
  'p61-2': [
    { text: "in the middle of", type: 'prepPhrase', start: 29, end: 45 },
    { text: "Can you", type: 'chunk', start: 57, end: 64 },
    { text: "no problem", type: 'prepPhrase', start: 119, end: 129 },
    { text: "no problem", type: 'chunk', start: 119, end: 129 },
  ],
  'p61-3': [
    { text: "wanted to", type: 'collocation', start: 4, end: 13 },
    { text: "right away", type: 'prepPhrase', start: 122, end: 132 },
  ],
  'p61-4': [
    { text: "touch base", type: 'phrasalVerb', start: 48, end: 58 },
    { text: "touch base with", type: 'fixedExpression', start: 48, end: 63 },
  ],
  'p61-5': [
    { text: "one of those days", type: 'fixedExpression', start: 59, end: 76 },
    { text: "one of those days", type: 'prepPhrase', start: 59, end: 76 },
    { text: "one of those days", type: 'chunk', start: 59, end: 76 },
  ],
  'p62-1': [
    { text: "Do you have", type: 'chunk', start: 39, end: 50 },
  ],
  'p62-2': [
    { text: "I wanted to", type: 'chunk', start: 42, end: 53 },
    { text: "wanted to", type: 'collocation', start: 44, end: 53 },
  ],
  'p62-3': [
    { text: "not just", type: 'chunk', start: 24, end: 32 },
  ],
  'p62-4': [
    { text: "Keep up the great work", type: 'fixedExpression', start: 40, end: 62 },
    { text: "Keep up the great work", type: 'chunk', start: 40, end: 62 },
    { text: "a real boost", type: 'fixedExpression', start: 85, end: 97 },
    { text: "real boost", type: 'collocation', start: 87, end: 97 },
  ],
  'p62-5': [
    { text: "needed to", type: 'collocation', start: 3, end: 12 },
    { text: "set up", type: 'phrasalVerb', start: 46, end: 52 },
  ],
  'p63-1': [
    { text: "warm smile", type: 'collocation', start: 35, end: 45 },
    { text: "took a breath", type: 'collocation', start: 90, end: 103 },
  ],
  'p63-2': [
    { text: "I have experience in", type: 'fixedExpression', start: 43, end: 63 },
    { text: "I have experience", type: 'chunk', start: 43, end: 60 },
    { text: "have experience", type: 'collocation', start: 45, end: 60 },
    { text: "I backed it up", type: 'chunk', start: 92, end: 106 },
  ],
  'p63-3': [
    { text: "staying calm under pressure", type: 'fixedExpression', start: 66, end: 93 },
    { text: "calm under pressure", type: 'collocation', start: 74, end: 93 },
    { text: "calm under pressure", type: 'prepPhrase', start: 74, end: 93 },
  ],
  'p63-4': [
    { text: "I'm confident that I can", type: 'fixedExpression', start: 46, end: 70 },
    { text: "I'm confident that", type: 'chunk', start: 46, end: 64 },
    { text: "hit the targets", type: 'fixedExpression', start: 71, end: 86 },
    { text: "it showed", type: 'chunk', start: 113, end: 122 },
  ],
  'p63-5': [
    { text: "wrapped up", type: 'phrasalVerb', start: 14, end: 24 },
    { text: "can I", type: 'chunk', start: 47, end: 52 },
    { text: "within a week", type: 'prepPhrase', start: 102, end: 115 },
  ],
  'p64-1': [
    { text: "asked for", type: 'phrasalVerb', start: 11, end: 20 },
    { text: "May I", type: 'chunk', start: 48, end: 53 },
  ],
  'p64-2': [
    { text: "Could you", type: 'chunk', start: 45, end: 54 },
  ],
  'p64-3': [
    { text: "I'll put you through", type: 'prepPhrase', start: 55, end: 75 },
    { text: "put you through", type: 'phrasalVerb', start: 60, end: 75 },
  ],
  'p64-4': [
    { text: "can I", type: 'chunk', start: 62, end: 67 },
  ],
  'p64-5': [
    { text: "back-to-back", type: 'prepPhrase', start: 10, end: 22 },
    { text: "Can I", type: 'chunk', start: 46, end: 51 },
    { text: "said that worked", type: 'collocation', start: 114, end: 130 },
  ],
  'p65-1': [
    { text: "can I", type: 'chunk', start: 60, end: 65 },
  ],
  'p65-2': [
    { text: "right away", type: 'prepPhrase', start: 64, end: 74 },
  ],
  'p65-3': [
    { text: "I apologize for the wait", type: 'prepPhrase', start: 46, end: 70 },
    { text: "I apologize for", type: 'chunk', start: 46, end: 61 },
    { text: "apologize for", type: 'phrasalVerb', start: 48, end: 61 },
    { text: "apologize for the wait", type: 'fixedExpression', start: 48, end: 70 },
    { text: "apologize for the wait", type: 'collocation', start: 48, end: 70 },
  ],
  'p65-4': [
    { text: "Is there anything else", type: 'fixedExpression', start: 37, end: 59 },
    { text: "Is there anything else I can do", type: 'chunk', start: 37, end: 68 },
  ],
  'p65-5': [
    { text: "Thanks for your patience", type: 'fixedExpression', start: 46, end: 70 },
    { text: "Thanks for your patience", type: 'chunk', start: 46, end: 70 },
  ],
  'p66-1': [
    { text: "As you can see", type: 'chunk', start: 44, end: 58 },
    { text: "up this quarter", type: 'chunk', start: 70, end: 85 },
  ],
  'p66-2': [
    { text: "the same", type: 'chunk', start: 21, end: 29 },
    { text: "take a look", type: 'collocation', start: 43, end: 54 },
  ],
  'p66-3': [
    { text: "point to", type: 'phrasalVerb', start: 18, end: 26 },
    { text: "get lost", type: 'collocation', start: 27, end: 35 },
  ],
  'p66-4': [
    { text: "carried on", type: 'phrasalVerb', start: 112, end: 122 },
  ],
  'p66-5': [
    { text: "on time", type: 'prepPhrase', start: 35, end: 42 },
  ],
  'p67-1': [
    { text: "thought about", type: 'phrasalVerb', start: 96, end: 109 },
  ],
  'p67-2': [
    { text: "Could you", type: 'chunk', start: 32, end: 41 },
  ],
  'p67-3': [
    { text: "after that", type: 'chunk', start: 106, end: 116 },
  ],
  'p67-4': [
    { text: "Let's call it", type: 'chunk', start: 46, end: 59 },
    { text: "call it", type: 'phrasalVerb', start: 52, end: 59 },
  ],
  'p67-5': [
    { text: "we have a deal", type: 'fixedExpression', start: 51, end: 65 },
    { text: "we have a deal", type: 'chunk', start: 51, end: 65 },
  ],
  'p68-1': [
    { text: "who's taking the lead", type: 'chunk', start: 45, end: 66 },
    { text: "taking the lead", type: 'phrasalVerb', start: 51, end: 66 },
  ],
  'p68-2': [
    { text: "off your plate", type: 'fixedExpression', start: 63, end: 77 },
    { text: "off your plate", type: 'chunk', start: 63, end: 77 },
  ],
  'p68-4': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
    { text: "on the same page", type: 'fixedExpression', start: 49, end: 65 },
    { text: "on the same page", type: 'prepPhrase', start: 49, end: 65 },
    { text: "the same", type: 'chunk', start: 52, end: 60 },
    { text: "moved on", type: 'phrasalVerb', start: 111, end: 119 },
  ],
  'p68-5': [
    { text: "That sounds great", type: 'fixedExpression', start: 43, end: 60 },
    { text: "count me in", type: 'fixedExpression', start: 63, end: 74 },
    { text: "count me in", type: 'chunk', start: 63, end: 74 },
  ],
  'p69-1': [
    { text: "Can we", type: 'chunk', start: 50, end: 56 },
    { text: "talk about", type: 'phrasalVerb', start: 57, end: 67 },
  ],
  'p69-2': [
    { text: "I'm sorry", type: 'chunk', start: 41, end: 50 },
  ],
  'p69-3': [
    { text: "Let's not turn this into", type: 'fixedExpression', start: 41, end: 65 },
    { text: "the heat drained", type: 'chunk', start: 100, end: 116 },
  ],
  'p69-4': [
    { text: "either", type: 'chunk', start: 25, end: 31 },
  ],
  'p69-5': [
    { text: "let's put this behind", type: 'fixedExpression', start: 51, end: 72 },
    { text: "let's put this behind us", type: 'chunk', start: 51, end: 75 },
    { text: "put this behind", type: 'phrasalVerb', start: 57, end: 72 },
  ],
  'p70-1': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
  ],
  'p70-2': [
    { text: "for once", type: 'prepPhrase', start: 26, end: 34 },
  ],
  'p70-3': [
    { text: "Let's actually", type: 'chunk', start: 40, end: 54 },
    { text: "make plans for", type: 'fixedExpression', start: 55, end: 69 },
  ],
  'p70-4': [
    { text: "I'm free anytime", type: 'fixedExpression', start: 41, end: 57 },
    { text: "I'm free", type: 'chunk', start: 41, end: 49 },
    { text: "after five", type: 'prepPhrase', start: 58, end: 68 },
  ],
  'p70-5': [
    { text: "for now", type: 'prepPhrase', start: 62, end: 69 },
    { text: "by Thursday", type: 'prepPhrase', start: 102, end: 113 },
  ],
  'p71-1': [
    { text: "at the door", type: 'prepPhrase', start: 89, end: 100 },
  ],
  'p71-2': [
    { text: "want to", type: 'collocation', start: 9, end: 16 },
    { text: "show up", type: 'phrasalVerb', start: 17, end: 24 },
    { text: "Can I", type: 'chunk', start: 40, end: 45 },
  ],
  'p71-3': [
    { text: "dug in", type: 'phrasalVerb', start: 105, end: 111 },
    { text: "at once", type: 'prepPhrase', start: 124, end: 131 },
  ],
  'p71-4': [
    { text: "by the door", type: 'prepPhrase', start: 11, end: 22 },
  ],
  'p71-5': [
    { text: "This was lovely", type: 'fixedExpression', start: 44, end: 59 },
    { text: "I should get going", type: 'chunk', start: 65, end: 83 },
    { text: "get going", type: 'phrasalVerb', start: 74, end: 83 },
    { text: "do it again soon", type: 'fixedExpression', start: 109, end: 125 },
  ],
  'p72-1': [
    { text: "at the same time", type: 'prepPhrase', start: 24, end: 40 },
    { text: "the same", type: 'chunk', start: 27, end: 35 },
    { text: "right now", type: 'prepPhrase', start: 75, end: 84 },
  ],
  'p72-2': [
    { text: "take it easy", type: 'collocation', start: 46, end: 58 },
    { text: "for once", type: 'prepPhrase', start: 112, end: 120 },
  ],
  'p72-3': [
    { text: "it'll be okay", type: 'chunk', start: 57, end: 70 },
  ],
  'p72-4': [
    { text: "Don't be so hard on yourself", type: 'fixedExpression', start: 39, end: 67 },
    { text: "Don't be so hard on yourself", type: 'chunk', start: 39, end: 67 },
  ],
  'p72-5': [
    { text: "I'm here for you", type: 'fixedExpression', start: 57, end: 73 },
    { text: "I'm here for you", type: 'chunk', start: 57, end: 73 },
  ],
  'p73-1': [
    { text: "You did a great job", type: 'fixedExpression', start: 40, end: 59 },
    { text: "You did a great job", type: 'chunk', start: 40, end: 59 },
  ],
  'p73-2': [
    { text: "right away", type: 'prepPhrase', start: 72, end: 82 },
  ],
  'p73-3': [
    { text: "good at", type: 'chunk', start: 67, end: 74 },
  ],
  'p73-4': [
    { text: "tried on", type: 'phrasalVerb', start: 4, end: 12 },
    { text: "decided to", type: 'collocation', start: 93, end: 103 },
  ],
  'p73-5': [
    { text: "Way to go", type: 'fixedExpression', start: 39, end: 48 },
    { text: "Way to go", type: 'chunk', start: 39, end: 48 },
    { text: "you crushed it", type: 'fixedExpression', start: 51, end: 65 },
    { text: "you crushed it", type: 'chunk', start: 51, end: 65 },
  ],
  'p74-1': [
    { text: "I owe you an apology", type: 'fixedExpression', start: 41, end: 61 },
    { text: "I owe you an apology", type: 'chunk', start: 41, end: 61 },
  ],
  'p74-2': [
    { text: "I could see", type: 'chunk', start: 0, end: 11 },
    { text: "made sure", type: 'phrasalVerb', start: 115, end: 124 },
    { text: "made sure", type: 'collocation', start: 115, end: 124 },
  ],
  'p74-3': [
    { text: "I didn't realize it was", type: 'chunk', start: 43, end: 66 },
    { text: "slipped away from me", type: 'chunk', start: 105, end: 125 },
  ],
  'p74-4': [
    { text: "I'm sorry", type: 'chunk', start: 48, end: 57 },
    { text: "make up for", type: 'phrasalVerb', start: 129, end: 140 },
  ],
  'p74-5': [
    { text: "I'll make", type: 'chunk', start: 36, end: 45 },
  ],
  'p75-1': [
    { text: "Would you", type: 'chunk', start: 34, end: 43 },
  ],
  'p75-2': [
    { text: "she'd be glad to", type: 'chunk', start: 104, end: 120 },
    { text: "glad to", type: 'fixedExpression', start: 113, end: 120 },
  ],
  'p75-4': [
    { text: "whether", type: 'chunk', start: 18, end: 25 },
    { text: "ask for", type: 'phrasalVerb', start: 29, end: 36 },
    { text: "happy to", type: 'collocation', start: 51, end: 59 },
    { text: "lit up", type: 'phrasalVerb', start: 95, end: 101 },
  ],
  'p75-5': [
    { text: "Why don't I", type: 'chunk', start: 46, end: 57 },
    { text: "take the calls", type: 'chunk', start: 58, end: 72 },
    { text: "Splitting it", type: 'chunk', start: 103, end: 115 },
    { text: "made everything easier", type: 'chunk', start: 116, end: 138 },
  ],
  'p76-1': [
    { text: "have a point there", type: 'fixedExpression', start: 56, end: 74 },
    { text: "the whole thing", type: 'chunk', start: 110, end: 125 },
  ],
  'p76-2': [
    { text: "I'm with", type: 'chunk', start: 46, end: 54 },
  ],
  'p76-3': [
    { text: "seemed to", type: 'collocation', start: 9, end: 18 },
  ],
  'p76-4': [
    { text: "summed up", type: 'phrasalVerb', start: 4, end: 13 },
  ],
  'p76-5': [
    { text: "Not necessarily", type: 'fixedExpression', start: 42, end: 57 },
    { text: "Not necessarily", type: 'chunk', start: 42, end: 57 },
    { text: "let's actually compare", type: 'fixedExpression', start: 60, end: 82 },
    { text: "let's actually", type: 'chunk', start: 60, end: 74 },
    { text: "dug in", type: 'phrasalVerb', start: 96, end: 102 },
  ],
  'p77-1': [
    { text: "have a feeling", type: 'collocation', start: 43, end: 57 },
  ],
  'p77-2': [
    { text: "It must be", type: 'chunk', start: 43, end: 53 },
    { text: "lost track of time", type: 'fixedExpression', start: 107, end: 125 },
    { text: "lost track of time", type: 'chunk', start: 107, end: 125 },
  ],
  'p77-4': [
    { text: "just to", type: 'chunk', start: 20, end: 27 },
    { text: "I'm pretty sure", type: 'chunk', start: 43, end: 58 },
    { text: "just in case", type: 'prepPhrase', start: 110, end: 122 },
    { text: "just in", type: 'chunk', start: 110, end: 117 },
  ],
  'p78-2': [
    { text: "the same", type: 'chunk', start: 109, end: 117 },
  ],
  'p78-4': [
    { text: "would you", type: 'chunk', start: 54, end: 63 },
  ],
  'p79-1': [
    { text: "the same", type: 'chunk', start: 21, end: 29 },
  ],
  'p79-2': [
    { text: "at least", type: 'prepPhrase', start: 109, end: 117 },
    { text: "at least", type: 'chunk', start: 109, end: 117 },
  ],
  'p79-4': [
    { text: "used to", type: 'phrasalVerb', start: 52, end: 59 },
    { text: "used to", type: 'collocation', start: 52, end: 59 },
    { text: "used to", type: 'chunk', start: 52, end: 59 },
    { text: "waking up", type: 'phrasalVerb', start: 60, end: 69 },
  ],
  'p79-5': [
    { text: "the same", type: 'chunk', start: 132, end: 140 },
  ],
  'p80-2': [
    { text: "Come to think of it", type: 'fixedExpression', start: 51, end: 70 },
  ],
  'p80-3': [
    { text: "wrapping up", type: 'phrasalVerb', start: 8, end: 19 },
    { text: "By the way", type: 'fixedExpression', start: 50, end: 60 },
    { text: "By the way", type: 'chunk', start: 50, end: 60 },
  ],
  'p80-4': [
    { text: "I'd been", type: 'chunk', start: 30, end: 38 },
    { text: "hoping for", type: 'phrasalVerb', start: 39, end: 49 },
    { text: "right away", type: 'prepPhrase', start: 109, end: 119 },
  ],
  'p81-2': [
    { text: "at all", type: 'prepPhrase', start: 28, end: 34 },
    { text: "pulled up", type: 'phrasalVerb', start: 81, end: 90 },
  ],
  'p81-3': [
    { text: "stay in", type: 'phrasalVerb', start: 63, end: 70 },
  ],
  'p81-4': [
    { text: "kept going", type: 'collocation', start: 3, end: 13 },
    { text: "going back", type: 'phrasalVerb', start: 8, end: 18 },
    { text: "back and forth", type: 'prepPhrase', start: 14, end: 28 },
  ],
  'p82-2': [
    { text: "right away", type: 'prepPhrase', start: 112, end: 122 },
  ],
  'p82-3': [
    { text: "to be clear", type: 'prepPhrase', start: 31, end: 42 },
  ],
  'p82-4': [
    { text: "miss it", type: 'collocation', start: 74, end: 81 },
  ],
  'p82-5': [
    { text: "started to", type: 'collocation', start: 20, end: 30 },
  ],
  'p83-3': [
    { text: "just for", type: 'chunk', start: 123, end: 131 },
  ],
  'p83-4': [
    { text: "by accident", type: 'prepPhrase', start: 124, end: 135 },
  ],
  'p84-1': [
    { text: "I'll be", type: 'chunk', start: 46, end: 53 },
  ],
  'p84-2': [
    { text: "Can I", type: 'chunk', start: 46, end: 51 },
  ],
  'p84-3': [
    { text: "wanted to", type: 'collocation', start: 11, end: 20 },
    { text: "Can I", type: 'chunk', start: 41, end: 46 },
  ],
  'p84-4': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
  ],
  'p84-5': [
    { text: "walked me through", type: 'collocation', start: 94, end: 111 },
  ],
  'p85-1': [
    { text: "How much is", type: 'chunk', start: 48, end: 59 },
  ],
  'p85-3': [
    { text: "think about", type: 'phrasalVerb', start: 56, end: 67 },
  ],
  'p85-5': [
    { text: "That's all", type: 'chunk', start: 36, end: 46 },
  ],
  'p86-1': [
    { text: "stay calm", type: 'collocation', start: 51, end: 60 },
  ],
  'p86-3': [
    { text: "Get back", type: 'phrasalVerb', start: 41, end: 49 },
    { text: "just in time", type: 'prepPhrase', start: 93, end: 105 },
    { text: "just in", type: 'chunk', start: 93, end: 100 },
  ],
  'p86-4': [
    { text: "at once", type: 'prepPhrase', start: 119, end: 126 },
  ],
  'p86-5': [
    { text: "right away", type: 'prepPhrase', start: 114, end: 124 },
  ],
  'p87-2': [
    { text: "Looks like", type: 'chunk', start: 51, end: 61 },
  ],
  'p87-3': [
    { text: "It's freezing", type: 'chunk', start: 39, end: 52 },
  ],
  'p87-4': [
    { text: "supposed to", type: 'collocation', start: 50, end: 61 },
    { text: "supposed to", type: 'chunk', start: 50, end: 61 },
    { text: "clear up", type: 'phrasalVerb', start: 62, end: 70 },
  ],
  'p87-5': [
    { text: "There's nothing", type: 'fixedExpression', start: 41, end: 56 },
  ],
  'p88-2': [
    { text: "feel better", type: 'collocation', start: 58, end: 69 },
  ],
  'p88-3': [
    { text: "listen to", type: 'phrasalVerb', start: 53, end: 62 },
    { text: "instead", type: 'chunk', start: 115, end: 122 },
  ],
  'p88-4': [
    { text: "Let's go", type: 'chunk', start: 53, end: 61 },
  ],
  'p89-1': [
    { text: "Do you have", type: 'chunk', start: 44, end: 55 },
    { text: "by the window", type: 'prepPhrase', start: 102, end: 115 },
  ],
  'p89-2': [
    { text: "sat down", type: 'phrasalVerb', start: 3, end: 11 },
    { text: "Could I", type: 'chunk', start: 34, end: 41 },
  ],
  'p89-3': [
    { text: "it was the best", type: 'chunk', start: 96, end: 111 },
  ],
  'p89-4': [
    { text: "That sounds great", type: 'fixedExpression', start: 50, end: 67 },
    { text: "I'll have", type: 'chunk', start: 70, end: 79 },
    { text: "the same", type: 'chunk', start: 80, end: 88 },
  ],
  'p90-3': [
    { text: "looked for", type: 'phrasalVerb', start: 23, end: 33 },
    { text: "I'll be", type: 'chunk', start: 43, end: 50 },
    { text: "at the table", type: 'prepPhrase', start: 51, end: 63 },
    { text: "by the window", type: 'prepPhrase', start: 64, end: 77 },
  ],
  'p90-4': [
    { text: "in the morning", type: 'prepPhrase', start: 64, end: 78 },
  ],
  'p91-3': [
    { text: "wait for", type: 'phrasalVerb', start: 46, end: 54 },
  ],
  'p91-4': [
    { text: "asked for", type: 'phrasalVerb', start: 8, end: 17 },
  ],
  'p91-5': [
    { text: "move on", type: 'phrasalVerb', start: 73, end: 80 },
    { text: "circled back", type: 'phrasalVerb', start: 99, end: 111 },
  ],
  'p93-2': [
    { text: "Can you", type: 'chunk', start: 43, end: 50 },
  ],
  'p93-4': [
    { text: "lit up", type: 'phrasalVerb', start: 9, end: 15 },
    { text: "right away", type: 'prepPhrase', start: 114, end: 124 },
  ],
  'p94-1': [
    { text: "opened up", type: 'phrasalVerb', start: 90, end: 99 },
  ],
  'p94-3': [
    { text: "by the window", type: 'prepPhrase', start: 67, end: 80 },
  ],
  'p94-4': [
    { text: "feel like", type: 'phrasalVerb', start: 106, end: 115 },
  ],
  'p95-1': [
    { text: "by the door", type: 'prepPhrase', start: 21, end: 32 },
  ],
  'p95-5': [
    { text: "can I", type: 'chunk', start: 55, end: 60 },
    { text: "of course", type: 'fixedExpression', start: 106, end: 115 },
  ],
  'p96-2': [
    { text: "Can we", type: 'chunk', start: 39, end: 45 },
  ],
  'p96-4': [
    { text: "have to", type: 'collocation', start: 51, end: 58 },
    { text: "instead of", type: 'prepPhrase', start: 65, end: 75 },
    { text: "instead", type: 'chunk', start: 65, end: 72 },
    { text: "at least", type: 'prepPhrase', start: 109, end: 117 },
    { text: "at least", type: 'chunk', start: 109, end: 117 },
  ],
  'p97-2': [
    { text: "on the way", type: 'prepPhrase', start: 111, end: 121 },
  ],
  'p97-5': [
    { text: "just in time", type: 'prepPhrase', start: 48, end: 60 },
    { text: "just in", type: 'chunk', start: 48, end: 55 },
  ],
  'p98-2': [
    { text: "I'd rather", type: 'chunk', start: 91, end: 101 },
  ],
  'p98-3': [
    { text: "decided to", type: 'collocation', start: 89, end: 99 },
  ],
  'p98-4': [
    { text: "the only", type: 'chunk', start: 101, end: 109 },
  ],
  'p99-1': [
    { text: "by the door", type: 'prepPhrase', start: 12, end: 23 },
  ],
  'p99-3': [
    { text: "Take care of", type: 'phrasalVerb', start: 50, end: 62 },
    { text: "Take care", type: 'fixedExpression', start: 50, end: 59 },
    { text: "Take care", type: 'collocation', start: 50, end: 59 },
  ],
  'p99-5': [
    { text: "keep in touch", type: 'collocation', start: 67, end: 80 },
  ],
  'p100-1': [
    { text: "sat down", type: 'phrasalVerb', start: 33, end: 41 },
    { text: "let me", type: 'chunk', start: 102, end: 108 },
  ],
  'p100-2': [
    { text: "apologized for", type: 'phrasalVerb', start: 4, end: 18 },
    { text: "on her own", type: 'prepPhrase', start: 115, end: 125 },
  ],
  'p100-3': [
    { text: "it's a long story", type: 'fixedExpression', start: 43, end: 60 },
  ],
}
