import type { SaveCandidate } from '@/data/pattern-examples-full'

/**
 * Story paragraph saveCandidates — auto-generated by scripts/generate-story-chunks.mjs
 * 255 / 500 paragraphs have chunk data.
 */
export const storyChunks: Record<string, SaveCandidate[]> = {
  'p1-1': [
    { text: "I want to", type: 'chunk', start: 50, end: 59 },
    { text: "want to", type: 'collocation', start: 52, end: 59 },
  ],
  'p1-2': [
    { text: "I'm thinking about", type: 'chunk', start: 0, end: 18 },
    { text: "thinking about", type: 'phrasalVerb', start: 4, end: 18 },
    { text: "every night", type: 'collocation', start: 43, end: 54 },
    { text: "doesn't have to", type: 'chunk', start: 90, end: 105 },
    { text: "have to", type: 'collocation', start: 98, end: 105 },
  ],
  'p1-3': [
    { text: "stay positive", type: 'collocation', start: 68, end: 81 },
  ],
  'p1-4': [
    { text: "That's because", type: 'chunk', start: 0, end: 14 },
    { text: "I want to", type: 'chunk', start: 83, end: 92 },
    { text: "want to", type: 'collocation', start: 85, end: 92 },
    { text: "hold on to", type: 'phrasalVerb', start: 93, end: 103 },
  ],
  'p1-5': [
    { text: "It turns out", type: 'chunk', start: 34, end: 46 },
    { text: "new start", type: 'collocation', start: 76, end: 85 },
  ],
  'p2-1': [
    { text: "old friend", type: 'collocation', start: 15, end: 25 },
    { text: "a long time", type: 'prepPhrase', start: 127, end: 138 },
    { text: "long time", type: 'collocation', start: 129, end: 138 },
  ],
  'p2-2': [
    { text: "I used to", type: 'chunk', start: 0, end: 9 },
    { text: "used to", type: 'phrasalVerb', start: 2, end: 9 },
    { text: "used to", type: 'collocation', start: 2, end: 9 },
    { text: "felt tired", type: 'collocation', start: 34, end: 44 },
    { text: "a lot of", type: 'prepPhrase', start: 55, end: 63 },
    { text: "I don't want to", type: 'chunk', start: 82, end: 97 },
    { text: "want to", type: 'collocation', start: 90, end: 97 },
  ],
  'p2-3': [
    { text: "sat down", type: 'phrasalVerb', start: 9, end: 17 },
    { text: "I'm sorry", type: 'chunk', start: 28, end: 37 },
  ],
  'p2-4': [
    { text: "It seems like", type: 'chunk', start: 0, end: 13 },
  ],
  'p2-5': [
    { text: "I'm looking forward to", type: 'chunk', start: 41, end: 63 },
    { text: "looking forward to", type: 'phrasalVerb', start: 45, end: 63 },
    { text: "from now on", type: 'prepPhrase', start: 87, end: 98 },
  ],
  'p3-1': [
    { text: "in the morning", type: 'prepPhrase', start: 11, end: 25 },
    { text: "have to", type: 'collocation', start: 54, end: 61 },
  ],
  'p3-2': [
    { text: "in the morning", type: 'prepPhrase', start: 21, end: 35 },
    { text: "instead", type: 'chunk', start: 55, end: 62 },
  ],
  'p3-4': [
    { text: "small kindness", type: 'collocation', start: 49, end: 63 },
  ],
  'p3-5': [
    { text: "wanted to", type: 'collocation', start: 7, end: 16 },
  ],
  'p4-2': [
    { text: "think about", type: 'phrasalVerb', start: 58, end: 69 },
  ],
  'p4-3': [
    { text: "again and again", type: 'prepPhrase', start: 25, end: 40 },
    { text: "want to", type: 'collocation', start: 85, end: 92 },
  ],
  'p4-4': [
    { text: "turn off", type: 'phrasalVerb', start: 32, end: 40 },
    { text: "deep breath", type: 'collocation', start: 62, end: 73 },
  ],
  'p4-5': [
    { text: "supposed to", type: 'collocation', start: 4, end: 15 },
    { text: "supposed to", type: 'chunk', start: 4, end: 15 },
    { text: "just in case", type: 'prepPhrase', start: 59, end: 71 },
    { text: "just in", type: 'chunk', start: 59, end: 66 },
  ],
  'p5-1': [
    { text: "by the window", type: 'prepPhrase', start: 14, end: 27 },
    { text: "for a long time", type: 'prepPhrase', start: 28, end: 43 },
    { text: "long time", type: 'collocation', start: 34, end: 43 },
    { text: "I'm going to", type: 'chunk', start: 45, end: 57 },
  ],
  'p5-2': [
    { text: "I'm going to", type: 'chunk', start: 0, end: 12 },
    { text: "waking up", type: 'phrasalVerb', start: 17, end: 26 },
    { text: "feel like", type: 'phrasalVerb', start: 68, end: 77 },
  ],
  'p5-3': [
    { text: "for a while", type: 'prepPhrase', start: 24, end: 35 },
    { text: "asking for", type: 'phrasalVerb', start: 91, end: 101 },
  ],
  'p5-4': [
    { text: "That's when", type: 'chunk', start: 95, end: 106 },
  ],
  'p5-5': [
    { text: "feel like", type: 'phrasalVerb', start: 2, end: 11 },
  ],
  'p6-1': [
    { text: "I'm not sure", type: 'chunk', start: 45, end: 57 },
  ],
  'p6-2': [
    { text: "tend to", type: 'collocation', start: 2, end: 9 },
  ],
  'p6-4': [
    { text: "I'm trying to", type: 'chunk', start: 0, end: 13 },
    { text: "listen to", type: 'phrasalVerb', start: 14, end: 23 },
    { text: "instead of", type: 'prepPhrase', start: 31, end: 41 },
    { text: "instead", type: 'chunk', start: 31, end: 38 },
    { text: "has to", type: 'collocation', start: 109, end: 115 },
  ],
  'p6-5': [
    { text: "Even though", type: 'prepPhrase', start: 0, end: 11 },
  ],
  'p7-1': [
    { text: "As long as", type: 'prepPhrase', start: 40, end: 50 },
  ],
  'p7-2': [
    { text: "No wonder", type: 'prepPhrase', start: 36, end: 45 },
    { text: "No wonder", type: 'chunk', start: 36, end: 45 },
  ],
  'p7-3': [
    { text: "I'd rather", type: 'chunk', start: 40, end: 50 },
    { text: "need to", type: 'collocation', start: 92, end: 99 },
  ],
  'p7-4': [
    { text: "ended up", type: 'phrasalVerb', start: 43, end: 51 },
    { text: "It was the best", type: 'chunk', start: 84, end: 99 },
    { text: "the best part", type: 'prepPhrase', start: 91, end: 104 },
  ],
  'p7-5': [
    { text: "for a long time", type: 'prepPhrase', start: 108, end: 123 },
    { text: "long time", type: 'collocation', start: 114, end: 123 },
  ],
  'p8-1': [
    { text: "by the window", type: 'prepPhrase', start: 72, end: 85 },
  ],
  'p8-2': [
    { text: "I'd like to", type: 'chunk', start: 28, end: 39 },
  ],
  'p8-4': [
    { text: "turning on", type: 'phrasalVerb', start: 53, end: 63 },
    { text: "right away", type: 'prepPhrase', start: 103, end: 113 },
  ],
  'p8-5': [
    { text: "It was getting", type: 'chunk', start: 0, end: 14 },
  ],
  'p9-1': [
    { text: "Make sure", type: 'phrasalVerb', start: 43, end: 52 },
    { text: "Make sure", type: 'collocation', start: 43, end: 52 },
  ],
  'p9-2': [
    { text: "want to", type: 'collocation', start: 12, end: 19 },
    { text: "have time", type: 'collocation', start: 86, end: 95 },
  ],
  'p9-5': [
    { text: "instead", type: 'chunk', start: 34, end: 41 },
  ],
  'p10-1': [
    { text: "think about", type: 'phrasalVerb', start: 44, end: 55 },
  ],
  'p10-3': [
    { text: "I can't wait", type: 'chunk', start: 0, end: 12 },
    { text: "feel like", type: 'phrasalVerb', start: 102, end: 111 },
  ],
  'p10-4': [
    { text: "so much", type: 'prepPhrase', start: 31, end: 38 },
  ],
  'p10-5': [
    { text: "worried about", type: 'phrasalVerb', start: 11, end: 24 },
    { text: "worried about", type: 'chunk', start: 11, end: 24 },
    { text: "at first", type: 'prepPhrase', start: 61, end: 69 },
  ],
  'p11-1': [
    { text: "I'm afraid", type: 'chunk', start: 53, end: 63 },
    { text: "put down", type: 'phrasalVerb', start: 110, end: 118 },
  ],
  'p11-2': [
    { text: "To be honest", type: 'prepPhrase', start: 1, end: 13 },
    { text: "for a while", type: 'prepPhrase', start: 34, end: 45 },
  ],
  'p11-3': [
    { text: "I don't think", type: 'chunk', start: 1, end: 14 },
    { text: "the same", type: 'chunk', start: 23, end: 31 },
    { text: "went on", type: 'phrasalVerb', start: 51, end: 58 },
  ],
  'p11-4': [
    { text: "I'd been", type: 'chunk', start: 63, end: 71 },
    { text: "felt like", type: 'phrasalVerb', start: 113, end: 122 },
  ],
  'p11-5': [
    { text: "in silence", type: 'prepPhrase', start: 7, end: 17 },
    { text: "for a moment", type: 'prepPhrase', start: 18, end: 30 },
    { text: "for a moment", type: 'chunk', start: 18, end: 30 },
  ],
  'p12-1': [
    { text: "I was wondering", type: 'chunk', start: 94, end: 109 },
  ],
  'p12-2': [
    { text: "showed up", type: 'phrasalVerb', start: 3, end: 12 },
  ],
  'p12-3': [
    { text: "on the phone", type: 'prepPhrase', start: 86, end: 98 },
  ],
  'p12-4': [
    { text: "On the way", type: 'prepPhrase', start: 0, end: 10 },
    { text: "had time", type: 'collocation', start: 37, end: 45 },
  ],
  'p12-5': [
    { text: "show up", type: 'phrasalVerb', start: 129, end: 136 },
  ],
  'p13-1': [
    { text: "get back", type: 'phrasalVerb', start: 63, end: 71 },
    { text: "want to", type: 'collocation', start: 124, end: 131 },
  ],
  'p13-2': [
    { text: "sat down", type: 'phrasalVerb', start: 11, end: 19 },
  ],
  'p13-3': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
    { text: "Just to", type: 'chunk', start: 41, end: 48 },
  ],
  'p13-4': [
    { text: "take care of", type: 'phrasalVerb', start: 66, end: 78 },
    { text: "take care", type: 'collocation', start: 66, end: 75 },
  ],
  'p14-2': [
    { text: "can't wait", type: 'chunk', start: 136, end: 146 },
  ],
  'p14-5': [
    { text: "No problem", type: 'prepPhrase', start: 55, end: 65 },
    { text: "No problem", type: 'chunk', start: 55, end: 65 },
    { text: "right now", type: 'prepPhrase', start: 78, end: 87 },
  ],
  'p15-1': [
    { text: "started with", type: 'phrasalVerb', start: 9, end: 21 },
  ],
  'p15-2': [
    { text: "got lost", type: 'collocation', start: 36, end: 44 },
    { text: "as soon as", type: 'prepPhrase', start: 70, end: 80 },
  ],
  'p15-3': [
    { text: "looking for", type: 'phrasalVerb', start: 36, end: 47 },
    { text: "By the time", type: 'chunk', start: 64, end: 75 },
  ],
  'p15-4': [
    { text: "stayed calm", type: 'collocation', start: 10, end: 21 },
  ],
  'p15-5': [
    { text: "That's why", type: 'chunk', start: 61, end: 71 },
    { text: "a lot of", type: 'prepPhrase', start: 132, end: 140 },
  ],
  'p16-4': [
    { text: "starting with", type: 'phrasalVerb', start: 49, end: 62 },
  ],
  'p17-2': [
    { text: "take a break", type: 'collocation', start: 65, end: 77 },
    { text: "after all", type: 'prepPhrase', start: 78, end: 87 },
    { text: "needs to", type: 'collocation', start: 116, end: 124 },
  ],
  'p17-3': [
    { text: "It was getting", type: 'chunk', start: 0, end: 14 },
  ],
  'p17-5': [
    { text: "want to", type: 'collocation', start: 119, end: 126 },
  ],
  'p18-2': [
    { text: "going out", type: 'phrasalVerb', start: 22, end: 31 },
    { text: "right now", type: 'prepPhrase', start: 71, end: 80 },
  ],
  'p18-3': [
    { text: "wanted to", type: 'collocation', start: 4, end: 13 },
  ],
  'p18-4': [
    { text: "thought about", type: 'phrasalVerb', start: 3, end: 16 },
    { text: "instead", type: 'chunk', start: 51, end: 58 },
    { text: "As far as", type: 'prepPhrase', start: 61, end: 70 },
  ],
  'p18-5': [
    { text: "instead", type: 'chunk', start: 125, end: 132 },
  ],
  'p19-2': [
    { text: "the same", type: 'chunk', start: 117, end: 125 },
  ],
  'p19-3': [
    { text: "ended up", type: 'phrasalVerb', start: 3, end: 11 },
  ],
  'p19-5': [
    { text: "have to", type: 'collocation', start: 114, end: 121 },
  ],
  'p20-1': [
    { text: "look forward to", type: 'phrasalVerb', start: 148, end: 163 },
  ],
  'p20-2': [
    { text: "new place", type: 'collocation', start: 26, end: 35 },
  ],
  'p20-3': [
    { text: "tried to", type: 'collocation', start: 3, end: 11 },
  ],
  'p20-4': [
    { text: "worry about", type: 'phrasalVerb', start: 59, end: 70 },
  ],
  'p21-3': [
    { text: "right away", type: 'prepPhrase', start: 126, end: 136 },
  ],
  'p23-1': [
    { text: "the same", type: 'chunk', start: 108, end: 116 },
  ],
  'p24-1': [
    { text: "looked up", type: 'phrasalVerb', start: 11, end: 20 },
  ],
  'p24-2': [
    { text: "take a deep breath", type: 'collocation', start: 51, end: 69 },
  ],
  'p24-3': [
    { text: "going on", type: 'phrasalVerb', start: 31, end: 39 },
    { text: "listened to", type: 'phrasalVerb', start: 94, end: 105 },
  ],
  'p24-4': [
    { text: "come back", type: 'phrasalVerb', start: 62, end: 71 },
  ],
  'p24-5': [
    { text: "wanted to", type: 'collocation', start: 7, end: 16 },
    { text: "feel better", type: 'collocation', start: 54, end: 65 },
  ],
  'p25-1': [
    { text: "at the counter", type: 'prepPhrase', start: 20, end: 34 },
  ],
  'p25-2': [
    { text: "looking for", type: 'phrasalVerb', start: 53, end: 64 },
  ],
  'p25-5': [
    { text: "want to", type: 'collocation', start: 51, end: 58 },
  ],
  'p26-5': [
    { text: "at the counter", type: 'prepPhrase', start: 24, end: 38 },
  ],
  'p27-1': [
    { text: "checking in", type: 'phrasalVerb', start: 42, end: 53 },
    { text: "asked for", type: 'phrasalVerb', start: 97, end: 106 },
  ],
  'p27-2': [
    { text: "at once", type: 'prepPhrase', start: 34, end: 41 },
  ],
  'p27-3': [
    { text: "have time", type: 'collocation', start: 49, end: 58 },
  ],
  'p28-3': [
    { text: "check in", type: 'phrasalVerb', start: 54, end: 62 },
  ],
  'p28-4': [
    { text: "a few times", type: 'prepPhrase', start: 18, end: 29 },
  ],
  'p29-1': [
    { text: "I need to", type: 'chunk', start: 47, end: 56 },
    { text: "need to", type: 'collocation', start: 49, end: 56 },
  ],
  'p29-3': [
    { text: "the same", type: 'chunk', start: 41, end: 49 },
  ],
  'p30-1': [
    { text: "running out of", type: 'phrasalVerb', start: 46, end: 60 },
    { text: "just in time", type: 'prepPhrase', start: 111, end: 123 },
    { text: "just in", type: 'chunk', start: 111, end: 118 },
  ],
  'p30-2': [
    { text: "turned up", type: 'phrasalVerb', start: 85, end: 94 },
  ],
  'p31-1': [
    { text: "It looks like", type: 'chunk', start: 47, end: 60 },
    { text: "just in case", type: 'prepPhrase', start: 115, end: 127 },
    { text: "just in", type: 'chunk', start: 115, end: 122 },
  ],
  'p32-1': [
    { text: "work out", type: 'phrasalVerb', start: 47, end: 55 },
    { text: "asked for", type: 'phrasalVerb', start: 111, end: 120 },
  ],
  'p32-5': [
    { text: "Getting up", type: 'phrasalVerb', start: 0, end: 10 },
    { text: "waking up", type: 'phrasalVerb', start: 46, end: 55 },
  ],
  'p33-1': [
    { text: "wanted to", type: 'collocation', start: 100, end: 109 },
  ],
  'p33-2': [
    { text: "in the corner", type: 'prepPhrase', start: 21, end: 34 },
    { text: "wanted to", type: 'collocation', start: 61, end: 70 },
  ],
  'p33-3': [
    { text: "good at", type: 'chunk', start: 56, end: 63 },
  ],
  'p33-5': [
    { text: "picked up", type: 'phrasalVerb', start: 52, end: 61 },
  ],
  'p34-3': [
    { text: "take out", type: 'phrasalVerb', start: 54, end: 62 },
  ],
  'p35-1': [
    { text: "get ready", type: 'collocation', start: 76, end: 85 },
    { text: "ready for", type: 'chunk', start: 80, end: 89 },
  ],
  'p35-3': [
    { text: "slowed down", type: 'phrasalVerb', start: 97, end: 108 },
  ],
  'p35-4': [
    { text: "by the door", type: 'prepPhrase', start: 23, end: 34 },
    { text: "by herself", type: 'prepPhrase', start: 39, end: 49 },
    { text: "Good job", type: 'collocation', start: 52, end: 60 },
  ],
  'p35-5': [
    { text: "the same", type: 'chunk', start: 31, end: 39 },
    { text: "need to", type: 'collocation', start: 50, end: 57 },
    { text: "thought about", type: 'phrasalVerb', start: 103, end: 116 },
  ],
  'p36-2': [
    { text: "at all", type: 'prepPhrase', start: 73, end: 79 },
    { text: "step by step", type: 'prepPhrase', start: 119, end: 131 },
  ],
  'p36-4': [
    { text: "Want to", type: 'collocation', start: 40, end: 47 },
    { text: "new place", type: 'collocation', start: 114, end: 123 },
  ],
  'p37-1': [
    { text: "picked up", type: 'phrasalVerb', start: 9, end: 18 },
    { text: "right away", type: 'prepPhrase', start: 107, end: 117 },
  ],
  'p37-2': [
    { text: "for a second", type: 'prepPhrase', start: 19, end: 31 },
  ],
  'p37-3': [
    { text: "no problem", type: 'prepPhrase', start: 111, end: 121 },
    { text: "no problem", type: 'chunk', start: 111, end: 121 },
    { text: "at all", type: 'prepPhrase', start: 122, end: 128 },
  ],
  'p37-4': [
    { text: "breaking up", type: 'phrasalVerb', start: 59, end: 70 },
  ],
  'p37-5': [
    { text: "at the door", type: 'prepPhrase', start: 73, end: 84 },
  ],
  'p38-1': [
    { text: "get started", type: 'collocation', start: 52, end: 63 },
  ],
  'p38-2': [
    { text: "Moving on", type: 'phrasalVerb', start: 41, end: 50 },
  ],
  'p38-4': [
    { text: "make sense", type: 'phrasalVerb', start: 50, end: 60 },
    { text: "so far", type: 'prepPhrase', start: 61, end: 67 },
  ],
  'p39-2': [
    { text: "looking for", type: 'phrasalVerb', start: 104, end: 115 },
  ],
  'p39-3': [
    { text: "wanted to", type: 'collocation', start: 14, end: 23 },
    { text: "give up", type: 'phrasalVerb', start: 24, end: 31 },
  ],
  'p40-1': [
    { text: "I can't believe", type: 'chunk', start: 41, end: 56 },
  ],
  'p40-3': [
    { text: "proud of", type: 'chunk', start: 51, end: 59 },
  ],
  'p40-5': [
    { text: "came back", type: 'phrasalVerb', start: 25, end: 34 },
  ],
  'p41-4': [
    { text: "asked for", type: 'phrasalVerb', start: 4, end: 13 },
    { text: "right away", type: 'prepPhrase', start: 32, end: 42 },
  ],
  'p41-5': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
  ],
  'p42-4': [
    { text: "by the door", type: 'prepPhrase', start: 114, end: 125 },
  ],
  'p43-2': [
    { text: "no problem", type: 'prepPhrase', start: 112, end: 122 },
    { text: "no problem", type: 'chunk', start: 112, end: 122 },
  ],
  'p43-4': [
    { text: "for a while", type: 'prepPhrase', start: 35, end: 46 },
  ],
  'p43-5': [
    { text: "take off", type: 'phrasalVerb', start: 54, end: 62 },
  ],
  'p44-4': [
    { text: "came back", type: 'phrasalVerb', start: 2, end: 11 },
  ],
  'p44-5': [
    { text: "gave up", type: 'phrasalVerb', start: 89, end: 96 },
    { text: "instead", type: 'chunk', start: 116, end: 123 },
  ],
  'p45-5': [
    { text: "over and over", type: 'prepPhrase', start: 18, end: 31 },
    { text: "no matter what", type: 'prepPhrase', start: 61, end: 75 },
    { text: "take a look", type: 'collocation', start: 107, end: 118 },
  ],
  'p46-2': [
    { text: "needs to", type: 'collocation', start: 37, end: 45 },
  ],
  'p46-3': [
    { text: "I need to", type: 'chunk', start: 38, end: 47 },
    { text: "need to", type: 'collocation', start: 40, end: 47 },
  ],
  'p46-4': [
    { text: "at once", type: 'prepPhrase', start: 28, end: 35 },
  ],
  'p47-3': [
    { text: "at least", type: 'prepPhrase', start: 95, end: 103 },
    { text: "at least", type: 'chunk', start: 95, end: 103 },
  ],
  'p48-1': [
    { text: "I'm sorry", type: 'chunk', start: 34, end: 43 },
    { text: "no problem", type: 'prepPhrase', start: 105, end: 115 },
    { text: "no problem", type: 'chunk', start: 105, end: 115 },
    { text: "at all", type: 'prepPhrase', start: 116, end: 122 },
  ],
  'p48-3': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
  ],
  'p48-5': [
    { text: "instead", type: 'chunk', start: 68, end: 75 },
    { text: "right away", type: 'prepPhrase', start: 110, end: 120 },
  ],
  'p49-1': [
    { text: "looked around", type: 'phrasalVerb', start: 25, end: 38 },
  ],
  'p49-2': [
    { text: "by the window", type: 'prepPhrase', start: 117, end: 130 },
  ],
  'p49-3': [
    { text: "slowed down", type: 'phrasalVerb', start: 93, end: 104 },
  ],
  'p49-4': [
    { text: "put on", type: 'phrasalVerb', start: 97, end: 103 },
  ],
  'p49-5': [
    { text: "look like", type: 'phrasalVerb', start: 34, end: 43 },
  ],
  'p50-2': [
    { text: "take a look", type: 'collocation', start: 51, end: 62 },
  ],
  'p50-4': [
    { text: "come out", type: 'phrasalVerb', start: 58, end: 66 },
  ],
  'p52-1': [
    { text: "at the table", type: 'prepPhrase', start: 100, end: 112 },
    { text: "at once", type: 'prepPhrase', start: 120, end: 127 },
  ],
  'p52-3': [
    { text: "stayed quiet", type: 'collocation', start: 96, end: 108 },
  ],
  'p52-4': [
    { text: "on the wall", type: 'prepPhrase', start: 11, end: 22 },
    { text: "grew up", type: 'phrasalVerb', start: 48, end: 55 },
    { text: "wanted to", type: 'collocation', start: 95, end: 104 },
  ],
  'p52-5': [
    { text: "the same", type: 'chunk', start: 18, end: 26 },
  ],
  'p53-1': [
    { text: "asked for", type: 'phrasalVerb', start: 119, end: 128 },
  ],
  'p53-3': [
    { text: "tried to", type: 'collocation', start: 2, end: 10 },
  ],
  'p53-4': [
    { text: "felt like", type: 'phrasalVerb', start: 102, end: 111 },
  ],
  'p53-5': [
    { text: "at all", type: 'prepPhrase', start: 31, end: 37 },
  ],
  'p54-1': [
    { text: "Long time", type: 'collocation', start: 47, end: 56 },
  ],
  'p54-5': [
    { text: "pick up", type: 'phrasalVerb', start: 111, end: 118 },
  ],
  'p55-1': [
    { text: "heard about", type: 'phrasalVerb', start: 55, end: 66 },
  ],
  'p55-3': [
    { text: "I'd been", type: 'chunk', start: 17, end: 25 },
    { text: "the same", type: 'chunk', start: 111, end: 119 },
  ],
  'p55-4': [
    { text: "want to", type: 'collocation', start: 9, end: 16 },
  ],
  'p56-4': [
    { text: "at once", type: 'prepPhrase', start: 115, end: 122 },
  ],
  'p56-5': [
    { text: "on the way", type: 'prepPhrase', start: 9, end: 19 },
    { text: "tried to", type: 'collocation', start: 114, end: 122 },
  ],
  'p57-4': [
    { text: "stepped back", type: 'phrasalVerb', start: 23, end: 35 },
  ],
  'p57-5': [
    { text: "at once", type: 'prepPhrase', start: 108, end: 115 },
  ],
  'p58-2': [
    { text: "right now", type: 'prepPhrase', start: 62, end: 71 },
  ],
  'p58-4': [
    { text: "in the middle of", type: 'prepPhrase', start: 17, end: 33 },
  ],
  'p58-5': [
    { text: "instead", type: 'chunk', start: 123, end: 130 },
  ],
  'p59-3': [
    { text: "on the way", type: 'prepPhrase', start: 74, end: 84 },
  ],
  'p60-1': [
    { text: "moved on", type: 'phrasalVerb', start: 107, end: 115 },
  ],
  'p60-2': [
    { text: "at all", type: 'prepPhrase', start: 73, end: 79 },
  ],
  'p60-3': [
    { text: "go out", type: 'phrasalVerb', start: 33, end: 39 },
  ],
  'p61-2': [
    { text: "in the middle of", type: 'prepPhrase', start: 29, end: 45 },
    { text: "no problem", type: 'prepPhrase', start: 119, end: 129 },
    { text: "no problem", type: 'chunk', start: 119, end: 129 },
  ],
  'p61-3': [
    { text: "wanted to", type: 'collocation', start: 4, end: 13 },
    { text: "right away", type: 'prepPhrase', start: 122, end: 132 },
  ],
  'p62-2': [
    { text: "I wanted to", type: 'chunk', start: 42, end: 53 },
    { text: "wanted to", type: 'collocation', start: 44, end: 53 },
  ],
  'p62-3': [
    { text: "not just", type: 'chunk', start: 24, end: 32 },
  ],
  'p62-5': [
    { text: "needed to", type: 'collocation', start: 3, end: 12 },
    { text: "set up", type: 'phrasalVerb', start: 46, end: 52 },
  ],
  'p63-1': [
    { text: "warm smile", type: 'collocation', start: 35, end: 45 },
  ],
  'p64-1': [
    { text: "asked for", type: 'phrasalVerb', start: 11, end: 20 },
  ],
  'p65-2': [
    { text: "right away", type: 'prepPhrase', start: 64, end: 74 },
  ],
  'p66-2': [
    { text: "the same", type: 'chunk', start: 21, end: 29 },
    { text: "take a look", type: 'collocation', start: 43, end: 54 },
  ],
  'p66-3': [
    { text: "get lost", type: 'collocation', start: 27, end: 35 },
  ],
  'p66-4': [
    { text: "carried on", type: 'phrasalVerb', start: 112, end: 122 },
  ],
  'p66-5': [
    { text: "on time", type: 'prepPhrase', start: 35, end: 42 },
  ],
  'p67-1': [
    { text: "thought about", type: 'phrasalVerb', start: 96, end: 109 },
  ],
  'p67-3': [
    { text: "after that", type: 'chunk', start: 106, end: 116 },
  ],
  'p68-4': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
    { text: "the same", type: 'chunk', start: 52, end: 60 },
    { text: "moved on", type: 'phrasalVerb', start: 111, end: 119 },
  ],
  'p69-1': [
    { text: "talk about", type: 'phrasalVerb', start: 57, end: 67 },
  ],
  'p69-2': [
    { text: "I'm sorry", type: 'chunk', start: 41, end: 50 },
  ],
  'p70-1': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
  ],
  'p70-2': [
    { text: "for once", type: 'prepPhrase', start: 26, end: 34 },
  ],
  'p70-5': [
    { text: "for now", type: 'prepPhrase', start: 62, end: 69 },
  ],
  'p71-1': [
    { text: "at the door", type: 'prepPhrase', start: 89, end: 100 },
  ],
  'p71-2': [
    { text: "want to", type: 'collocation', start: 9, end: 16 },
    { text: "show up", type: 'phrasalVerb', start: 17, end: 24 },
  ],
  'p71-3': [
    { text: "at once", type: 'prepPhrase', start: 124, end: 131 },
  ],
  'p71-4': [
    { text: "by the door", type: 'prepPhrase', start: 11, end: 22 },
  ],
  'p72-1': [
    { text: "at the same time", type: 'prepPhrase', start: 24, end: 40 },
    { text: "the same", type: 'chunk', start: 27, end: 35 },
    { text: "right now", type: 'prepPhrase', start: 75, end: 84 },
  ],
  'p72-2': [
    { text: "for once", type: 'prepPhrase', start: 112, end: 120 },
  ],
  'p73-2': [
    { text: "right away", type: 'prepPhrase', start: 72, end: 82 },
  ],
  'p73-3': [
    { text: "good at", type: 'chunk', start: 67, end: 74 },
  ],
  'p73-4': [
    { text: "decided to", type: 'collocation', start: 93, end: 103 },
  ],
  'p74-2': [
    { text: "made sure", type: 'phrasalVerb', start: 115, end: 124 },
    { text: "made sure", type: 'collocation', start: 115, end: 124 },
  ],
  'p74-4': [
    { text: "I'm sorry", type: 'chunk', start: 48, end: 57 },
    { text: "make up for", type: 'phrasalVerb', start: 129, end: 140 },
  ],
  'p75-4': [
    { text: "ask for", type: 'phrasalVerb', start: 29, end: 36 },
  ],
  'p76-3': [
    { text: "seemed to", type: 'collocation', start: 9, end: 18 },
  ],
  'p77-1': [
    { text: "have a feeling", type: 'collocation', start: 43, end: 57 },
  ],
  'p77-4': [
    { text: "just to", type: 'chunk', start: 20, end: 27 },
    { text: "I'm pretty sure", type: 'chunk', start: 43, end: 58 },
    { text: "just in case", type: 'prepPhrase', start: 110, end: 122 },
    { text: "just in", type: 'chunk', start: 110, end: 117 },
  ],
  'p78-2': [
    { text: "the same", type: 'chunk', start: 109, end: 117 },
  ],
  'p79-1': [
    { text: "the same", type: 'chunk', start: 21, end: 29 },
  ],
  'p79-2': [
    { text: "at least", type: 'prepPhrase', start: 109, end: 117 },
    { text: "at least", type: 'chunk', start: 109, end: 117 },
  ],
  'p79-4': [
    { text: "used to", type: 'phrasalVerb', start: 52, end: 59 },
    { text: "used to", type: 'collocation', start: 52, end: 59 },
    { text: "used to", type: 'chunk', start: 52, end: 59 },
    { text: "waking up", type: 'phrasalVerb', start: 60, end: 69 },
  ],
  'p79-5': [
    { text: "the same", type: 'chunk', start: 132, end: 140 },
  ],
  'p80-4': [
    { text: "I'd been", type: 'chunk', start: 30, end: 38 },
    { text: "hoping for", type: 'phrasalVerb', start: 39, end: 49 },
    { text: "right away", type: 'prepPhrase', start: 109, end: 119 },
  ],
  'p81-2': [
    { text: "at all", type: 'prepPhrase', start: 28, end: 34 },
  ],
  'p81-4': [
    { text: "kept going", type: 'collocation', start: 3, end: 13 },
    { text: "going back", type: 'phrasalVerb', start: 8, end: 18 },
    { text: "back and forth", type: 'prepPhrase', start: 14, end: 28 },
  ],
  'p82-2': [
    { text: "right away", type: 'prepPhrase', start: 112, end: 122 },
  ],
  'p82-3': [
    { text: "to be clear", type: 'prepPhrase', start: 31, end: 42 },
  ],
  'p82-5': [
    { text: "started to", type: 'collocation', start: 20, end: 30 },
  ],
  'p83-3': [
    { text: "just for", type: 'chunk', start: 123, end: 131 },
  ],
  'p84-3': [
    { text: "wanted to", type: 'collocation', start: 11, end: 20 },
  ],
  'p84-4': [
    { text: "I wanted to", type: 'chunk', start: 0, end: 11 },
    { text: "wanted to", type: 'collocation', start: 2, end: 11 },
  ],
  'p85-3': [
    { text: "think about", type: 'phrasalVerb', start: 56, end: 67 },
  ],
  'p85-5': [
    { text: "That's all", type: 'chunk', start: 36, end: 46 },
  ],
  'p86-1': [
    { text: "stay calm", type: 'collocation', start: 51, end: 60 },
  ],
  'p86-3': [
    { text: "Get back", type: 'phrasalVerb', start: 41, end: 49 },
    { text: "just in time", type: 'prepPhrase', start: 93, end: 105 },
    { text: "just in", type: 'chunk', start: 93, end: 100 },
  ],
  'p86-4': [
    { text: "at once", type: 'prepPhrase', start: 119, end: 126 },
  ],
  'p86-5': [
    { text: "right away", type: 'prepPhrase', start: 114, end: 124 },
  ],
  'p87-4': [
    { text: "supposed to", type: 'collocation', start: 50, end: 61 },
    { text: "supposed to", type: 'chunk', start: 50, end: 61 },
  ],
  'p88-2': [
    { text: "feel better", type: 'collocation', start: 58, end: 69 },
  ],
  'p88-3': [
    { text: "listen to", type: 'phrasalVerb', start: 53, end: 62 },
    { text: "instead", type: 'chunk', start: 115, end: 122 },
  ],
  'p89-1': [
    { text: "by the window", type: 'prepPhrase', start: 102, end: 115 },
  ],
  'p89-2': [
    { text: "sat down", type: 'phrasalVerb', start: 3, end: 11 },
  ],
  'p89-3': [
    { text: "it was the best", type: 'chunk', start: 96, end: 111 },
  ],
  'p89-4': [
    { text: "the same", type: 'chunk', start: 80, end: 88 },
  ],
  'p90-3': [
    { text: "looked for", type: 'phrasalVerb', start: 23, end: 33 },
    { text: "at the table", type: 'prepPhrase', start: 51, end: 63 },
    { text: "by the window", type: 'prepPhrase', start: 64, end: 77 },
  ],
  'p90-4': [
    { text: "in the morning", type: 'prepPhrase', start: 64, end: 78 },
  ],
  'p91-3': [
    { text: "wait for", type: 'phrasalVerb', start: 46, end: 54 },
  ],
  'p91-4': [
    { text: "asked for", type: 'phrasalVerb', start: 8, end: 17 },
  ],
  'p91-5': [
    { text: "move on", type: 'phrasalVerb', start: 73, end: 80 },
  ],
  'p93-4': [
    { text: "right away", type: 'prepPhrase', start: 114, end: 124 },
  ],
  'p94-3': [
    { text: "by the window", type: 'prepPhrase', start: 67, end: 80 },
  ],
  'p94-4': [
    { text: "feel like", type: 'phrasalVerb', start: 106, end: 115 },
  ],
  'p95-1': [
    { text: "by the door", type: 'prepPhrase', start: 21, end: 32 },
  ],
  'p96-4': [
    { text: "have to", type: 'collocation', start: 51, end: 58 },
    { text: "instead of", type: 'prepPhrase', start: 65, end: 75 },
    { text: "instead", type: 'chunk', start: 65, end: 72 },
    { text: "at least", type: 'prepPhrase', start: 109, end: 117 },
    { text: "at least", type: 'chunk', start: 109, end: 117 },
  ],
  'p97-2': [
    { text: "on the way", type: 'prepPhrase', start: 111, end: 121 },
  ],
  'p97-5': [
    { text: "just in time", type: 'prepPhrase', start: 48, end: 60 },
    { text: "just in", type: 'chunk', start: 48, end: 55 },
  ],
  'p98-2': [
    { text: "I'd rather", type: 'chunk', start: 91, end: 101 },
  ],
  'p98-3': [
    { text: "decided to", type: 'collocation', start: 89, end: 99 },
  ],
  'p98-4': [
    { text: "the only", type: 'chunk', start: 101, end: 109 },
  ],
  'p99-1': [
    { text: "by the door", type: 'prepPhrase', start: 12, end: 23 },
  ],
  'p99-3': [
    { text: "Take care of", type: 'phrasalVerb', start: 50, end: 62 },
    { text: "Take care", type: 'collocation', start: 50, end: 59 },
  ],
  'p99-5': [
    { text: "keep in touch", type: 'collocation', start: 67, end: 80 },
  ],
  'p100-1': [
    { text: "sat down", type: 'phrasalVerb', start: 33, end: 41 },
  ],
  'p100-2': [
    { text: "on her own", type: 'prepPhrase', start: 115, end: 125 },
  ],
}
