-- Migration: 012_blog_posts.sql
-- Auto-generated blog posts stored in DB (generated by Vercel Cron + Claude API)

CREATE TABLE IF NOT EXISTS blog_posts (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pattern_id   UUID REFERENCES patterns(id),
  locale       TEXT NOT NULL CHECK (locale IN ('en', 'ko')),
  slug         TEXT NOT NULL,
  title        TEXT NOT NULL,
  description  TEXT NOT NULL,
  content      TEXT NOT NULL,
  tags         TEXT[] DEFAULT '{}',
  published_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (pattern_id, locale)
);

CREATE INDEX IF NOT EXISTS idx_blog_posts_locale       ON blog_posts(locale);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON blog_posts(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug         ON blog_posts(slug, locale);

ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read blog posts" ON blog_posts
  FOR SELECT USING (true);
