UPDATE kp_episodes SET title_en = 'At the Café'                  WHERE episode_num = 1;
UPDATE kp_episodes SET title_en = 'At the Subway Station'         WHERE episode_num = 2;
UPDATE kp_episodes SET title_en = 'At the Tteokbokki Stall'      WHERE episode_num = 3;
UPDATE kp_episodes SET title_en = 'At the Convenience Store'     WHERE episode_num = 4;
UPDATE kp_episodes SET title_en = 'At the Restaurant'            WHERE episode_num = 5;
UPDATE kp_episodes SET title_en = 'At the Noraebang (Karaoke)'   WHERE episode_num = 6;
UPDATE kp_episodes SET title_en = 'At the Market'                WHERE episode_num = 7;
UPDATE kp_episodes SET title_en = 'At the Beauty Shop'           WHERE episode_num = 8;
UPDATE kp_episodes SET title_en = 'At the Han River'             WHERE episode_num = 9;
UPDATE kp_episodes SET title_en = 'At School'                    WHERE episode_num = 10;
UPDATE kp_episodes SET title_en = 'Riding the Subway'            WHERE episode_num = 11;
UPDATE kp_episodes SET title_en = 'At the Restaurant, Round 2'   WHERE episode_num = 12;
UPDATE kp_episodes SET title_en = 'Making Plans'                 WHERE episode_num = 13;
UPDATE kp_episodes SET title_en = 'Emma Gets Lost'               WHERE episode_num = 14;
UPDATE kp_episodes SET title_en = 'Drama Recommendations'        WHERE episode_num = 15;
UPDATE kp_episodes SET title_en = 'Talking About the Weather'    WHERE episode_num = 16;
UPDATE kp_episodes SET title_en = 'At the Pharmacy'             WHERE episode_num = 17;
UPDATE kp_episodes SET title_en = 'Talking About Hobbies'       WHERE episode_num = 18;
UPDATE kp_episodes SET title_en = 'A Day at Gyeongbokgung'      WHERE episode_num = 19;
UPDATE kp_episodes SET title_en = 'Meeting After a Long Time'   WHERE episode_num = 20;
UPDATE kp_episodes SET title_en = 'What Did You Do Yesterday?'  WHERE episode_num = 21;
UPDATE kp_episodes SET title_en = 'Making a Guess'              WHERE episode_num = 22;
UPDATE kp_episodes SET title_en = 'Things You Have to Do'       WHERE episode_num = 23;
UPDATE kp_episodes SET title_en = 'Sharing Opinions'            WHERE episode_num = 24;
UPDATE kp_episodes SET title_en = 'Talking About Experiences'   WHERE episode_num = 25;
UPDATE kp_episodes SET title_en = 'Talking About K-Dramas'      WHERE episode_num = 26;
UPDATE kp_episodes SET title_en = 'Talking About K-Pop'         WHERE episode_num = 27;
UPDATE kp_episodes SET title_en = 'K-Beauty Shopping'           WHERE episode_num = 28;
UPDATE kp_episodes SET title_en = 'Health and Exercise'         WHERE episode_num = 29;
UPDATE kp_episodes SET title_en = 'Where Do You Live?'          WHERE episode_num = 30;
