UPDATE kp_episodes SET title_en = 'Expressing How You Feel'   WHERE episode_num = 31;
UPDATE kp_episodes SET title_en = 'Comforting a Friend'        WHERE episode_num = 32;
UPDATE kp_episodes SET title_en = 'Friends on Social Media'    WHERE episode_num = 33;
UPDATE kp_episodes SET title_en = 'Let''s Grab a Meal Sometime' WHERE episode_num = 34;
UPDATE kp_episodes SET title_en = 'Korean Culture'             WHERE episode_num = 35;
UPDATE kp_episodes SET title_en = 'Drinking Culture'           WHERE episode_num = 36;
UPDATE kp_episodes SET title_en = 'Noraebang Night'            WHERE episode_num = 37;
UPDATE kp_episodes SET title_en = 'K-Dance Class'              WHERE episode_num = 38;
UPDATE kp_episodes SET title_en = 'Studying at a Café'         WHERE episode_num = 39;
UPDATE kp_episodes SET title_en = 'Settling In'                WHERE episode_num = 40;
UPDATE kp_episodes SET title_en = 'Linking Your Sentences'     WHERE episode_num = 41;
UPDATE kp_episodes SET title_en = 'Conditions and Suggestions' WHERE episode_num = 42;
UPDATE kp_episodes SET title_en = 'Reasons and Comparisons'    WHERE episode_num = 43;
UPDATE kp_episodes SET title_en = 'Putting Events in Order'    WHERE episode_num = 44;
UPDATE kp_episodes SET title_en = 'Offering a Hand'            WHERE episode_num = 45;
UPDATE kp_episodes SET title_en = 'How Long It''s Been'         WHERE episode_num = 46;
UPDATE kp_episodes SET title_en = 'Fashion Talk'               WHERE episode_num = 47;
UPDATE kp_episodes SET title_en = 'Food Delivery'              WHERE episode_num = 48;
UPDATE kp_episodes SET title_en = 'Planning a Trip'            WHERE episode_num = 49;
UPDATE kp_episodes SET title_en = 'Halfway Through'            WHERE episode_num = 50;
UPDATE kp_episodes SET title_en = 'Making a Plan'              WHERE episode_num = 51;
UPDATE kp_episodes SET title_en = 'Making Up Your Mind'        WHERE episode_num = 52;
UPDATE kp_episodes SET title_en = 'Sharing What You''ve Done'   WHERE episode_num = 53;
UPDATE kp_episodes SET title_en = 'Language Exchange'          WHERE episode_num = 54;
UPDATE kp_episodes SET title_en = 'Cooking Together'           WHERE episode_num = 55;
UPDATE kp_episodes SET title_en = 'Shopping Day'               WHERE episode_num = 56;
UPDATE kp_episodes SET title_en = 'A Part-Time Job'            WHERE episode_num = 57;
UPDATE kp_episodes SET title_en = 'At the Clinic'              WHERE episode_num = 58;
UPDATE kp_episodes SET title_en = 'At a Book Café'             WHERE episode_num = 59;
UPDATE kp_episodes SET title_en = 'Food Culture'               WHERE episode_num = 60;
UPDATE kp_episodes SET title_en = 'Saying It Just Right'       WHERE episode_num = 61;
UPDATE kp_episodes SET title_en = 'Life at Work'               WHERE episode_num = 62;
UPDATE kp_episodes SET title_en = 'Social Media Trends'        WHERE episode_num = 63;
UPDATE kp_episodes SET title_en = 'A Cooking Challenge'        WHERE episode_num = 64;
UPDATE kp_episodes SET title_en = 'A K-Beauty Routine'         WHERE episode_num = 65;
UPDATE kp_episodes SET title_en = 'How Far You''ve Come'        WHERE episode_num = 66;
UPDATE kp_episodes SET title_en = 'Weather and Seasons'        WHERE episode_num = 67;
UPDATE kp_episodes SET title_en = 'Clearing the Air'           WHERE episode_num = 68;
UPDATE kp_episodes SET title_en = 'Goals and Dreams'           WHERE episode_num = 69;
UPDATE kp_episodes SET title_en = 'Recycling in Korea'         WHERE episode_num = 70;
UPDATE kp_episodes SET title_en = 'A Heartfelt Talk'           WHERE episode_num = 71;
UPDATE kp_episodes SET title_en = 'A Misunderstanding'         WHERE episode_num = 72;
UPDATE kp_episodes SET title_en = 'Reaching a Goal'            WHERE episode_num = 73;
UPDATE kp_episodes SET title_en = 'Exploring Korean Food'      WHERE episode_num = 74;
UPDATE kp_episodes SET title_en = 'Everyday Joys'              WHERE episode_num = 75;
UPDATE kp_episodes SET title_en = 'Struggling with Korean'     WHERE episode_num = 76;
UPDATE kp_episodes SET title_en = 'Time with Friends'          WHERE episode_num = 77;
UPDATE kp_episodes SET title_en = 'Chasing a Dream'            WHERE episode_num = 78;
UPDATE kp_episodes SET title_en = 'Hunting for Good Food'      WHERE episode_num = 79;
UPDATE kp_episodes SET title_en = 'Feeling the Progress'       WHERE episode_num = 80;
UPDATE kp_episodes SET title_en = 'Passing It Along'           WHERE episode_num = 81;
UPDATE kp_episodes SET title_en = 'A Gradual Change'           WHERE episode_num = 82;
UPDATE kp_episodes SET title_en = 'Nuance, Level Up'           WHERE episode_num = 83;
UPDATE kp_episodes SET title_en = 'Taking Your Time to Decide' WHERE episode_num = 84;
UPDATE kp_episodes SET title_en = 'Reading the Situation'      WHERE episode_num = 85;
UPDATE kp_episodes SET title_en = 'Getting the Culture'        WHERE episode_num = 86;
UPDATE kp_episodes SET title_en = 'Being Honest'               WHERE episode_num = 87;
UPDATE kp_episodes SET title_en = 'Sounding Fluent'            WHERE episode_num = 88;
UPDATE kp_episodes SET title_en = 'Off the Tourist Trail'      WHERE episode_num = 89;
UPDATE kp_episodes SET title_en = 'What''s Trending'            WHERE episode_num = 90;
UPDATE kp_episodes SET title_en = 'Softening What You Say'     WHERE episode_num = 91;
UPDATE kp_episodes SET title_en = 'Making Your Point'          WHERE episode_num = 92;
UPDATE kp_episodes SET title_en = 'Deeper Feelings'            WHERE episode_num = 93;
UPDATE kp_episodes SET title_en = 'Real Comfort'               WHERE episode_num = 94;
UPDATE kp_episodes SET title_en = 'Watching a Drama'           WHERE episode_num = 95;
UPDATE kp_episodes SET title_en = 'Feelings Hard to Name'      WHERE episode_num = 96;
UPDATE kp_episodes SET title_en = 'Goodbyes and Longing'       WHERE episode_num = 97;
UPDATE kp_episodes SET title_en = 'Fluency, Finally'           WHERE episode_num = 98;
UPDATE kp_episodes SET title_en = 'Gratitude'                  WHERE episode_num = 99;
UPDATE kp_episodes SET title_en = 'The Journey Begins'         WHERE episode_num = 100;
