-- ============================================================
-- K-PATTO expressions SEO migration
-- 생성일: 2026-08-07T06:37:54.057Z
-- ⚠ 실행 전 반드시 _backup-kp-tables.ts 로 백업할 것
-- ============================================================

BEGIN;

-- [1] 컬럼 추가
ALTER TABLE kp_expressions
  ADD COLUMN IF NOT EXISTS romaja    text,
  ADD COLUMN IF NOT EXISTS heading_en text;

-- [2] slug UPDATE (is_new_slug=true, 225건)
UPDATE kp_expressions SET slug = 'eottaeyo' WHERE id = 775;
UPDATE kp_expressions SET slug = 'cheoeumieonneunde' WHERE id = 829;
UPDATE kp_expressions SET slug = 'geuncheoe-mwo-isseo' WHERE id = 856;
UPDATE kp_expressions SET slug = 'gibuni-eottae' WHERE id = 857;
UPDATE kp_expressions SET slug = 'raseo-haengbokae' WHERE id = 858;
UPDATE kp_expressions SET slug = 'seolle' WHERE id = 859;
UPDATE kp_expressions SET slug = 'gwaenchanayo' WHERE id = 860;
UPDATE kp_expressions SET slug = 'yojeum-jom-himdeureoyo' WHERE id = 861;
UPDATE kp_expressions SET slug = 'eonjedeunji-yeollakaeyo' WHERE id = 862;
UPDATE kp_expressions SET slug = 'kakaotok-haeyo' WHERE id = 863;
UPDATE kp_expressions SET slug = 'pallouhaedo-dwaeyo' WHERE id = 864;
UPDATE kp_expressions SET slug = 'jega-salgeyo' WHERE id = 866;
UPDATE kp_expressions SET slug = 'deochipei-haeyo' WHERE id = 867;
UPDATE kp_expressions SET slug = 'bap-hanbeon-meogeoyo' WHERE id = 868;
UPDATE kp_expressions SET slug = 'baedal-sikyeoyo' WHERE id = 869;
UPDATE kp_expressions SET slug = 'ibeo-bwasseo' WHERE id = 870;
UPDATE kp_expressions SET slug = 'myeongjeore-mwo-hae' WHERE id = 871;
UPDATE kp_expressions SET slug = 'ige-museun-tteusiya' WHERE id = 872;
UPDATE kp_expressions SET slug = 'sul-masyeoyo' WHERE id = 873;
UPDATE kp_expressions SET slug = 'geonbaehaeyo' WHERE id = 874;
UPDATE kp_expressions SET slug = 'yeogikkajiman-haeyo' WHERE id = 875;
UPDATE kp_expressions SET slug = 'i-norae-gachi-bulleoyo' WHERE id = 876;
UPDATE kp_expressions SET slug = 'sincheonggok-isseoyo' WHERE id = 877;
UPDATE kp_expressions SET slug = 'han-gok-deo-haeyo' WHERE id = 878;
UPDATE kp_expressions SET slug = 'gachi-chwoyo' WHERE id = 879;
UPDATE kp_expressions SET slug = 'eoryeopjiman-jaemiisseoyo' WHERE id = 880;
UPDATE kp_expressions SET slug = 'hada-bomyeon-neureoyo' WHERE id = 881;
UPDATE kp_expressions SET slug = 'bunwigi-joayo' WHERE id = 882;
UPDATE kp_expressions SET slug = 'daldalhan-geo-isseoyo' WHERE id = 883;
UPDATE kp_expressions SET slug = 'orae-isseodo-dwaeyo' WHERE id = 884;
UPDATE kp_expressions SET slug = 'naramada-dallayo' WHERE id = 885;
UPDATE kp_expressions SET slug = 'ije-jeogeungi-dwaesseoyo' WHERE id = 886;
UPDATE kp_expressions SET slug = 'cheoeumen-natseoreonneunde' WHERE id = 887;
UPDATE kp_expressions SET slug = 'neunde' WHERE id = 888;
UPDATE kp_expressions SET slug = 'myeon-eottaeyo' WHERE id = 891;
UPDATE kp_expressions SET slug = 'myeon-jokesseoyo' WHERE id = 892;
UPDATE kp_expressions SET slug = 'myeon-dwaeyo' WHERE id = 893;
UPDATE kp_expressions SET slug = 'ttaemune' WHERE id = 894;
UPDATE kp_expressions SET slug = 'deokbune' WHERE id = 895;
UPDATE kp_expressions SET slug = 'neun-dongan' WHERE id = 897;
UPDATE kp_expressions SET slug = 'go-naseo' WHERE id = 898;
UPDATE kp_expressions SET slug = 'gi-jeone' WHERE id = 899;
UPDATE kp_expressions SET slug = 'hae-deurilkkayo' WHERE id = 901;
UPDATE kp_expressions SET slug = 'joesonghandeyo-hoksi' WHERE id = 902;
UPDATE kp_expressions SET slug = 'ji-eolmana-dwaesseoyo' WHERE id = 903;
UPDATE kp_expressions SET slug = 'ajik-neun-jungieyo' WHERE id = 904;
UPDATE kp_expressions SET slug = 'geoui-da-dwaesseoyo' WHERE id = 905;
UPDATE kp_expressions SET slug = 'seutail-joahaeyo' WHERE id = 906;
UPDATE kp_expressions SET slug = 'jal-eoullyeoyo' WHERE id = 907;
UPDATE kp_expressions SET slug = 'yojeum-yuhaengieyo' WHERE id = 908;
UPDATE kp_expressions SET slug = 'baedal-eolmana-geollyeoyo' WHERE id = 909;
UPDATE kp_expressions SET slug = 'gaseongbi-joayo' WHERE id = 910;
UPDATE kp_expressions SET slug = 'yeohaeng-gyehoek-isseoyo' WHERE id = 911;
UPDATE kp_expressions SET slug = 'myeochirina-isseul-geoyeyo' WHERE id = 912;
UPDATE kp_expressions SET slug = 'hanguk-saenghwal-eottae' WHERE id = 914;
UPDATE kp_expressions SET slug = 'ije-iksukaejyeosseo' WHERE id = 915;
UPDATE kp_expressions SET slug = 'ryeogo-haeyo' WHERE id = 918;
UPDATE kp_expressions SET slug = 'go-sipeoyo' WHERE id = 919;
UPDATE kp_expressions SET slug = 'giro-haesseoyo' WHERE id = 920;
UPDATE kp_expressions SET slug = 'maeummeogeosseoyo' WHERE id = 921;
UPDATE kp_expressions SET slug = 'yejeonboda-neureosseoyo' WHERE id = 922;
UPDATE kp_expressions SET slug = 'bonikka' WHERE id = 924;
UPDATE kp_expressions SET slug = 'chucheonhaejwosseo' WHERE id = 925;
UPDATE kp_expressions SET slug = 'maja' WHERE id = 927;
UPDATE kp_expressions SET slug = 'mandeureobwasseo' WHERE id = 929;
UPDATE kp_expressions SET slug = 'eolmana-neoeo' WHERE id = 930;
UPDATE kp_expressions SET slug = 'hamyeon-dwae' WHERE id = 931;
UPDATE kp_expressions SET slug = 'sal-geoyeyo' WHERE id = 932;
UPDATE kp_expressions SET slug = 'igeo-eottaeyo' WHERE id = 933;
UPDATE kp_expressions SET slug = 'kadeuro-halgeyo' WHERE id = 934;
UPDATE kp_expressions SET slug = 'batgo-sipeoyo' WHERE id = 937;
UPDATE kp_expressions SET slug = 'eodiga-apayo' WHERE id = 938;
UPDATE kp_expressions SET slug = 'eonjebuteo-apasseoyo' WHERE id = 939;
UPDATE kp_expressions SET slug = 'wa-bwasseoyo' WHERE id = 940;
UPDATE kp_expressions SET slug = 'hagi-joayo' WHERE id = 941;
UPDATE kp_expressions SET slug = 'junge-mwoga-jeil-joayo' WHERE id = 942;
UPDATE kp_expressions SET slug = 'raseo-jungdokseong-isseoyo' WHERE id = 943;
UPDATE kp_expressions SET slug = 'irang-dallayo' WHERE id = 944;
UPDATE kp_expressions SET slug = 'eungeunhi-hae' WHERE id = 947;
UPDATE kp_expressions SET slug = 'ttaemune-bappayo' WHERE id = 948;
UPDATE kp_expressions SET slug = 'murihaji-maseyo' WHERE id = 949;
UPDATE kp_expressions SET slug = 'mani-hae' WHERE id = 950;
UPDATE kp_expressions SET slug = 'yuhaengiya' WHERE id = 951;
UPDATE kp_expressions SET slug = 'ollyeotdeoni' WHERE id = 952;
UPDATE kp_expressions SET slug = 'dojeonhaeyo' WHERE id = 953;
UPDATE kp_expressions SET slug = 'jaeryoga-isseoyo' WHERE id = 954;
UPDATE kp_expressions SET slug = 'daeumen-deo-jalhal-geoyeyo' WHERE id = 955;
UPDATE kp_expressions SET slug = 'rutin-isseoyo' WHERE id = 956;
UPDATE kp_expressions SET slug = 'hago-naseo' WHERE id = 957;
UPDATE kp_expressions SET slug = 'kkok-haeya-haeyo' WHERE id = 958;
UPDATE kp_expressions SET slug = 'mani-neureosseoyo' WHERE id = 959;
UPDATE kp_expressions SET slug = 'bigyeori-mwoyeyo' WHERE id = 960;
UPDATE kp_expressions SET slug = 'i-hetgallyeoyo' WHERE id = 961;
UPDATE kp_expressions SET slug = 'seounhaesseoyo' WHERE id = 965;
UPDATE kp_expressions SET slug = 'maeumeun-arayo' WHERE id = 966;
UPDATE kp_expressions SET slug = 'malhago-nanikka' WHERE id = 967;
UPDATE kp_expressions SET slug = 'kkumi-mwoyeyo' WHERE id = 968;
UPDATE kp_expressions SET slug = 'ga-doego-sipeoyo' WHERE id = 969;
UPDATE kp_expressions SET slug = 'pogihago-sipeoyo' WHERE id = 970;
UPDATE kp_expressions SET slug = 'pyohyeonhagi-eoryeowoyo' WHERE id = 974;
UPDATE kp_expressions SET slug = 'i-neukkim-arayo' WHERE id = 975;
UPDATE kp_expressions SET slug = 'waenji-moreuge-haeyo' WHERE id = 976;
UPDATE kp_expressions SET slug = 'ttak-i-neukkimieyo' WHERE id = 977;
UPDATE kp_expressions SET slug = 'hapgyeokaesseoyo' WHERE id = 981;
UPDATE kp_expressions SET slug = 'deudieo-haenaesseoyo' WHERE id = 982;
UPDATE kp_expressions SET slug = 'meogeobwa' WHERE id = 984;
UPDATE kp_expressions SET slug = 'saenggakboda-hwolssin-hae' WHERE id = 985;
UPDATE kp_expressions SET slug = 'jungdokseong-isseo' WHERE id = 986;
UPDATE kp_expressions SET slug = 'haengbokaeyo' WHERE id = 987;
UPDATE kp_expressions SET slug = 'haneun-ge-joayo' WHERE id = 988;
UPDATE kp_expressions SET slug = 'ireon-ilsangi-sojunghaeyo' WHERE id = 989;
UPDATE kp_expressions SET slug = 'da-gachi-moinikka-joayo' WHERE id = 992;
UPDATE kp_expressions SET slug = 'cheoeum-mannasseul-ttae' WHERE id = 993;
UPDATE kp_expressions SET slug = 'yeoreobun-deokbunieyo' WHERE id = 994;
UPDATE kp_expressions SET slug = 'apeurodo-jal-butakaeyo' WHERE id = 995;
UPDATE kp_expressions SET slug = 'eolmana-isseul-geoyeyo' WHERE id = 996;
UPDATE kp_expressions SET slug = 'jul-seoya-haeyo' WHERE id = 998;
UPDATE kp_expressions SET slug = 'ge-dwaesseoyo' WHERE id = 1007;
UPDATE kp_expressions SET slug = 'da-bonikka' WHERE id = 1008;
UPDATE kp_expressions SET slug = 'hada-bomyeon' WHERE id = 1009;
UPDATE kp_expressions SET slug = 'han-geotchigoneun' WHERE id = 1010;
UPDATE kp_expressions SET slug = 'amuri-geuraedo' WHERE id = 1011;
UPDATE kp_expressions SET slug = 'jal-moreugenneundeyo' WHERE id = 1012;
UPDATE kp_expressions SET slug = 'deo-saenggakae-bwayagesseo' WHERE id = 1013;
UPDATE kp_expressions SET slug = 'ildaneun-haeyo' WHERE id = 1014;
UPDATE kp_expressions SET slug = 'nunchichaesseoyo' WHERE id = 1015;
UPDATE kp_expressions SET slug = 'gami-japyeoyo' WHERE id = 1016;
UPDATE kp_expressions SET slug = 'ttak-bwado-algesseoyo' WHERE id = 1017;
UPDATE kp_expressions SET slug = 'budamseureowoyo' WHERE id = 1020;
UPDATE kp_expressions SET slug = 'soljikage-malhaedo-dwaeyo' WHERE id = 1021;
UPDATE kp_expressions SET slug = 'ije-mani-pyeonhaejyeosseo' WHERE id = 1022;
UPDATE kp_expressions SET slug = 'oegugin-ti-nayo' WHERE id = 1023;
UPDATE kp_expressions SET slug = 'ije-hangungmari-pyeonhaeyo' WHERE id = 1024;
UPDATE kp_expressions SET slug = 'hangugeoro-kkumdo-kkwoyo' WHERE id = 1025;
UPDATE kp_expressions SET slug = 'rokeori-joa' WHERE id = 1026;
UPDATE kp_expressions SET slug = 'hyeonjiindeuri-ganeun' WHERE id = 1027;
UPDATE kp_expressions SET slug = 'sumgyeojin-myeongsoya' WHERE id = 1028;
UPDATE kp_expressions SET slug = 'yojeum-hataeyo' WHERE id = 1029;
UPDATE kp_expressions SET slug = 'wanjeon-daeseyeyo' WHERE id = 1030;
UPDATE kp_expressions SET slug = 'tteooreuneun-jungieyo' WHERE id = 1031;
UPDATE kp_expressions SET slug = 'mari-doeneyo' WHERE id = 1034;
UPDATE kp_expressions SET slug = 'apdwiga-an-majayo' WHERE id = 1035;
UPDATE kp_expressions SET slug = 'gyeolgugen' WHERE id = 1036;
UPDATE kp_expressions SET slug = 'soksanghaesseoyo' WHERE id = 1037;
UPDATE kp_expressions SET slug = 'eogulhaesseoyo' WHERE id = 1038;
UPDATE kp_expressions SET slug = 'banjeon-isseoyo' WHERE id = 1042;
UPDATE kp_expressions SET slug = 'yeouni-namayo' WHERE id = 1043;
UPDATE kp_expressions SET slug = 'moribi-dwaeyo' WHERE id = 1044;
UPDATE kp_expressions SET slug = 'tteonagi-sileo' WHERE id = 1046;
UPDATE kp_expressions SET slug = 'i-geuriul-geot-gata' WHERE id = 1047;
UPDATE kp_expressions SET slug = 'kkok-dasi-olge' WHERE id = 1048;
UPDATE kp_expressions SET slug = 'hangugeoro-saenggakaeyo' WHERE id = 1049;
UPDATE kp_expressions SET slug = 'beonyeok-an-haedo' WHERE id = 1050;
UPDATE kp_expressions SET slug = 'sillyeogi-neureosseoyo' WHERE id = 1051;
UPDATE kp_expressions SET slug = 'gachi-seongjanghan-geot' WHERE id = 1052;
UPDATE kp_expressions SET slug = 'deokbune-mani-baewosseo' WHERE id = 1053;
UPDATE kp_expressions SET slug = 'geona' WHERE id = 1301;
UPDATE kp_expressions SET slug = 'geodeun' WHERE id = 1302;
UPDATE kp_expressions SET slug = 'ge-doeda' WHERE id = 1303;
UPDATE kp_expressions SET slug = 'get' WHERE id = 1304;
UPDATE kp_expressions SET slug = 'go-malda' WHERE id = 1305;
UPDATE kp_expressions SET slug = 'goseo' WHERE id = 1306;
UPDATE kp_expressions SET slug = 'gi-wihae' WHERE id = 1307;
UPDATE kp_expressions SET slug = 'giro-hada' WHERE id = 1308;
UPDATE kp_expressions SET slug = 'gie' WHERE id = 1309;
UPDATE kp_expressions SET slug = 'na-boda' WHERE id = 1310;
UPDATE kp_expressions SET slug = 'na-sipda' WHERE id = 1311;
UPDATE kp_expressions SET slug = 'neurago' WHERE id = 1312;
UPDATE kp_expressions SET slug = 'neun-geot-gatgido' WHERE id = 1313;
UPDATE kp_expressions SET slug = 'neun-ge-anira' WHERE id = 1314;
UPDATE kp_expressions SET slug = 'neun-gime' WHERE id = 1315;
UPDATE kp_expressions SET slug = 'neun-daero' WHERE id = 1316;
UPDATE kp_expressions SET slug = 'neun-daesine' WHERE id = 1317;
UPDATE kp_expressions SET slug = 'neun-barame' WHERE id = 1318;
UPDATE kp_expressions SET slug = 'neun-jul-aratda' WHERE id = 1319;
UPDATE kp_expressions SET slug = 'neun-pyeonida' WHERE id = 1320;
UPDATE kp_expressions SET slug = 'neundago' WHERE id = 1321;
UPDATE kp_expressions SET slug = 'neundamyeonseo' WHERE id = 1322;
UPDATE kp_expressions SET slug = 'neunji' WHERE id = 1323;
UPDATE kp_expressions SET slug = 'ni-eomi' WHERE id = 1324;
UPDATE kp_expressions SET slug = 'dasipi' WHERE id = 1325;
UPDATE kp_expressions SET slug = 'deogun' WHERE id = 1326;
UPDATE kp_expressions SET slug = 'deora' WHERE id = 1327;
UPDATE kp_expressions SET slug = 'deorado' WHERE id = 1328;
UPDATE kp_expressions SET slug = 'deon' WHERE id = 1329;
UPDATE kp_expressions SET slug = 'deonde' WHERE id = 1330;
UPDATE kp_expressions SET slug = 'dorok' WHERE id = 1331;
UPDATE kp_expressions SET slug = 'seumnikka' WHERE id = 1332;
UPDATE kp_expressions SET slug = 'eo-gada' WHERE id = 1335;
UPDATE kp_expressions SET slug = 'eo-nota' WHERE id = 1336;
UPDATE kp_expressions SET slug = 'eo-duda' WHERE id = 1337;
UPDATE kp_expressions SET slug = 'eo-deurida' WHERE id = 1338;
UPDATE kp_expressions SET slug = 'eo-beorida' WHERE id = 1339;
UPDATE kp_expressions SET slug = 'eo-oda' WHERE id = 1341;
UPDATE kp_expressions SET slug = 'eo-itda' WHERE id = 1342;
UPDATE kp_expressions SET slug = 'eo-juda' WHERE id = 1343;
UPDATE kp_expressions SET slug = 'eoyagetda' WHERE id = 1345;
UPDATE kp_expressions SET slug = 'eojida' WHERE id = 1346;
UPDATE kp_expressions SET slug = 'eureo-gada' WHERE id = 1348;
UPDATE kp_expressions SET slug = 'eumyeon-an-doeda' WHERE id = 1349;
UPDATE kp_expressions SET slug = 'eumyeonseo' WHERE id = 1350;
UPDATE kp_expressions SET slug = 'eusipsio' WHERE id = 1351;
UPDATE kp_expressions SET slug = 'eun-daeume' WHERE id = 1352;
UPDATE kp_expressions SET slug = 'eun-ji' WHERE id = 1353;
UPDATE kp_expressions SET slug = 'eun-hue' WHERE id = 1354;
UPDATE kp_expressions SET slug = 'eul-ttaemada' WHERE id = 1356;
UPDATE kp_expressions SET slug = 'eul-subakke-eopda' WHERE id = 1357;
UPDATE kp_expressions SET slug = 'eul-teni' WHERE id = 1358;
UPDATE kp_expressions SET slug = 'eul-tende' WHERE id = 1359;
UPDATE kp_expressions SET slug = 'eulgeol' WHERE id = 1360;
UPDATE kp_expressions SET slug = 'eulsurok' WHERE id = 1363;
UPDATE kp_expressions SET slug = 'eupsida' WHERE id = 1364;
UPDATE kp_expressions SET slug = 'jamaja' WHERE id = 1365;
UPDATE kp_expressions SET slug = 'kke' WHERE id = 1369;
UPDATE kp_expressions SET slug = 'kkeseo' WHERE id = 1370;
UPDATE kp_expressions SET slug = 'mada' WHERE id = 1371;
UPDATE kp_expressions SET slug = 'mankeum' WHERE id = 1373;
UPDATE kp_expressions SET slug = 'ppun' WHERE id = 1376;
UPDATE kp_expressions SET slug = 'eseobuteo' WHERE id = 1378;
UPDATE kp_expressions SET slug = 'inama' WHERE id = 1381;
UPDATE kp_expressions SET slug = 'iran' WHERE id = 1382;
UPDATE kp_expressions SET slug = 'keonyeong' WHERE id = 1385;
UPDATE kp_expressions SET slug = 'hanteseo' WHERE id = 1387;
UPDATE kp_expressions SET slug = 'eolmana-geollyeoyo' WHERE id = 1388;
UPDATE kp_expressions SET slug = 'kkok-bwaya-hal-ge-mwoyeyo' WHERE id = 1389;

-- [3] romaja + heading_en UPDATE (전체 325건)
UPDATE kp_expressions SET romaja = 'juseyo', heading_en = 'How to use 주세요 (juseyo) in Korean — "Give me ~, please"' WHERE id = 770;
UPDATE kp_expressions SET romaja = 'mwoyeyo', heading_en = 'How to use 뭐예요? (mwoyeyo) in Korean — "What is ~?"' WHERE id = 771;
UPDATE kp_expressions SET romaja = 'isseoyo', heading_en = 'How to use 있어요? (isseoyo) in Korean' WHERE id = 772;
UPDATE kp_expressions SET romaja = 'eotteoke gayo', heading_en = 'How to use 어떻게 가요? (eotteoke gayo) in Korean — "How do I get to ~?"' WHERE id = 773;
UPDATE kp_expressions SET romaja = 'gago sipeoyo', heading_en = 'How to use 가고 싶어요 (gago sipeoyo) in Korean — "I want to go to ~"' WHERE id = 774;
UPDATE kp_expressions SET romaja = 'eottaeyo', heading_en = 'How to use 어때요? (eottaeyo) in Korean — "How is ~?"' WHERE id = 775;
UPDATE kp_expressions SET romaja = 'ro halgeyo', heading_en = 'How to use 로 할게요 (ro halgeyo) in Korean — "I''ll have ~"' WHERE id = 776;
UPDATE kp_expressions SET romaja = 'hae bon jeok isseoyo', heading_en = 'How to use 해 본 적 있어요? (hae bon jeok isseoyo) in Korean — "Have you ever ~?"' WHERE id = 777;
UPDATE kp_expressions SET romaja = 'chucheonhae juseyo', heading_en = 'How to use 추천해 주세요 (chucheonhae juseyo) in Korean — "Please recommend ~"' WHERE id = 778;
UPDATE kp_expressions SET romaja = 'jusil su isseoyo', heading_en = 'How to use 주실 수 있어요? (jusil su isseoyo) in Korean — "Could you ~?"' WHERE id = 779;
UPDATE kp_expressions SET romaja = 'joahaeyo', heading_en = 'How to use 좋아해요 (joahaeyo) in Korean — "I like ~"' WHERE id = 780;
UPDATE kp_expressions SET romaja = 'singihaeyo', heading_en = 'How to say "That''s fascinating" in Korean — 신기해요 (singihaeyo)' WHERE id = 781;
UPDATE kp_expressions SET romaja = 'deo juseyo', heading_en = 'How to use 더 주세요 (deo juseyo) in Korean — "More ~, please"' WHERE id = 782;
UPDATE kp_expressions SET romaja = 'kkakka juseyo', heading_en = 'How to use 깎아 주세요 (kkakka juseyo) in Korean — "Could you lower the price?"' WHERE id = 783;
UPDATE kp_expressions SET romaja = 'sseobwasseoyo', heading_en = 'How to use 써봤어요? (sseobwasseoyo) in Korean — "Have you tried ~?"' WHERE id = 784;
UPDATE kp_expressions SET romaja = 'eotteon ge joayo', heading_en = 'How to use 어떤 게 좋아요? (eotteon ge joayo) in Korean — "Which ~ do you like?"' WHERE id = 785;
UPDATE kp_expressions SET romaja = 'saenggakboda haeyo', heading_en = 'How to say "It''s more ~ than I expected" in Korean — 생각보다 ~해요 (saenggakboda haeyo)' WHERE id = 786;
UPDATE kp_expressions SET romaja = 'da gachi isseoseo joayo', heading_en = 'How to say "I''m happy we''re all together" in Korean — 다 같이 있어서 좋아요 (da gachi isseoseo joayo)' WHERE id = 787;
UPDATE kp_expressions SET romaja = 'imi haeyo', heading_en = 'How to say "I already ~" in Korean — 이미 ~해요 (imi haeyo)' WHERE id = 788;
UPDATE kp_expressions SET romaja = 'tteollyeoyo', heading_en = 'How to say "I''m nervous" in Korean — 떨려요 (tteollyeoyo)' WHERE id = 789;
UPDATE kp_expressions SET romaja = 'eseo wasseoyo', heading_en = 'How to use 에서 왔어요 (eseo wasseoyo) in Korean — "I''m from ~"' WHERE id = 790;
UPDATE kp_expressions SET romaja = 'jal butakdeuryeoyo', heading_en = 'How to say "I look forward to it" in Korean — 잘 부탁드려요 (jal butakdeuryeoyo)' WHERE id = 791;
UPDATE kp_expressions SET romaja = 'eodiseo tayo', heading_en = 'How to use 어디서 타요? (eodiseo tayo) in Korean — "Where do I catch ~?"' WHERE id = 792;
UPDATE kp_expressions SET romaja = 'meokgo sipeoyo', heading_en = 'How to use 먹고 싶어요 (meokgo sipeoyo) in Korean — "I want to eat ~"' WHERE id = 793;
UPDATE kp_expressions SET romaja = 'mot meogeoyo', heading_en = 'How to use 못 먹어요 (mot meogeoyo) in Korean — "I can''t eat ~"' WHERE id = 794;
UPDATE kp_expressions SET romaja = 'meogeodo dwaeyo', heading_en = 'How to use 먹어도 돼요? (meogeodo dwaeyo) in Korean — "May I eat ~?"' WHERE id = 795;
UPDATE kp_expressions SET romaja = 'bulleodo dwaeyo', heading_en = 'How to use 불러도 돼요? (bulleodo dwaeyo) in Korean' WHERE id = 796;
UPDATE kp_expressions SET romaja = 'tto ogo sipeoyo', heading_en = 'How to say "I want to come here again" in Korean — 또 오고 싶어요 (tto ogo sipeoyo)' WHERE id = 797;
UPDATE kp_expressions SET romaja = 'tayo', heading_en = 'How to use 타요 (tayo) in Korean — "I''m taking the ~"' WHERE id = 798;
UPDATE kp_expressions SET romaja = 'eseo naeryeoyo', heading_en = 'How to use 에서 내려요 (eseo naeryeoyo) in Korean — "I get off at ~"' WHERE id = 799;
UPDATE kp_expressions SET romaja = 'kkaji ga juseyo', heading_en = 'How to use 까지 가 주세요 (kkaji ga juseyo) in Korean — "Please take me to ~"' WHERE id = 800;
UPDATE kp_expressions SET romaja = 'deol ge hae juseyo', heading_en = 'How to say "Please make it less ~" in Korean — 덜 ~게 해 주세요 (deol ge hae juseyo)' WHERE id = 801;
UPDATE kp_expressions SET romaja = 'ripil dwaeyo', heading_en = 'How to use 리필 돼요? (ripil dwaeyo) in Korean' WHERE id = 802;
UPDATE kp_expressions SET romaja = 'e mwo haeyo', heading_en = 'How to use 에 뭐 해요? (e mwo haeyo) in Korean — "What are you doing on ~?"' WHERE id = 803;
UPDATE kp_expressions SET romaja = 'gachi raeyo', heading_en = 'How to say "Shall we ~ together?" in Korean — 같이 ~ㄹ래요? (gachi raeyo)' WHERE id = 804;
UPDATE kp_expressions SET romaja = 'jogeum neujeul geot gatayo', heading_en = 'How to say "I think I''ll be a little late" in Korean — 조금 늦을 것 같아요 (jogeum neujeul geot gatayo)' WHERE id = 805;
UPDATE kp_expressions SET romaja = 'gireul ileosseoyo', heading_en = 'How to say "I''m lost" in Korean — 길을 잃었어요 (gireul ileosseoyo)' WHERE id = 806;
UPDATE kp_expressions SET romaja = 'jjuk gamyeon dwaeyo', heading_en = 'How to say "Just go straight" in Korean — 쭉 가면 돼요 (jjuk gamyeon dwaeyo)' WHERE id = 807;
UPDATE kp_expressions SET romaja = 'euro kkeokkeumyeon dwaeyo', heading_en = 'How to use 으로 꺾으면 돼요 (euro kkeokkeumyeon dwaeyo) in Korean — "Turn ~"' WHERE id = 808;
UPDATE kp_expressions SET romaja = 'bwasseoyo', heading_en = 'How to use 봤어요? (bwasseoyo) in Korean — "Have you tried ~?"' WHERE id = 809;
UPDATE kp_expressions SET romaja = 'jaemiisseoyo', heading_en = 'How to say "It''s fun" in Korean — 재미있어요 (jaemiisseoyo)' WHERE id = 810;
UPDATE kp_expressions SET romaja = 'gangchuyeyo', heading_en = 'How to say "I highly recommend it" in Korean — 강추예요 (gangchuyeyo)' WHERE id = 811;
UPDATE kp_expressions SET romaja = 'nalssi eottaeyo', heading_en = 'How to use 날씨 어때요? (nalssi eottaeyo) in Korean — "How''s the weather in ~?"' WHERE id = 812;
UPDATE kp_expressions SET romaja = 'ol geot gatayo', heading_en = 'How to use 올 것 같아요 (ol geot gatayo) in Korean — "It looks like ~ is coming"' WHERE id = 813;
UPDATE kp_expressions SET romaja = 'yak isseoyo', heading_en = 'How to use 약 있어요? (yak isseoyo) in Korean — "Do you have medicine for ~?"' WHERE id = 816;
UPDATE kp_expressions SET romaja = 'an meongneun ge naayo', heading_en = 'How to say "You''d better not eat it" in Korean — 안 먹는 게 나아요 (an meongneun ge naayo)' WHERE id = 817;
UPDATE kp_expressions SET romaja = 'chwimiga mwoyeyo', heading_en = 'How to say "What are your hobbies?" in Korean — 취미가 뭐예요? (chwimiga mwoyeyo)' WHERE id = 818;
UPDATE kp_expressions SET romaja = 'jeodoyo', heading_en = 'How to say "Me too" in Korean — 저도요 (jeodoyo)' WHERE id = 819;
UPDATE kp_expressions SET romaja = 'byeolloyeyo', heading_en = 'How to use 별로예요 (byeolloyeyo) in Korean — "It''s not that great"' WHERE id = 820;
UPDATE kp_expressions SET romaja = 'yeogiseo yumyeonghan ge mwoyeyo', heading_en = 'How to say "What''s this place famous for?" in Korean — 여기서 유명한 게 뭐예요? (yeogiseo yumyeonghan ge mwoyeyo)' WHERE id = 821;
UPDATE kp_expressions SET romaja = 'gachi sajin jjigeoyo', heading_en = 'How to say "Let''s take a photo together" in Korean — 같이 사진 찍어요 (gachi sajin jjigeoyo)' WHERE id = 822;
UPDATE kp_expressions SET romaja = 'sajini jal nawasseoyo', heading_en = 'How to say "Did the photo turn out well?" in Korean — 사진이 잘 나왔어요? (sajini jal nawasseoyo)' WHERE id = 823;
UPDATE kp_expressions SET romaja = 'oraenmanieyo', heading_en = 'How to say "Long time no see" in Korean — 오랜만이에요 (oraenmanieyo)' WHERE id = 824;
UPDATE kp_expressions SET romaja = 'jal jinaesseoyo', heading_en = 'How to say "How have you been?" in Korean — 잘 지냈어요? (jal jinaesseoyo)' WHERE id = 825;
UPDATE kp_expressions SET romaja = 'daeume tto bwayo', heading_en = 'How to say "See you again next time" in Korean — 다음에 또 봐요 (daeume tto bwayo)' WHERE id = 826;
UPDATE kp_expressions SET romaja = 'eottaesseo', heading_en = 'How to use 어땠어? (eottaesseo) in Korean — "How was ~?"' WHERE id = 828;
UPDATE kp_expressions SET romaja = 'cheoeumieonneunde', heading_en = 'How to say "It was my first time, but ~" in Korean — 처음이었는데 (cheoeumieonneunde)' WHERE id = 829;
UPDATE kp_expressions SET romaja = 'geot gatayo', heading_en = 'How to use 것 같아요 (geot gatayo) in Korean' WHERE id = 830;
UPDATE kp_expressions SET romaja = 'na bwayo', heading_en = 'How to use 나 봐요 (na bwayo) in Korean' WHERE id = 831;
UPDATE kp_expressions SET romaja = 'haeya hae', heading_en = 'How to use 해야 해 (haeya hae) in Korean' WHERE id = 833;
UPDATE kp_expressions SET romaja = 'haji ma', heading_en = 'How to use 하지 마 (haji ma) in Korean — "Don''t ~"' WHERE id = 834;
UPDATE kp_expressions SET romaja = 'itji ma', heading_en = 'How to use 잊지 마 (itji ma) in Korean — "Don''t forget ~"' WHERE id = 835;
UPDATE kp_expressions SET romaja = 'eotteoke saenggakaeyo', heading_en = 'How to use 어떻게 생각해요? (eotteoke saenggakaeyo) in Korean — "What do you think about ~?"' WHERE id = 836;
UPDATE kp_expressions SET romaja = 'manneun marieyo', heading_en = 'How to say "That''s a good point" in Korean — 맞는 말이에요 (manneun marieyo)' WHERE id = 837;
UPDATE kp_expressions SET romaja = 'jeoneun jom dallayo', heading_en = 'How to say "I''m a bit different" in Korean — 저는 좀 달라요 (jeoneun jom dallayo)' WHERE id = 838;
UPDATE kp_expressions SET romaja = 'e ga bwasseoyo', heading_en = 'How to use 에 가 봤어요? (e ga bwasseoyo) in Korean — "Have you been to ~?"' WHERE id = 839;
UPDATE kp_expressions SET romaja = 'kkok ga boseyo', heading_en = 'How to say "You should definitely go" in Korean — 꼭 가 보세요 (kkok ga boseyo)' WHERE id = 840;
UPDATE kp_expressions SET romaja = 'yojeum mwo bwayo', heading_en = 'How to say "What are you watching these days?" in Korean — 요즘 뭐 봐요? (yojeum mwo bwayo)' WHERE id = 842;
UPDATE kp_expressions SET romaja = 'wanjeon ppajyeodeureosseoyo', heading_en = 'How to say "I''m totally hooked" in Korean — 완전 빠져들었어요 (wanjeon ppajyeodeureosseoyo)' WHERE id = 843;
UPDATE kp_expressions SET romaja = 'daeum hwaga gidaedwaeyo', heading_en = 'How to say "I can''t wait for the next episode" in Korean — 다음 화가 기대돼요 (daeum hwaga gidaedwaeyo)' WHERE id = 844;
UPDATE kp_expressions SET romaja = 'i norae arayo', heading_en = 'How to say "Do you know this song?" in Korean — 이 노래 알아요? (i norae arayo)' WHERE id = 845;
UPDATE kp_expressions SET romaja = 'gasaga museun tteusieyo', heading_en = 'How to say "What do the lyrics mean?" in Korean — 가사가 무슨 뜻이에요? (gasaga museun tteusieyo)' WHERE id = 846;
UPDATE kp_expressions SET romaja = 'jungdokseong isseoyo', heading_en = 'How to say "It''s addictive" in Korean — 중독성 있어요 (jungdokseong isseoyo)' WHERE id = 847;
UPDATE kp_expressions SET romaja = 'gwalli eotteoke haeyo', heading_en = 'How to use 관리 어떻게 해요? (gwalli eotteoke haeyo) in Korean' WHERE id = 848;
UPDATE kp_expressions SET romaja = 'hyogwa isseoyo', heading_en = 'How to use 효과 있어요? (hyogwa isseoyo) in Korean — "Does ~ actually work?"' WHERE id = 849;
UPDATE kp_expressions SET romaja = 'hugiga joayo', heading_en = 'How to say "It has good reviews" in Korean — 후기가 좋아요 (hugiga joayo)' WHERE id = 850;
UPDATE kp_expressions SET romaja = 'eolmana jaju haeyo', heading_en = 'How to say "How often do you ~?" in Korean — 얼마나 자주 해요? (eolmana jaju haeyo)' WHERE id = 851;
UPDATE kp_expressions SET romaja = 'geongange joayo', heading_en = 'How to say "It''s good for your health" in Korean — 건강에 좋아요 (geongange joayo)' WHERE id = 852;
UPDATE kp_expressions SET romaja = 'kkujunhi hago isseoyo', heading_en = 'How to say "I''ve been keeping it up" in Korean — 꾸준히 하고 있어요 (kkujunhi hago isseoyo)' WHERE id = 853;
UPDATE kp_expressions SET romaja = 'eodi sarayo', heading_en = 'How to use 어디 살아요? (eodi sarayo) in Korean — "Where do you live?"' WHERE id = 854;
UPDATE kp_expressions SET romaja = 'honja sarayo', heading_en = 'How to say "Do you live alone?" in Korean — 혼자 살아요? (honja sarayo)' WHERE id = 855;
UPDATE kp_expressions SET romaja = 'geuncheoe mwo isseo', heading_en = 'How to use 근처에 뭐 있어? (geuncheoe mwo isseo) in Korean — "What''s near ~?"' WHERE id = 856;
UPDATE kp_expressions SET romaja = 'gibuni eottae', heading_en = 'How to say "How are you feeling today?" in Korean — 기분이 어때? (gibuni eottae)' WHERE id = 857;
UPDATE kp_expressions SET romaja = 'raseo haengbokae', heading_en = 'How to use 라서 행복해 (raseo haengbokae) in Korean — "Happy because of ~"' WHERE id = 858;
UPDATE kp_expressions SET romaja = 'seolle', heading_en = 'How to say "I''m so excited!" in Korean — 설레 (seolle)' WHERE id = 859;
UPDATE kp_expressions SET romaja = 'gwaenchanayo', heading_en = 'How to say "Are you okay?" in Korean — 괜찮아요? (gwaenchanayo)' WHERE id = 860;
UPDATE kp_expressions SET romaja = 'yojeum jom himdeureoyo', heading_en = 'How to say "Things have been a bit hard lately" in Korean — 요즘 좀 힘들어요 (yojeum jom himdeureoyo)' WHERE id = 861;
UPDATE kp_expressions SET romaja = 'eonjedeunji yeollakaeyo', heading_en = 'How to say "Contact me anytime" in Korean — 언제든지 연락해요 (eonjedeunji yeollakaeyo)' WHERE id = 862;
UPDATE kp_expressions SET romaja = 'kakaotok haeyo', heading_en = 'How to say "Do you use KakaoTalk?" in Korean — 카카오톡 해요? (kakaotok haeyo)' WHERE id = 863;
UPDATE kp_expressions SET romaja = 'pallouhaedo dwaeyo', heading_en = 'How to say "May I follow you?" in Korean — 팔로우해도 돼요? (pallouhaedo dwaeyo)' WHERE id = 864;
UPDATE kp_expressions SET romaja = 'jega salgeyo', heading_en = 'How to say "It''s on me" in Korean — 제가 살게요 (jega salgeyo)' WHERE id = 866;
UPDATE kp_expressions SET romaja = 'deochipei haeyo', heading_en = 'How to say "Shall we split the bill?" in Korean — 더치페이 해요? (deochipei haeyo)' WHERE id = 867;
UPDATE kp_expressions SET romaja = 'bap hanbeon meogeoyo', heading_en = 'How to say "Let''s grab a meal sometime" in Korean — 밥 한번 먹어요 (bap hanbeon meogeoyo)' WHERE id = 868;
UPDATE kp_expressions SET romaja = 'baedal sikyeoyo', heading_en = 'How to say "Let''s order delivery" in Korean — 배달 시켜요 (baedal sikyeoyo)' WHERE id = 869;
UPDATE kp_expressions SET romaja = 'ibeo bwasseo', heading_en = 'How to use 입어 봤어? (ibeo bwasseo) in Korean — "Have you tried this on?"' WHERE id = 870;
UPDATE kp_expressions SET romaja = 'myeongjeore mwo hae', heading_en = 'How to say "What do you do on holidays?" in Korean — 명절에 뭐 해? (myeongjeore mwo hae)' WHERE id = 871;
UPDATE kp_expressions SET romaja = 'ige museun tteusiya', heading_en = 'How to say "What does this mean?" in Korean — 이게 무슨 뜻이야? (ige museun tteusiya)' WHERE id = 872;
UPDATE kp_expressions SET romaja = 'sul masyeoyo', heading_en = 'How to say "Do you drink?" in Korean — 술 마셔요? (sul masyeoyo)' WHERE id = 873;
UPDATE kp_expressions SET romaja = 'geonbaehaeyo', heading_en = 'How to say "Cheers!" in Korean — 건배해요 (geonbaehaeyo)' WHERE id = 874;
UPDATE kp_expressions SET romaja = 'oneureun yeogikkajiman haeyo', heading_en = 'How to say "Let''s stop here for today" in Korean — 오늘은 여기까지만 해요 (oneureun yeogikkajiman haeyo)' WHERE id = 875;
UPDATE kp_expressions SET romaja = 'i norae gachi bulleoyo', heading_en = 'How to say "Let''s sing this song together!" in Korean — 이 노래 같이 불러요 (i norae gachi bulleoyo)' WHERE id = 876;
UPDATE kp_expressions SET romaja = 'sincheonggok isseoyo', heading_en = 'How to say "Any song requests?" in Korean — 신청곡 있어요? (sincheonggok isseoyo)' WHERE id = 877;
UPDATE kp_expressions SET romaja = 'han gok deo haeyo', heading_en = 'How to say "One more song" in Korean — 한 곡 더 해요 (han gok deo haeyo)' WHERE id = 878;
UPDATE kp_expressions SET romaja = 'gachi chwoyo', heading_en = 'How to say "Let''s dance together" in Korean — 같이 춰요 (gachi chwoyo)' WHERE id = 879;
UPDATE kp_expressions SET romaja = 'eoryeopjiman jaemiisseoyo', heading_en = 'How to say "It''s hard but fun" in Korean — 어렵지만 재미있어요 (eoryeopjiman jaemiisseoyo)' WHERE id = 880;
UPDATE kp_expressions SET romaja = 'hada bomyeon neureoyo', heading_en = 'How to say "You''ll improve as you go" in Korean — 하다 보면 늘어요 (hada bomyeon neureoyo)' WHERE id = 881;
UPDATE kp_expressions SET romaja = 'bunwigi joayo', heading_en = 'How to say "The atmosphere is nice" in Korean — 분위기 좋아요 (bunwigi joayo)' WHERE id = 882;
UPDATE kp_expressions SET romaja = 'daldalhan geo isseoyo', heading_en = 'How to say "Do you have anything sweet?" in Korean — 달달한 거 있어요? (daldalhan geo isseoyo)' WHERE id = 883;
UPDATE kp_expressions SET romaja = 'orae isseodo dwaeyo', heading_en = 'How to say "Is it okay to stay a long time?" in Korean — 오래 있어도 돼요? (orae isseodo dwaeyo)' WHERE id = 884;
UPDATE kp_expressions SET romaja = 'naramada dallayo', heading_en = 'How to say "It differs from country to country" in Korean — 나라마다 달라요 (naramada dallayo)' WHERE id = 885;
UPDATE kp_expressions SET romaja = 'ije jeogeungi dwaesseoyo', heading_en = 'How to say "I''ve gotten used to it now" in Korean — 이제 적응이 됐어요 (ije jeogeungi dwaesseoyo)' WHERE id = 886;
UPDATE kp_expressions SET romaja = 'cheoeumen natseoreonneunde', heading_en = 'How to say "It felt strange at first, but ~" in Korean — 처음엔 낯설었는데 (cheoeumen natseoreonneunde)' WHERE id = 887;
UPDATE kp_expressions SET romaja = 'neunde', heading_en = 'How to use 는데 (neunde) in Korean' WHERE id = 888;
UPDATE kp_expressions SET romaja = 'myeon eottaeyo', heading_en = 'How to use 면 어때요? (myeon eottaeyo) in Korean — "How about meeting ~?"' WHERE id = 891;
UPDATE kp_expressions SET romaja = 'myeon jokesseoyo', heading_en = 'How to use 면 좋겠어요 (myeon jokesseoyo) in Korean' WHERE id = 892;
UPDATE kp_expressions SET romaja = 'myeon dwaeyo', heading_en = 'How to use 면 돼요 (myeon dwaeyo) in Korean — "You can ~"' WHERE id = 893;
UPDATE kp_expressions SET romaja = 'ttaemune', heading_en = 'How to use 때문에 (ttaemune) in Korean' WHERE id = 894;
UPDATE kp_expressions SET romaja = 'deokbune', heading_en = 'How to use 덕분에 (deokbune) in Korean' WHERE id = 895;
UPDATE kp_expressions SET romaja = 'boda', heading_en = 'How to use 보다 (boda) in Korean — "than ~"' WHERE id = 896;
UPDATE kp_expressions SET romaja = 'neun dongan', heading_en = 'How to use 는 동안 (neun dongan) in Korean' WHERE id = 897;
UPDATE kp_expressions SET romaja = 'go naseo', heading_en = 'How to use 고 나서 (go naseo) in Korean' WHERE id = 898;
UPDATE kp_expressions SET romaja = 'gi jeone', heading_en = 'How to use 기 전에 (gi jeone) in Korean' WHERE id = 899;
UPDATE kp_expressions SET romaja = 'hae deurilkkayo', heading_en = 'How to say "Shall I do it for you?" in Korean — 해 드릴까요? (hae deurilkkayo)' WHERE id = 901;
UPDATE kp_expressions SET romaja = 'joesonghandeyo hoksi', heading_en = 'How to say "Excuse me, could you ~?" in Korean — 죄송한데요 혹시 ~ (joesonghandeyo hoksi)' WHERE id = 902;
UPDATE kp_expressions SET romaja = 'ji eolmana dwaesseoyo', heading_en = 'How to use 지 얼마나 됐어요? (ji eolmana dwaesseoyo) in Korean' WHERE id = 903;
UPDATE kp_expressions SET romaja = 'ajik neun jungieyo', heading_en = 'How to say "아직 ~" in Korean — 아직 ~는 중이에요 (ajik neun jungieyo)' WHERE id = 904;
UPDATE kp_expressions SET romaja = 'geoui da dwaesseoyo', heading_en = 'How to say "It''s almost done" in Korean — 거의 다 됐어요 (geoui da dwaesseoyo)' WHERE id = 905;
UPDATE kp_expressions SET romaja = 'seutail joahaeyo', heading_en = 'How to use 스타일 좋아해요? (seutail joahaeyo) in Korean — "What music style do you ~?"' WHERE id = 906;
UPDATE kp_expressions SET romaja = 'jal eoullyeoyo', heading_en = 'How to use 잘 어울려요 (jal eoullyeoyo) in Korean — "That outfit suits you really ~!"' WHERE id = 907;
UPDATE kp_expressions SET romaja = 'yojeum yuhaengieyo', heading_en = 'How to say "It''s trendy these days" in Korean — 요즘 유행이에요 (yojeum yuhaengieyo)' WHERE id = 908;
UPDATE kp_expressions SET romaja = 'baedal eolmana geollyeoyo', heading_en = 'How to say "How long does delivery take?" in Korean — 배달 얼마나 걸려요? (baedal eolmana geollyeoyo)' WHERE id = 909;
UPDATE kp_expressions SET romaja = 'gaseongbi joayo', heading_en = 'How to say "This restaurant is great value" in Korean — 가성비 좋아요 (gaseongbi joayo)' WHERE id = 910;
UPDATE kp_expressions SET romaja = 'yeohaeng gyehoek isseoyo', heading_en = 'How to say "Do you have any travel plans?" in Korean — 여행 계획 있어요? (yeohaeng gyehoek isseoyo)' WHERE id = 911;
UPDATE kp_expressions SET romaja = 'myeochirina isseul geoyeyo', heading_en = 'How to say "How many days will you stay?" in Korean — 며칠이나 있을 거예요? (myeochirina isseul geoyeyo)' WHERE id = 912;
UPDATE kp_expressions SET romaja = 'hanguk saenghwal eottae', heading_en = 'How to say "How''s life in Korea?" in Korean — 한국 생활 어때? (hanguk saenghwal eottae)' WHERE id = 914;
UPDATE kp_expressions SET romaja = 'ije iksukaejyeosseo', heading_en = 'How to say "I''m used to it now" in Korean — 이제 익숙해졌어 (ije iksukaejyeosseo)' WHERE id = 915;
UPDATE kp_expressions SET romaja = 'ryeogo haeyo', heading_en = 'How to use 려고 해요 (ryeogo haeyo) in Korean' WHERE id = 918;
UPDATE kp_expressions SET romaja = 'go sipeoyo', heading_en = 'How to use 고 싶어요 (go sipeoyo) in Korean — "I want to ~"' WHERE id = 919;
UPDATE kp_expressions SET romaja = 'giro haesseoyo', heading_en = 'How to use 기로 했어요 (giro haesseoyo) in Korean — "I''ve decided to live in ~"' WHERE id = 920;
UPDATE kp_expressions SET romaja = 'maeummeogeosseoyo', heading_en = 'How to say "I''ve made up my mind" in Korean — 마음먹었어요 (maeummeogeosseoyo)' WHERE id = 921;
UPDATE kp_expressions SET romaja = 'yejeonboda neureosseoyo', heading_en = 'How to say "I''ve improved compared to before" in Korean — 예전보다 늘었어요 (yejeonboda neureosseoyo)' WHERE id = 922;
UPDATE kp_expressions SET romaja = 'bonikka', heading_en = 'How to use 보니까 (bonikka) in Korean' WHERE id = 924;
UPDATE kp_expressions SET romaja = 'chucheonhaejwosseo', heading_en = 'How to use 추천해줬어 (chucheonhaejwosseo) in Korean' WHERE id = 925;
UPDATE kp_expressions SET romaja = 'maja', heading_en = 'How to use 맞아? (maja) in Korean — "This is Hongdae station, ~?"' WHERE id = 927;
UPDATE kp_expressions SET romaja = 'mandeureobwasseo', heading_en = 'How to use 만들어봤어? (mandeureobwasseo) in Korean' WHERE id = 929;
UPDATE kp_expressions SET romaja = 'eolmana neoeo', heading_en = 'How to use 얼마나 넣어? (eolmana neoeo) in Korean' WHERE id = 930;
UPDATE kp_expressions SET romaja = 'hamyeon dwae', heading_en = 'How to use 하면 돼 (hamyeon dwae) in Korean — "Just press this button. It''s ~"' WHERE id = 931;
UPDATE kp_expressions SET romaja = 'sal geoyeyo', heading_en = 'How to use 살 거예요 (sal geoyeyo) in Korean' WHERE id = 932;
UPDATE kp_expressions SET romaja = 'igeo eottaeyo', heading_en = 'How to say "How about this one?" in Korean — 이거 어때요? (igeo eottaeyo)' WHERE id = 933;
UPDATE kp_expressions SET romaja = 'kadeuro halgeyo', heading_en = 'How to say "I''ll pay by card" in Korean — 카드로 할게요 (kadeuro halgeyo)' WHERE id = 934;
UPDATE kp_expressions SET romaja = 'batgo sipeoyo', heading_en = 'How to use 받고 싶어요 (batgo sipeoyo) in Korean' WHERE id = 937;
UPDATE kp_expressions SET romaja = 'eodiga apayo', heading_en = 'How to say "Where does it hurt?" in Korean — 어디가 아파요? (eodiga apayo)' WHERE id = 938;
UPDATE kp_expressions SET romaja = 'eonjebuteo apasseoyo', heading_en = 'How to say "Since when has it been hurting?" in Korean — 언제부터 아팠어요? (eonjebuteo apasseoyo)' WHERE id = 939;
UPDATE kp_expressions SET romaja = 'wa bwasseoyo', heading_en = 'How to use 와 봤어요? (wa bwasseoyo) in Korean' WHERE id = 940;
UPDATE kp_expressions SET romaja = 'hagi joayo', heading_en = 'How to use 하기 좋아요 (hagi joayo) in Korean' WHERE id = 941;
UPDATE kp_expressions SET romaja = 'junge mwoga jeil joayo', heading_en = 'How to use 중에 뭐가 제일 좋아요? (junge mwoga jeil joayo) in Korean — "What''s your favorite among Korean ~?"' WHERE id = 942;
UPDATE kp_expressions SET romaja = 'raseo jungdokseong isseoyo', heading_en = 'How to use 라서 중독성 있어요 (raseo jungdokseong isseoyo) in Korean' WHERE id = 943;
UPDATE kp_expressions SET romaja = 'irang dallayo', heading_en = 'How to use 이랑 달라요 (irang dallayo) in Korean' WHERE id = 944;
UPDATE kp_expressions SET romaja = 'eungeunhi hae', heading_en = 'How to say "은근히 ~" in Korean — 은근히 ~해 (eungeunhi hae)' WHERE id = 947;
UPDATE kp_expressions SET romaja = 'ttaemune bappayo', heading_en = 'How to use 때문에 바빠요 (ttaemune bappayo) in Korean' WHERE id = 948;
UPDATE kp_expressions SET romaja = 'murihaji maseyo', heading_en = 'How to say "Don''t push yourself too hard" in Korean — 무리하지 마세요 (murihaji maseyo)' WHERE id = 949;
UPDATE kp_expressions SET romaja = 'mani hae', heading_en = 'How to use 많이 해? (mani hae) in Korean' WHERE id = 950;
UPDATE kp_expressions SET romaja = 'yuhaengiya', heading_en = 'How to use 유행이야? (yuhaengiya) in Korean — "Is this style trendy these ~?"' WHERE id = 951;
UPDATE kp_expressions SET romaja = 'ollyeotdeoni', heading_en = 'How to use 올렸더니 (ollyeotdeoni) in Korean' WHERE id = 952;
UPDATE kp_expressions SET romaja = 'dojeonhaeyo', heading_en = 'How to use 도전해요 (dojeonhaeyo) in Korean' WHERE id = 953;
UPDATE kp_expressions SET romaja = 'jaeryoga isseoyo', heading_en = 'How to say "Do you have the ingredients?" in Korean — 재료가 있어요? (jaeryoga isseoyo)' WHERE id = 954;
UPDATE kp_expressions SET romaja = 'daeumen deo jalhal geoyeyo', heading_en = 'How to say "I''ll do better next time" in Korean — 다음엔 더 잘할 거예요 (daeumen deo jalhal geoyeyo)' WHERE id = 955;
UPDATE kp_expressions SET romaja = 'rutin isseoyo', heading_en = 'How to use 루틴 있어요? (rutin isseoyo) in Korean' WHERE id = 956;
UPDATE kp_expressions SET romaja = 'hago naseo', heading_en = 'How to use 하고 나서 (hago naseo) in Korean — "Let''s take a walk after ~"' WHERE id = 957;
UPDATE kp_expressions SET romaja = 'kkok haeya haeyo', heading_en = 'How to say "꼭 ~" in Korean — 꼭 ~해야 해요 (kkok haeya haeyo)' WHERE id = 958;
UPDATE kp_expressions SET romaja = 'mani neureosseoyo', heading_en = 'How to say "You''ve improved a lot" in Korean — 많이 늘었어요 (mani neureosseoyo)' WHERE id = 959;
UPDATE kp_expressions SET romaja = 'bigyeori mwoyeyo', heading_en = 'How to say "What''s your secret?" in Korean — 비결이 뭐예요? (bigyeori mwoyeyo)' WHERE id = 960;
UPDATE kp_expressions SET romaja = 'i hetgallyeoyo', heading_en = 'How to use 이 헷갈려요 (i hetgallyeoyo) in Korean' WHERE id = 961;
UPDATE kp_expressions SET romaja = 'seounhaesseoyo', heading_en = 'How to say "I felt hurt" in Korean — 서운했어요 (seounhaesseoyo)' WHERE id = 965;
UPDATE kp_expressions SET romaja = 'maeumeun arayo', heading_en = 'How to say "I understand how you feel" in Korean — 마음은 알아요 (maeumeun arayo)' WHERE id = 966;
UPDATE kp_expressions SET romaja = 'malhago nanikka huryeonhaeyo', heading_en = 'How to say "I feel relieved now that I''ve said it" in Korean — 말하고 나니까 후련해요 (malhago nanikka huryeonhaeyo)' WHERE id = 967;
UPDATE kp_expressions SET romaja = 'kkumi mwoyeyo', heading_en = 'How to say "What''s your dream?" in Korean — 꿈이 뭐예요? (kkumi mwoyeyo)' WHERE id = 968;
UPDATE kp_expressions SET romaja = 'ga doego sipeoyo', heading_en = 'How to use 가 되고 싶어요 (ga doego sipeoyo) in Korean' WHERE id = 969;
UPDATE kp_expressions SET romaja = 'pogihago sipeoyo', heading_en = 'How to say "I want to give up" in Korean — 포기하고 싶어요 (pogihago sipeoyo)' WHERE id = 970;
UPDATE kp_expressions SET romaja = 'mallo pyohyeonhagi eoryeowoyo', heading_en = 'How to say "It''s hard to put into words" in Korean — 말로 표현하기 어려워요 (mallo pyohyeonhagi eoryeowoyo)' WHERE id = 974;
UPDATE kp_expressions SET romaja = 'i neukkim arayo', heading_en = 'How to say "Do you know this feeling?" in Korean — 이 느낌 알아요? (i neukkim arayo)' WHERE id = 975;
UPDATE kp_expressions SET romaja = 'waenji moreuge haeyo', heading_en = 'How to say "왠지 모르게 ~" in Korean — 왠지 모르게 ~해요 (waenji moreuge haeyo)' WHERE id = 976;
UPDATE kp_expressions SET romaja = 'ttak i neukkimieyo', heading_en = 'How to say "This is exactly the feeling" in Korean — 딱 이 느낌이에요 (ttak i neukkimieyo)' WHERE id = 977;
UPDATE kp_expressions SET romaja = 'hapgyeokaesseoyo', heading_en = 'How to say "I passed" in Korean — 합격했어요 (hapgyeokaesseoyo)' WHERE id = 981;
UPDATE kp_expressions SET romaja = 'deudieo haenaesseoyo', heading_en = 'How to say "I finally did it" in Korean — 드디어 해냈어요 (deudieo haenaesseoyo)' WHERE id = 982;
UPDATE kp_expressions SET romaja = 'meogeobwa', heading_en = 'How to use 먹어봐 (meogeobwa) in Korean — "Try this. It''s really ~"' WHERE id = 984;
UPDATE kp_expressions SET romaja = 'saenggakboda hwolssin hae', heading_en = 'How to say "생각보다 훨씬 ~" in Korean — 생각보다 훨씬 ~해 (saenggakboda hwolssin hae)' WHERE id = 985;
UPDATE kp_expressions SET romaja = 'jungdokseong isseo', heading_en = 'How to say "It''s addictive" in Korean — 중독성 있어 (jungdokseong isseo)' WHERE id = 986;
UPDATE kp_expressions SET romaja = 'haengbokaeyo', heading_en = 'How to say "I''m happy" in Korean — 행복해요 (haengbokaeyo)' WHERE id = 987;
UPDATE kp_expressions SET romaja = 'haneun ge joayo', heading_en = 'How to use 하는 게 좋아요 (haneun ge joayo) in Korean — "I like listening to ~"' WHERE id = 988;
UPDATE kp_expressions SET romaja = 'ireon ilsangi sojunghaeyo', heading_en = 'How to say "These ordinary days are precious" in Korean — 이런 일상이 소중해요 (ireon ilsangi sojunghaeyo)' WHERE id = 989;
UPDATE kp_expressions SET romaja = 'da gachi moinikka joayo', heading_en = 'How to say "It''s great having everyone together" in Korean — 다 같이 모이니까 좋아요 (da gachi moinikka joayo)' WHERE id = 992;
UPDATE kp_expressions SET romaja = 'cheoeum mannasseul ttae', heading_en = 'How to say "when we first met" in Korean — 처음 만났을 때 (cheoeum mannasseul ttae)' WHERE id = 993;
UPDATE kp_expressions SET romaja = 'yeoreobun deokbunieyo', heading_en = 'How to say "It''s all thanks to you" in Korean — 여러분 덕분이에요 (yeoreobun deokbunieyo)' WHERE id = 994;
UPDATE kp_expressions SET romaja = 'apeurodo jal butakaeyo', heading_en = 'How to say "Please keep looking out for me" in Korean — 앞으로도 잘 부탁해요 (apeurodo jal butakaeyo)' WHERE id = 995;
UPDATE kp_expressions SET romaja = 'eolmana isseul geoyeyo', heading_en = 'How to say "How long will you stay?" in Korean — 얼마나 있을 거예요? (eolmana isseul geoyeyo)' WHERE id = 996;
UPDATE kp_expressions SET romaja = 'jul seoya haeyo', heading_en = 'How to say "You have to wait in line" in Korean — 줄 서야 해요 (jul seoya haeyo)' WHERE id = 998;
UPDATE kp_expressions SET romaja = 'ge dwaesseoyo', heading_en = 'How to use 게 됐어요 (ge dwaesseoyo) in Korean — "I ended up living in ~"' WHERE id = 1007;
UPDATE kp_expressions SET romaja = 'da bonikka', heading_en = 'How to use 다 보니까 (da bonikka) in Korean' WHERE id = 1008;
UPDATE kp_expressions SET romaja = 'hada bomyeon', heading_en = 'How to use 하다 보면 (hada bomyeon) in Korean' WHERE id = 1009;
UPDATE kp_expressions SET romaja = 'han geotchigoneun', heading_en = 'How to use 한 것치고는 (han geotchigoneun) in Korean' WHERE id = 1010;
UPDATE kp_expressions SET romaja = 'amuri geuraedo', heading_en = 'How to say "Even so, ~" in Korean — 아무리 그래도 (amuri geuraedo)' WHERE id = 1011;
UPDATE kp_expressions SET romaja = 'jal moreugenneundeyo', heading_en = 'How to say "I''m not really sure" in Korean — 잘 모르겠는데요 (jal moreugenneundeyo)' WHERE id = 1012;
UPDATE kp_expressions SET romaja = 'jom deo saenggakae bwayagesseoyo', heading_en = 'How to say "I can''t decide right now" in Korean — 좀 더 생각해 봐야겠어요 (jom deo saenggakae bwayagesseoyo)' WHERE id = 1013;
UPDATE kp_expressions SET romaja = 'ildaneun haeyo', heading_en = 'How to say "일단은 ~" in Korean — 일단은 ~해요 (ildaneun haeyo)' WHERE id = 1014;
UPDATE kp_expressions SET romaja = 'nunchichaesseoyo', heading_en = 'How to say "Did you notice?" in Korean — 눈치챘어요? (nunchichaesseoyo)' WHERE id = 1015;
UPDATE kp_expressions SET romaja = 'gami japyeoyo', heading_en = 'How to say "I''m getting the hang of it" in Korean — 감이 잡혀요 (gami japyeoyo)' WHERE id = 1016;
UPDATE kp_expressions SET romaja = 'ttak bwado algesseoyo', heading_en = 'How to say "I can tell just by looking" in Korean — 딱 봐도 알겠어요 (ttak bwado algesseoyo)' WHERE id = 1017;
UPDATE kp_expressions SET romaja = 'budamseureowoyo', heading_en = 'How to say "It feels like a burden" in Korean — 부담스러워요 (budamseureowoyo)' WHERE id = 1020;
UPDATE kp_expressions SET romaja = 'soljikage malhaedo dwaeyo', heading_en = 'How to say "Can I be honest?" in Korean — 솔직하게 말해도 돼요? (soljikage malhaedo dwaeyo)' WHERE id = 1021;
UPDATE kp_expressions SET romaja = 'ije mani pyeonhaejyeosseoyo', heading_en = 'How to say "I''ve gotten much more comfortable now" in Korean — 이제 많이 편해졌어요 (ije mani pyeonhaejyeosseoyo)' WHERE id = 1022;
UPDATE kp_expressions SET romaja = 'oegugin ti nayo', heading_en = 'How to say "Can you tell I''m a foreigner?" in Korean — 외국인 티 나요? (oegugin ti nayo)' WHERE id = 1023;
UPDATE kp_expressions SET romaja = 'ije hangungmari pyeonhaeyo', heading_en = 'How to say "Korean feels comfortable now" in Korean — 이제 한국말이 편해요 (ije hangungmari pyeonhaeyo)' WHERE id = 1024;
UPDATE kp_expressions SET romaja = 'hangugeoro kkumdo kkwoyo', heading_en = 'How to say "I even dream in Korean" in Korean — 한국어로 꿈도 꿔요 (hangugeoro kkumdo kkwoyo)' WHERE id = 1025;
UPDATE kp_expressions SET romaja = 'gwangwangjiboda rokeori joa', heading_en = 'How to say "I prefer local spots to tourist spots" in Korean — 관광지보다 로컬이 좋아 (gwangwangjiboda rokeori joa)' WHERE id = 1026;
UPDATE kp_expressions SET romaja = 'hyeonjiindeuri ganeun gosiya', heading_en = 'How to say "It''s a place locals go" in Korean — 현지인들이 가는 곳이야 (hyeonjiindeuri ganeun gosiya)' WHERE id = 1027;
UPDATE kp_expressions SET romaja = 'sumgyeojin myeongsoya', heading_en = 'How to say "It''s a hidden gem" in Korean — 숨겨진 명소야 (sumgyeojin myeongsoya)' WHERE id = 1028;
UPDATE kp_expressions SET romaja = 'yojeum hataeyo', heading_en = 'How to say "It''s hot right now" in Korean — 요즘 핫해요 (yojeum hataeyo)' WHERE id = 1029;
UPDATE kp_expressions SET romaja = 'wanjeon daeseyeyo', heading_en = 'How to say "It''s totally the trend" in Korean — 완전 대세예요 (wanjeon daeseyeyo)' WHERE id = 1030;
UPDATE kp_expressions SET romaja = 'tteooreuneun jungieyo', heading_en = 'How to say "It''s on the rise" in Korean — 떠오르는 중이에요 (tteooreuneun jungieyo)' WHERE id = 1031;
UPDATE kp_expressions SET romaja = 'mari doeneyo', heading_en = 'How to say "That makes sense" in Korean — 말이 되네요 (mari doeneyo)' WHERE id = 1034;
UPDATE kp_expressions SET romaja = 'apdwiga an majayo', heading_en = 'How to say "It doesn''t add up" in Korean — 앞뒤가 안 맞아요 (apdwiga an majayo)' WHERE id = 1035;
UPDATE kp_expressions SET romaja = 'gyeolgugen', heading_en = 'How to say "In the end, ~" in Korean — 결국엔 ~ (gyeolgugen)' WHERE id = 1036;
UPDATE kp_expressions SET romaja = 'soksanghaesseoyo', heading_en = 'How to say "I was upset" in Korean — 속상했어요 (soksanghaesseoyo)' WHERE id = 1037;
UPDATE kp_expressions SET romaja = 'eogulhaesseoyo', heading_en = 'How to say "It felt unfair" in Korean — 억울했어요 (eogulhaesseoyo)' WHERE id = 1038;
UPDATE kp_expressions SET romaja = 'banjeon isseoyo', heading_en = 'How to say "This movie has a twist" in Korean — 반전 있어요 (banjeon isseoyo)' WHERE id = 1042;
UPDATE kp_expressions SET romaja = 'yeouni namayo', heading_en = 'How to say "The feeling lingers" in Korean — 여운이 남아요 (yeouni namayo)' WHERE id = 1043;
UPDATE kp_expressions SET romaja = 'moribi dwaeyo', heading_en = 'How to say "I get completely absorbed" in Korean — 몰입이 돼요 (moribi dwaeyo)' WHERE id = 1044;
UPDATE kp_expressions SET romaja = 'tteonagi sileo', heading_en = 'How to say "I don''t want to leave" in Korean — 떠나기 싫어 (tteonagi sileo)' WHERE id = 1046;
UPDATE kp_expressions SET romaja = 'i geuriul geot gata', heading_en = 'How to use 이 그리울 것 같아 (i geuriul geot gata) in Korean — "I think I''ll miss Korean ~"' WHERE id = 1047;
UPDATE kp_expressions SET romaja = 'kkok dasi olge', heading_en = 'How to say "I''ll definitely come back" in Korean — 꼭 다시 올게 (kkok dasi olge)' WHERE id = 1048;
UPDATE kp_expressions SET romaja = 'ije hangugeoro saenggakaeyo', heading_en = 'How to say "I think in Korean now" in Korean — 이제 한국어로 생각해요 (ije hangugeoro saenggakaeyo)' WHERE id = 1049;
UPDATE kp_expressions SET romaja = 'beonyeok an haedo ihaedwaeyo', heading_en = 'How to say "I understand without translating" in Korean — 번역 안 해도 이해돼요 (beonyeok an haedo ihaedwaeyo)' WHERE id = 1050;
UPDATE kp_expressions SET romaja = 'sillyeogi mani neureosseoyo', heading_en = 'How to say "My skills have improved a lot" in Korean — 실력이 많이 늘었어요 (sillyeogi mani neureosseoyo)' WHERE id = 1051;
UPDATE kp_expressions SET romaja = 'gachi seongjanghan geot gatayo', heading_en = 'How to say "I think we grew together" in Korean — 같이 성장한 것 같아요 (gachi seongjanghan geot gatayo)' WHERE id = 1052;
UPDATE kp_expressions SET romaja = 'deokbune jeongmal mani baewosseoyo', heading_en = 'How to say "I learned so much thanks to you" in Korean — 덕분에 정말 많이 배웠어요 (deokbune jeongmal mani baewosseoyo)' WHERE id = 1053;
UPDATE kp_expressions SET romaja = 'geona', heading_en = 'What does -거나 (geona) mean in Korean?' WHERE id = 1301;
UPDATE kp_expressions SET romaja = 'geodeun', heading_en = 'What does -거든 (geodeun) mean in Korean?' WHERE id = 1302;
UPDATE kp_expressions SET romaja = 'ge doeda', heading_en = 'What does -게 되다 (ge doeda) mean in Korean?' WHERE id = 1303;
UPDATE kp_expressions SET romaja = 'get', heading_en = 'What does -겠- (get) mean in Korean?' WHERE id = 1304;
UPDATE kp_expressions SET romaja = 'go malda', heading_en = 'What does -고 말다 (go malda) mean in Korean?' WHERE id = 1305;
UPDATE kp_expressions SET romaja = 'goseo', heading_en = 'What does -고서 (goseo) mean in Korean?' WHERE id = 1306;
UPDATE kp_expressions SET romaja = 'gi wihae', heading_en = 'What does -기 위해 (gi wihae) mean in Korean?' WHERE id = 1307;
UPDATE kp_expressions SET romaja = 'giro hada', heading_en = 'What does -기로 하다 (giro hada) mean in Korean?' WHERE id = 1308;
UPDATE kp_expressions SET romaja = 'gie', heading_en = 'What does -기에 (gie) mean in Korean?' WHERE id = 1309;
UPDATE kp_expressions SET romaja = 'na boda', heading_en = 'What does -나 보다 (na boda) mean in Korean?' WHERE id = 1310;
UPDATE kp_expressions SET romaja = 'na sipda', heading_en = 'What does -나 싶다 (na sipda) mean in Korean?' WHERE id = 1311;
UPDATE kp_expressions SET romaja = 'neurago', heading_en = 'What does -느라고 (neurago) mean in Korean?' WHERE id = 1312;
UPDATE kp_expressions SET romaja = 'neun geot gatgido', heading_en = 'What does -는 것 같기도 (neun geot gatgido) mean in Korean?' WHERE id = 1313;
UPDATE kp_expressions SET romaja = 'neun ge anira', heading_en = 'What does -는 게 아니라 (neun ge anira) mean in Korean?' WHERE id = 1314;
UPDATE kp_expressions SET romaja = 'neun gime', heading_en = 'What does -는 김에 (neun gime) mean in Korean?' WHERE id = 1315;
UPDATE kp_expressions SET romaja = 'neun daero', heading_en = 'What does -는 대로 (neun daero) mean in Korean?' WHERE id = 1316;
UPDATE kp_expressions SET romaja = 'neun daesine', heading_en = 'What does -는 대신에 (neun daesine) mean in Korean?' WHERE id = 1317;
UPDATE kp_expressions SET romaja = 'neun barame', heading_en = 'What does -는 바람에 (neun barame) mean in Korean?' WHERE id = 1318;
UPDATE kp_expressions SET romaja = 'neun jul aratda', heading_en = 'What does -는 줄 알았다 (neun jul aratda) mean in Korean?' WHERE id = 1319;
UPDATE kp_expressions SET romaja = 'neun pyeonida', heading_en = 'What does -는 편이다 (neun pyeonida) mean in Korean?' WHERE id = 1320;
UPDATE kp_expressions SET romaja = 'neundago', heading_en = 'What does -는다고 (neundago) mean in Korean?' WHERE id = 1321;
UPDATE kp_expressions SET romaja = 'neundamyeonseo', heading_en = 'What does -는다면서? (neundamyeonseo) mean in Korean?' WHERE id = 1322;
UPDATE kp_expressions SET romaja = 'neunji', heading_en = 'What does -는지 (neunji) mean in Korean?' WHERE id = 1323;
UPDATE kp_expressions SET romaja = 'ni', heading_en = 'What does -니? (ni) mean in Korean?' WHERE id = 1324;
UPDATE kp_expressions SET romaja = 'dasipi', heading_en = 'What does -다시피 (dasipi) mean in Korean?' WHERE id = 1325;
UPDATE kp_expressions SET romaja = 'deogun', heading_en = 'What does -더군 (deogun) mean in Korean?' WHERE id = 1326;
UPDATE kp_expressions SET romaja = 'deora', heading_en = 'What does -더라 (deora) mean in Korean?' WHERE id = 1327;
UPDATE kp_expressions SET romaja = 'deorado', heading_en = 'What does -더라도 (deorado) mean in Korean?' WHERE id = 1328;
UPDATE kp_expressions SET romaja = 'deon', heading_en = 'What does -던 (deon) mean in Korean?' WHERE id = 1329;
UPDATE kp_expressions SET romaja = 'deonde', heading_en = 'What does -던데 (deonde) mean in Korean?' WHERE id = 1330;
UPDATE kp_expressions SET romaja = 'dorok', heading_en = 'What does -도록 (dorok) mean in Korean?' WHERE id = 1331;
UPDATE kp_expressions SET romaja = 'seumnikka', heading_en = 'What does -습니까? (seumnikka) mean in Korean?' WHERE id = 1332;
UPDATE kp_expressions SET romaja = 'seumnida', heading_en = 'What does -습니다 (seumnida) mean in Korean?' WHERE id = 1333;
UPDATE kp_expressions SET romaja = 'at eot', heading_en = 'What does -았/었- (at eot) mean in Korean?' WHERE id = 1334;
UPDATE kp_expressions SET romaja = 'eo gada', heading_en = 'What does -어 가다 (eo gada) mean in Korean?' WHERE id = 1335;
UPDATE kp_expressions SET romaja = 'eo nota', heading_en = 'What does -어 놓다 (eo nota) mean in Korean?' WHERE id = 1336;
UPDATE kp_expressions SET romaja = 'eo duda', heading_en = 'What does -어 두다 (eo duda) mean in Korean?' WHERE id = 1337;
UPDATE kp_expressions SET romaja = 'eo deurida', heading_en = 'What does -어 드리다 (eo deurida) mean in Korean?' WHERE id = 1338;
UPDATE kp_expressions SET romaja = 'eo beorida', heading_en = 'What does -어 버리다 (eo beorida) mean in Korean?' WHERE id = 1339;
UPDATE kp_expressions SET romaja = 'eo boda', heading_en = 'What does -어 보다 (eo boda) mean in Korean?' WHERE id = 1340;
UPDATE kp_expressions SET romaja = 'eo oda', heading_en = 'What does -어 오다 (eo oda) mean in Korean?' WHERE id = 1341;
UPDATE kp_expressions SET romaja = 'eo itda', heading_en = 'What does -어 있다 (eo itda) mean in Korean?' WHERE id = 1342;
UPDATE kp_expressions SET romaja = 'eo juda', heading_en = 'What does -어 주다 (eo juda) mean in Korean?' WHERE id = 1343;
UPDATE kp_expressions SET romaja = 'eoseo', heading_en = 'What does -어서 (eoseo) mean in Korean?' WHERE id = 1344;
UPDATE kp_expressions SET romaja = 'eoyagetda', heading_en = 'What does -어야겠다 (eoyagetda) mean in Korean?' WHERE id = 1345;
UPDATE kp_expressions SET romaja = 'eojida', heading_en = 'What does -어지다 (eojida) mean in Korean?' WHERE id = 1346;
UPDATE kp_expressions SET romaja = 'eunikka', heading_en = 'What does -으니까 (eunikka) mean in Korean?' WHERE id = 1347;
UPDATE kp_expressions SET romaja = 'eureo gada', heading_en = 'What does -으러 가다 (eureo gada) mean in Korean?' WHERE id = 1348;
UPDATE kp_expressions SET romaja = 'eumyeon an doeda', heading_en = 'What does -으면 안 되다 (eumyeon an doeda) mean in Korean?' WHERE id = 1349;
UPDATE kp_expressions SET romaja = 'eumyeonseo', heading_en = 'What does -으면서 (eumyeonseo) mean in Korean?' WHERE id = 1350;
UPDATE kp_expressions SET romaja = 'eusipsio', heading_en = 'What does -으십시오 (eusipsio) mean in Korean?' WHERE id = 1351;
UPDATE kp_expressions SET romaja = 'eun daeume', heading_en = 'What does -은 다음에 (eun daeume) mean in Korean?' WHERE id = 1352;
UPDATE kp_expressions SET romaja = 'eun ji', heading_en = 'What does -은 지 (eun ji) mean in Korean?' WHERE id = 1353;
UPDATE kp_expressions SET romaja = 'eun hue', heading_en = 'What does -은 후에 (eun hue) mean in Korean?' WHERE id = 1354;
UPDATE kp_expressions SET romaja = 'eul geoyeyo', heading_en = 'What does -을 거예요 (eul geoyeyo) mean in Korean?' WHERE id = 1355;
UPDATE kp_expressions SET romaja = 'eul ttaemada', heading_en = 'What does -을 때마다 (eul ttaemada) mean in Korean?' WHERE id = 1356;
UPDATE kp_expressions SET romaja = 'eul subakke eopda', heading_en = 'What does -을 수밖에 없다 (eul subakke eopda) mean in Korean?' WHERE id = 1357;
UPDATE kp_expressions SET romaja = 'eul teni', heading_en = 'What does -을 테니 (eul teni) mean in Korean?' WHERE id = 1358;
UPDATE kp_expressions SET romaja = 'eul tende', heading_en = 'What does -을 텐데 (eul tende) mean in Korean?' WHERE id = 1359;
UPDATE kp_expressions SET romaja = 'eulgeol', heading_en = 'What does -을걸 (eulgeol) mean in Korean?' WHERE id = 1360;
UPDATE kp_expressions SET romaja = 'eulge', heading_en = 'What does -을게 (eulge) mean in Korean?' WHERE id = 1361;
UPDATE kp_expressions SET romaja = 'eulkkayo', heading_en = 'What does -을까요? (eulkkayo) mean in Korean?' WHERE id = 1362;
UPDATE kp_expressions SET romaja = 'eulsurok', heading_en = 'What does -을수록 (eulsurok) mean in Korean?' WHERE id = 1363;
UPDATE kp_expressions SET romaja = 'eupsida', heading_en = 'What does -읍시다 (eupsida) mean in Korean?' WHERE id = 1364;
UPDATE kp_expressions SET romaja = 'jamaja', heading_en = 'What does -자마자 (jamaja) mean in Korean?' WHERE id = 1365;
UPDATE kp_expressions SET romaja = 'jana', heading_en = 'What does -잖아 (jana) mean in Korean?' WHERE id = 1366;
UPDATE kp_expressions SET romaja = 'jiman', heading_en = 'What does -지만 (jiman) mean in Korean?' WHERE id = 1367;
UPDATE kp_expressions SET romaja = 'gwa wa', heading_en = 'How to use 과/와 (gwa wa) in Korean — "and; with"' WHERE id = 1368;
UPDATE kp_expressions SET romaja = 'kke', heading_en = 'How to use 께 (kke) in Korean — "to (honorific)"' WHERE id = 1369;
UPDATE kp_expressions SET romaja = 'kkeseo', heading_en = 'How to use 께서 (kkeseo) in Korean — "subject marker (honorific)"' WHERE id = 1370;
UPDATE kp_expressions SET romaja = 'mada', heading_en = 'How to use 마다 (mada) in Korean — "every"' WHERE id = 1371;
UPDATE kp_expressions SET romaja = 'man', heading_en = 'How to use 만 (man) in Korean — "only; just"' WHERE id = 1372;
UPDATE kp_expressions SET romaja = 'mankeum', heading_en = 'How to use 만큼 (mankeum) in Korean — "as much as"' WHERE id = 1373;
UPDATE kp_expressions SET romaja = 'bakke', heading_en = 'How to use 밖에 (bakke) in Korean — "only (nothing but)"' WHERE id = 1374;
UPDATE kp_expressions SET romaja = 'buteo kkaji', heading_en = 'How to use 부터 ~까지 (buteo kkaji) in Korean — "from ~ to ~"' WHERE id = 1375;
UPDATE kp_expressions SET romaja = 'ppun', heading_en = 'How to use 뿐 (ppun) in Korean — "only; nothing but"' WHERE id = 1376;
UPDATE kp_expressions SET romaja = 'ege hante', heading_en = 'How to use 에게/한테 (ege hante) in Korean — "to (a person)"' WHERE id = 1377;
UPDATE kp_expressions SET romaja = 'eseobuteo', heading_en = 'How to use 에서부터 (eseobuteo) in Korean — "starting from (a place)"' WHERE id = 1378;
UPDATE kp_expressions SET romaja = 'euro', heading_en = 'How to use 으로 (euro) in Korean — "by; toward; with"' WHERE id = 1379;
UPDATE kp_expressions SET romaja = 'eullaeyo', heading_en = 'How to use 을래요? (eullaeyo) in Korean — "would you like to?"' WHERE id = 1380;
UPDATE kp_expressions SET romaja = 'inama', heading_en = 'How to use 이나마 (inama) in Korean — "even if only; at least"' WHERE id = 1381;
UPDATE kp_expressions SET romaja = 'iran', heading_en = 'How to use 이란 (iran) in Korean — "what we call ~; as for"' WHERE id = 1382;
UPDATE kp_expressions SET romaja = 'ieyo yeyo', heading_en = 'How to use 이에요/예요 (ieyo yeyo) in Korean — "is; am; are"' WHERE id = 1383;
UPDATE kp_expressions SET romaja = 'cheoreom', heading_en = 'How to use 처럼 (cheoreom) in Korean — "like; as if"' WHERE id = 1384;
UPDATE kp_expressions SET romaja = 'keonyeong', heading_en = 'How to use 커녕 (keonyeong) in Korean — "let alone; far from"' WHERE id = 1385;
UPDATE kp_expressions SET romaja = 'hago', heading_en = 'How to use 하고 (hago) in Korean — "and; with"' WHERE id = 1386;
UPDATE kp_expressions SET romaja = 'hanteseo', heading_en = 'How to use 한테서 (hanteseo) in Korean — "from (a person)"' WHERE id = 1387;
UPDATE kp_expressions SET romaja = 'eolmana geollyeoyo', heading_en = 'How to use 얼마나 걸려요? (eolmana geollyeoyo) in Korean — "How long does ~ take?"' WHERE id = 1388;
UPDATE kp_expressions SET romaja = 'kkok bwaya hal ge mwoyeyo', heading_en = 'How to say "What''s a must-see?" in Korean — 꼭 봐야 할 게 뭐예요? (kkok bwaya hal ge mwoyeyo)' WHERE id = 1389;

COMMIT;